// apps/vue-demo/src/components/starwind-runtime/aspect-ratio/AspectRatio.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { computed, type HTMLAttributes, useAttrs } from "vue";
import { aspectRatio, aspectRatioWrapper } from "./variants";

defineOptions({ inheritAttrs: false });

export type AspectRatioProps = Omit<HTMLAttributes, "as" | "class" | "ratio"> &
  VariantProps<typeof aspectRatio> & {
    as?: string;
    ratio?: number;
    class?: ClassValue;
  };
type AspectRatioDeclaredProps = {
  as?: string;
  ratio?: number;
  class?: ClassValue;
} & /* @vue-ignore */ AspectRatioProps;
const { ratio = 1, as: Tag = "div", class: className } = defineProps<AspectRatioDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const wrapperStyle = computed(() => ({ paddingBottom: `${100 / ratio}%` }));
</script>

<template>
  <div :class="aspectRatioWrapper()" :style="wrapperStyle" data-slot="aspect-ratio-wrapper">
    <component
      :is="Tag"
      :class="aspectRatio({ class: className })"
      data-slot="aspect-ratio"
      v-bind="attrs"
    >
      <slot />
    </component>
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/aspect-ratio/AspectRatio.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { aspectRatio, aspectRatioWrapper } from "./variants";

export type AspectRatioProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof aspectRatio> & {
    as?: React.ElementType;
    ratio?: number;
    ref?: React.Ref<HTMLElement>;
  };

function AspectRatio(props: AspectRatioProps) {
  const { ratio = 1, as: Tag = "div", ref, className, children, ...rest } = props;

  const wrapperStyle = { paddingBottom: `${100 / ratio}%` } as React.CSSProperties;

  return (
    <div className={aspectRatioWrapper()} style={wrapperStyle} data-slot="aspect-ratio-wrapper">
      <Tag
        className={aspectRatio({ class: className })}
        data-slot="aspect-ratio"
        {...rest}
        ref={ref}
      >
        {children}
      </Tag>
    </div>
  );
}

export default AspectRatio;
