// apps/react-demo/src/components/starwind-runtime/toast/ToastDescription.tsx
import ToastPrimitive from "@starwind-ui/react/toast";
import type * as React from "react";
import { toastDescription } from "./variants";

export type ToastDescriptionProps = React.ComponentPropsWithoutRef<"div">;

function ToastDescription(props: ToastDescriptionProps) {
  const { className, children, ...rest } = props;

  return (
    <ToastPrimitive.Description
      className={toastDescription({ class: className })}
      {...rest}
      data-slot="toast-description"
    >
      {children}
    </ToastPrimitive.Description>
  );
}

export default ToastDescription;

// apps/vue-demo/src/components/starwind-runtime/toast/ToastDescription.vue
<script setup lang="ts">
import * as ToastPrimitive from "@starwind-ui/vue/toast";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { toastDescription } from "./variants";

defineOptions({ inheritAttrs: false });

export type ToastDescriptionProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ToastDescriptionDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ToastDescriptionProps;
const { class: className } = defineProps<ToastDescriptionDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ToastPrimitive.ToastDescription
    :class="toastDescription({ class: className })"
    v-bind="$attrs"
    data-slot="toast-description"
  >
    <slot />
  </ToastPrimitive.ToastDescription>
</template>
