// apps/react-demo/src/components/starwind-runtime/toast/ToastAction.tsx
import ToastPrimitive from "@starwind-ui/react/toast";
import type * as React from "react";
import { toastAction } from "./variants";

export type ToastActionProps = React.ComponentPropsWithoutRef<"button">;

function ToastAction(props: ToastActionProps) {
  const { className, children, ...rest } = props;

  return (
    <ToastPrimitive.Action
      className={toastAction({ class: className })}
      {...rest}
      data-slot="toast-action"
    >
      {children}
    </ToastPrimitive.Action>
  );
}

export default ToastAction;

// apps/vue-demo/src/components/starwind-runtime/toast/ToastAction.vue
<script setup lang="ts">
import * as ToastPrimitive from "@starwind-ui/vue/toast";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes } from "vue";
import { toastAction } from "./variants";

defineOptions({ inheritAttrs: false });

export type ToastActionProps = Omit<ButtonHTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ToastActionDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ToastActionProps;
const { class: className } = defineProps<ToastActionDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ToastPrimitive.ToastAction
    :class="toastAction({ class: className })"
    v-bind="$attrs"
    data-slot="toast-action"
  >
    <slot />
  </ToastPrimitive.ToastAction>
</template>
