// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownSub.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";

export type DropdownSubProps = React.ComponentPropsWithoutRef<"div"> & {
  closeDelay?: number;
};

function DropdownSub(props: DropdownSubProps) {
  const { className, closeDelay = 200, children, ...rest } = props;

  return (
    <MenuPrimitive.SubmenuRoot
      className={["relative", className].filter(Boolean).join(" ")}
      closeDelay={closeDelay}
      {...rest}
      data-slot="dropdown-sub"
    >
      {children}
    </MenuPrimitive.SubmenuRoot>
  );
}

export default DropdownSub;

// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownSub.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";

defineOptions({ inheritAttrs: false });

export type DropdownSubProps = Omit<HTMLAttributes, "class" | "closeDelay"> & {
  closeDelay?: number;
  class?: ClassValue;
};
type DropdownSubDeclaredProps = {
  closeDelay?: number;
  class?: ClassValue;
} & /* @vue-ignore */ DropdownSubProps;
const { class: className, closeDelay = 200 } = defineProps<DropdownSubDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <MenuPrimitive.MenuSubmenuRoot
    :class="['relative', className].filter(Boolean).join(' ')"
    :close-delay="closeDelay"
    v-bind="$attrs"
    data-slot="dropdown-sub"
  >
    <slot />
  </MenuPrimitive.MenuSubmenuRoot>
</template>
