// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownItem.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdownItem } from "./variants";

export type DropdownItemProps = React.ComponentPropsWithoutRef<"div"> & {
  inset?: boolean;
  disabled?: boolean;
};

function DropdownItem(props: DropdownItemProps) {
  const { className, inset = false, disabled = false, children, ...rest } = props;

  return (
    <MenuPrimitive.Item
      className={dropdownItem({ inset, disabled, class: className })}
      disabled={disabled}
      {...rest}
      data-slot="dropdown-item"
    >
      {children}
    </MenuPrimitive.Item>
  );
}

export default DropdownItem;

// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownItem.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dropdownItem } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownItemProps = Omit<HTMLAttributes, "class" | "disabled" | "inset"> & {
  inset?: boolean;
  disabled?: boolean;
  class?: ClassValue;
};
type DropdownItemDeclaredProps = {
  inset?: boolean;
  disabled?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ DropdownItemProps;
const {
  class: className,
  inset = false,
  disabled = false,
} = defineProps<DropdownItemDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <MenuPrimitive.MenuItem
    :class="dropdownItem({ inset, disabled, class: className })"
    :disabled="disabled"
    v-bind="$attrs"
    data-slot="dropdown-item"
  >
    <slot />
  </MenuPrimitive.MenuItem>
</template>
