// apps/react-demo/src/components/starwind-runtime/dropdown/Dropdown.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdown } from "./variants";

export type DropdownProps = React.ComponentPropsWithoutRef<"div"> & {
  defaultOpen?: boolean;
  open?: boolean;
  disabled?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  onOpenChange?: (
    open: boolean,
    details: import("@starwind-ui/react/menu").MenuOpenChangeDetails,
  ) => void;
  onCloseComplete?: (details: import("@starwind-ui/react/menu").MenuCloseCompleteDetails) => void;
};

function Dropdown(props: DropdownProps) {
  const {
    defaultOpen = false,
    open,
    disabled = false,
    modal = false,
    openOnHover = false,
    closeDelay = 200,
    onOpenChange,
    onCloseComplete,
    className,
    children,
    ...rest
  } = props;

  return (
    <MenuPrimitive.Root
      className={dropdown({ class: className })}
      defaultOpen={defaultOpen}
      open={open}
      disabled={disabled}
      modal={modal}
      openOnHover={openOnHover}
      closeDelay={closeDelay}
      onOpenChange={onOpenChange}
      onCloseComplete={onCloseComplete}
      {...rest}
      data-slot="dropdown"
    >
      {children}
    </MenuPrimitive.Root>
  );
}

export default Dropdown;

// apps/vue-demo/src/components/starwind-runtime/dropdown/Dropdown.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes, useAttrs } from "vue";
import { dropdown } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownProps = Omit<
  HTMLAttributes,
  "class" | "closeDelay" | "defaultOpen" | "disabled" | "modal" | "open" | "openOnHover"
> & {
  defaultOpen?: boolean;
  open?: boolean;
  disabled?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  class?: ClassValue;
};
type DropdownDeclaredProps = {
  defaultOpen?: boolean;
  open?: boolean;
  disabled?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  class?: ClassValue;
} & /* @vue-ignore */ DropdownProps;
const {
  defaultOpen = false,
  open = undefined,
  disabled = false,
  modal = false,
  openOnHover = false,
  closeDelay = 200,
  class: className,
} = defineProps<DropdownDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const emit = defineEmits<{
  closeComplete: [detail: import("@starwind-ui/vue/menu").MenuCloseCompleteDetails];
  openChange: [open: boolean, detail: import("@starwind-ui/vue/menu").MenuOpenChangeDetails];
  "update:open": [value: boolean];
}>();
function handleCloseComplete(
  detail: import("@starwind-ui/vue/menu").MenuCloseCompleteDetails,
): void {
  emit("closeComplete", detail);
}

function handleOpenChange(
  open: boolean,
  detail: import("@starwind-ui/vue/menu").MenuOpenChangeDetails,
): void {
  emit("openChange", open, detail);
}
</script>

<template>
  <MenuPrimitive.MenuRoot
    :class="dropdown({ class: className })"
    :default-open="defaultOpen"
    :open="open"
    :disabled="disabled"
    :modal="modal"
    :open-on-hover="openOnHover"
    :close-delay="closeDelay"
    v-bind="attrs"
    data-slot="dropdown"
    @update:open="emit('update:open', $event)"
    @close-complete="handleCloseComplete"
    @open-change="handleOpenChange"
  >
    <slot />
  </MenuPrimitive.MenuRoot>
</template>
