// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownLabel.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdownLabel } from "./variants";

export type DropdownLabelProps = React.ComponentPropsWithoutRef<"div"> & {
  inset?: boolean;
};

function DropdownLabel(props: DropdownLabelProps) {
  const { className, inset = false, children, ...rest } = props;

  return (
    <MenuPrimitive.Label
      className={dropdownLabel({ inset, class: className })}
      {...rest}
      data-slot="dropdown-label"
    >
      {children}
    </MenuPrimitive.Label>
  );
}

export default DropdownLabel;

// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownLabel.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dropdownLabel } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownLabelProps = Omit<HTMLAttributes, "class" | "inset"> & {
  inset?: boolean;
  class?: ClassValue;
};
type DropdownLabelDeclaredProps = {
  inset?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ DropdownLabelProps;
const { class: className, inset = false } = defineProps<DropdownLabelDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <MenuPrimitive.MenuLabel
    :class="dropdownLabel({ inset, class: className })"
    v-bind="$attrs"
    data-slot="dropdown-label"
  >
    <slot />
  </MenuPrimitive.MenuLabel>
</template>
