// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownSeparator.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdownSeparator } from "./variants";

export type DropdownSeparatorProps = React.ComponentPropsWithoutRef<"div">;

function DropdownSeparator(props: DropdownSeparatorProps) {
  const { className, ...rest } = props;

  return (
    <MenuPrimitive.Separator
      className={dropdownSeparator({ class: className })}
      {...rest}
      data-slot="dropdown-separator"
    />
  );
}

export default DropdownSeparator;

// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownSeparator.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dropdownSeparator } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownSeparatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type DropdownSeparatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ DropdownSeparatorProps;
const { class: className } = defineProps<DropdownSeparatorDeclaredProps>();
defineSlots<{}>();
</script>

<template>
  <MenuPrimitive.MenuSeparator
    :class="dropdownSeparator({ class: className })"
    v-bind="$attrs"
    data-slot="dropdown-separator"
  />
</template>
