// apps/react-demo/src/components/starwind-runtime/aspect-ratio/AspectRatio.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { aspectRatio, aspectRatioWrapper } from "./variants";

export type AspectRatioProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof aspectRatio> & {
    as?: React.ElementType;
    ratio?: number;
    ref?: React.Ref<HTMLElement>;
  };

function AspectRatio(props: AspectRatioProps) {
  const { ratio = 1, as: Tag = "div", ref, className, children, ...rest } = props;

  const wrapperStyle = { paddingBottom: `${100 / ratio}%` } as React.CSSProperties;

  return (
    <div className={aspectRatioWrapper()} style={wrapperStyle} data-slot="aspect-ratio-wrapper">
      <Tag
        className={aspectRatio({ class: className })}
        data-slot="aspect-ratio"
        {...rest}
        ref={ref}
      >
        {children}
      </Tag>
    </div>
  );
}

export default AspectRatio;

// apps/svelte-demo/src/lib/starwind-runtime/aspect-ratio/AspectRatio.svelte
<script module lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { aspectRatio, aspectRatioWrapper } from "./variants.js";

  export type AspectRatioProps = SvelteHTMLElements["div"] & VariantProps<typeof aspectRatio> & { as?: keyof HTMLElementTagNameMap; ref?: HTMLElement; "ratio"?: number; };
</script>

<script lang="ts">
  let {
    "ratio": ratio = 1,
    "as": Tag = "div",
    "class": className,
    ref = $bindable(),
    "children": children,
    ...rest
  }: AspectRatioProps = $props();

  let wrapperStyle = $derived(`padding-bottom: ${100 / ratio}%`);

  let nativeIsVoid = $derived(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"].includes(Tag));
</script>

<div
  class={aspectRatioWrapper({  })}
  style={wrapperStyle}
  data-slot={"aspect-ratio-wrapper"}
>
  {#if nativeIsVoid}
    <svelte:element
      this={Tag}
      class={aspectRatio({ "class": cx(className) })}
      data-slot={"aspect-ratio"}
      {...rest}
      bind:this={ref}
    />
  {:else}
    <svelte:element
      this={Tag}
      class={aspectRatio({ "class": cx(className) })}
      data-slot={"aspect-ratio"}
      {...rest}
      bind:this={ref}
    >
      {@render children?.()}
    </svelte:element>
  {/if}
</div>
