// apps/react-demo/src/components/starwind-runtime/button/Button.tsx
import ButtonPrimitive from "@starwind-ui/react/button";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { button } from "./variants";

export type ButtonProps = React.ComponentPropsWithoutRef<"button"> &
  Omit<React.ComponentPropsWithoutRef<"a">, "type"> &
  VariantProps<typeof button> & {
    as?: "button" | "a";
    "data-slot"?: string;
    focusableWhenDisabled?: boolean;
    ref?: React.Ref<HTMLButtonElement | HTMLAnchorElement>;
  };

function Button(props: ButtonProps) {
  const {
    variant,
    size,
    as: buttonAs,
    href,
    disabled = false,
    focusableWhenDisabled,
    "data-slot": dataSlot = "button",
    ref,
    tabIndex,
    className,
    children,
    ...rest
  } = props;

  if (buttonAs === "a" || href !== undefined) {
    return (
      <a
        className={button({ variant, size, class: className })}
        href={disabled ? undefined : href}
        aria-disabled={disabled ? "true" : undefined}
        data-disabled={disabled ? "" : undefined}
        {...rest}
        tabIndex={disabled ? -1 : tabIndex}
        ref={ref as React.Ref<HTMLAnchorElement>}
        data-slot={dataSlot}
      >
        {children}
      </a>
    );
  }

  return (
    <ButtonPrimitive.Root
      className={button({ variant, size, class: className })}
      disabled={disabled}
      focusableWhenDisabled={focusableWhenDisabled}
      ref={ref as React.Ref<HTMLButtonElement>}
      {...rest}
      data-slot={dataSlot}
    >
      {children}
    </ButtonPrimitive.Root>
  );
}

export default Button;

// apps/vue-demo/src/components/starwind-runtime/button/Button.vue
<script setup lang="ts">
import * as ButtonPrimitive from "@starwind-ui/vue/button";
import type { ClassValue, VariantProps } from "tailwind-variants";
import {
  type AnchorHTMLAttributes,
  type ButtonHTMLAttributes,
  type ComponentPublicInstance,
  nextTick,
  ref,
  useAttrs,
} from "vue";
import { button } from "./variants";

defineOptions({ inheritAttrs: false });

export type ButtonProps = Omit<
  ButtonHTMLAttributes,
  "as" | "class" | "data-slot" | "disabled" | "focusableWhenDisabled" | "href" | "tabindex"
> &
  Omit<
    AnchorHTMLAttributes,
    | "as"
    | "class"
    | "data-slot"
    | "disabled"
    | "focusableWhenDisabled"
    | "href"
    | "tabindex"
    | "type"
  > &
  VariantProps<typeof button> & {
    as?: "button" | "a";
    "data-slot"?: string;
    focusableWhenDisabled?: boolean;
    href?: string;
    disabled?: boolean;
    tabindex?: number;
    class?: ClassValue;
  };
type ButtonDeclaredProps = {
  as?: "button" | "a";
  dataSlot?: string;
  focusableWhenDisabled?: boolean;
  href?: string;
  disabled?: boolean;
  tabindex?: number;
  class?: ClassValue;
  variant?: ButtonProps["variant"];
  size?: ButtonProps["size"];
} & /* @vue-ignore */ ButtonProps;
const {
  variant,
  size,
  as: buttonAs,
  href,
  disabled = false,
  focusableWhenDisabled,
  dataSlot = "button",
  tabindex,
  class: className,
} = defineProps<ButtonDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const element = ref<HTMLButtonElement | HTMLAnchorElement | null>(null);
let pendingPrimitiveRef: ({ element?: HTMLButtonElement | null } & ComponentPublicInstance) | null =
  null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLButtonElement || value instanceof HTMLAnchorElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as
    | ({ element?: HTMLButtonElement | null } & ComponentPublicInstance)
    | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLButtonElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLButtonElement ? exposed.element : null;
  });
}
</script>

<template>
  <template v-if="buttonAs === 'a' || href !== undefined">
    <a
      :ref="setElement"
      :class="button({ variant, size, class: className })"
      :href="disabled ? undefined : href"
      :aria-disabled="disabled ? 'true' : undefined"
      :data-disabled="disabled ? '' : undefined"
      v-bind="attrs"
      :tabindex="disabled ? -1 : tabindex"
      :data-slot="dataSlot || 'button'"
    >
      <slot />
    </a>
  </template>
  <template v-else>
    <ButtonPrimitive.ButtonRoot
      :ref="setElement"
      :class="button({ variant, size, class: className })"
      :disabled="disabled"
      :focusable-when-disabled="focusableWhenDisabled"
      v-bind="attrs"
      :data-slot="dataSlot || 'button'"
    >
      <slot />
    </ButtonPrimitive.ButtonRoot>
  </template>
</template>
