// apps/react-demo/src/components/starwind-runtime/avatar/AvatarFallback.tsx
import AvatarPrimitive from "@starwind-ui/react/avatar";
import type * as React from "react";
import { avatarFallback } from "./variants";

export type AvatarFallbackProps = React.ComponentPropsWithoutRef<"span"> & {
  delay?: number;
  ref?: React.Ref<HTMLSpanElement>;
};

function AvatarFallback(props: AvatarFallbackProps) {
  const { delay, ref, className, children, ...rest } = props;

  return (
    <AvatarPrimitive.Fallback
      className={avatarFallback({ class: className })}
      delay={delay}
      {...rest}
      ref={ref}
      data-slot="avatar-fallback"
    >
      {children}
    </AvatarPrimitive.Fallback>
  );
}

export default AvatarFallback;

// apps/svelte-demo/src/lib/starwind-runtime/avatar/AvatarFallback.svelte
<script module lang="ts">
  import type { ComponentProps } from "svelte";
  import { AvatarFallback as PrimitivePart } from "@starwind-ui/svelte/avatar";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { avatar, avatarFallback, avatarImage } from "./variants.js";
  import { AvatarFallback } from "@starwind-ui/svelte/avatar";

  export type AvatarFallbackProps = ComponentProps<typeof PrimitivePart>;
</script>

<script lang="ts">
  let {
    "delay": delay,
    "class": className,
    "children": children,
    ...rest
  }: AvatarFallbackProps = $props();
</script>

<AvatarFallback
  class={avatarFallback({ "class": cx(className) })}
  delay={delay}
  {...rest}
  data-slot={"avatar-fallback"}
>
  {@render children?.()}
</AvatarFallback>
