// apps/react-demo/src/components/starwind-runtime/tabs/Tabs.tsx
import TabsPrimitive from "@starwind-ui/react/tabs";
import type * as React from "react";
import { tabs } from "./variants";

export type TabsProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "defaultValue" | "onChange" | "value"
> & {
  defaultValue?: import("@starwind-ui/react/tabs").TabsValue;
  onValueChange?: (
    value: import("@starwind-ui/react/tabs").TabsValue,
    details: import("@starwind-ui/react/tabs").TabsValueChangeDetails,
  ) => void;
  orientation?: "horizontal" | "vertical";
  ref?: React.Ref<HTMLDivElement>;
  syncKey?: string;
  value?: import("@starwind-ui/react/tabs").TabsValue;
};

function Tabs(props: TabsProps) {
  const {
    defaultValue,
    onValueChange,
    orientation = "horizontal",
    ref,
    syncKey,
    value,
    className,
    children,
    ...rest
  } = props;

  return (
    <TabsPrimitive.Root
      className={tabs({ class: className })}
      defaultValue={defaultValue}
      onValueChange={onValueChange}
      orientation={orientation}
      ref={ref}
      syncKey={syncKey}
      value={value}
      {...rest}
      data-slot="tabs"
    >
      {children}
    </TabsPrimitive.Root>
  );
}

export default Tabs;

// apps/svelte-demo/src/lib/starwind-runtime/tabs/Tabs.svelte
<script module lang="ts">
  import type { ComponentProps } from "svelte";
  import { untrack } from "svelte";
  import { cx } from "tailwind-variants";
  import { TabsRoot as PrimitivePart } from "@starwind-ui/svelte/tabs";
  import { tabs, tabsContent, tabsList, tabsTrigger } from "./variants.js";
  import { TabsRoot } from "@starwind-ui/svelte/tabs";

  export type TabsProps = ComponentProps<typeof PrimitivePart>;
</script>

<script lang="ts">
  let {
    "defaultValue": defaultValue,
    "orientation": orientation = "horizontal",
    "syncKey": syncKey,
    "class": className,
    "ref": ref,
    "children": children,
    value = $bindable(),
    "value": commandValue,
    "onValueChange": onValueChange,
    ...rest
  }: TabsProps = $props();

  let observedCommand=untrack(()=>commandValue);
  $effect(()=>{const next=commandValue;untrack(()=>{if(Object.is(next,observedCommand))return;observedCommand=next;if(!Object.is(next,value))value=next;});});
</script>

<TabsRoot
  class={tabs({ "class": cx(className) })}
  defaultValue={defaultValue}
  onValueChange={onValueChange}
  orientation={orientation}
  ref={ref}
  syncKey={syncKey}
  {...rest}
  data-slot={"tabs"}
  children={children}
  bind:value={value}
>

</TabsRoot>
