// apps/react-demo/src/components/starwind-runtime/collapsible/CollapsibleContent.tsx
import CollapsiblePrimitive from "@starwind-ui/react/collapsible";
import type * as React from "react";
import { collapsibleContent } from "./variants";

export type CollapsibleContentProps = React.ComponentPropsWithoutRef<"div">;

function CollapsibleContent(props: CollapsibleContentProps) {
  const { className, children, ...rest } = props;

  return (
    <CollapsiblePrimitive.Panel
      className={collapsibleContent({ class: className })}
      {...rest}
      data-slot="collapsible-content"
    >
      {children}
    </CollapsiblePrimitive.Panel>
  );
}

export default CollapsibleContent;

// apps/vue-demo/src/components/starwind-runtime/collapsible/CollapsibleContent.vue
<script setup lang="ts">
import * as CollapsiblePrimitive from "@starwind-ui/vue/collapsible";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { collapsibleContent } from "./variants";

defineOptions({ inheritAttrs: false });

export type CollapsibleContentProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type CollapsibleContentDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ CollapsibleContentProps;
const { class: className } = defineProps<CollapsibleContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <CollapsiblePrimitive.CollapsiblePanel
    :class="collapsibleContent({ class: className })"
    v-bind="$attrs"
    data-slot="collapsible-content"
  >
    <slot />
  </CollapsiblePrimitive.CollapsiblePanel>
</template>
