// apps/react-demo/src/components/starwind-runtime/collapsible/CollapsibleTrigger.tsx
import CollapsiblePrimitive from "@starwind-ui/react/collapsible";
import type * as React from "react";
import { collapsibleTrigger } from "./variants";

export type CollapsibleTriggerProps = React.ComponentPropsWithoutRef<"button"> & {
  asChild?: boolean;
};

function CollapsibleTrigger(props: CollapsibleTriggerProps) {
  const { asChild = false, className, children, ...rest } = props;

  return (
    <CollapsiblePrimitive.Trigger
      className={collapsibleTrigger({ class: className })}
      asChild={asChild}
      {...rest}
      data-slot="collapsible-trigger"
    >
      {children}
    </CollapsiblePrimitive.Trigger>
  );
}

export default CollapsibleTrigger;

// apps/vue-demo/src/components/starwind-runtime/collapsible/CollapsibleTrigger.vue
<script setup lang="ts">
import * as CollapsiblePrimitive from "@starwind-ui/vue/collapsible";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes } from "vue";
import { collapsibleTrigger } from "./variants";

defineOptions({ inheritAttrs: false });

export type CollapsibleTriggerProps = Omit<ButtonHTMLAttributes, "asChild" | "class"> & {
  asChild?: boolean;
  class?: ClassValue;
};
type CollapsibleTriggerDeclaredProps = {
  asChild?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ CollapsibleTriggerProps;
const { asChild = false, class: className } = defineProps<CollapsibleTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <CollapsiblePrimitive.CollapsibleTrigger
    :class="collapsibleTrigger({ class: className })"
    :as-child="asChild"
    v-bind="$attrs"
    data-slot="collapsible-trigger"
  >
    <slot />
  </CollapsiblePrimitive.CollapsibleTrigger>
</template>
