// apps/vue-demo/src/components/starwind-runtime/color-picker/ColorPickerEyeDropper.vue
<script setup lang="ts">
import * as ColorPickerPrimitive from "@starwind-ui/vue/color-picker";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes } from "vue";
import { colorPickerAction } from "./variants";

defineOptions({ inheritAttrs: false });

export type ColorPickerEyeDropperProps = Omit<ButtonHTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ColorPickerEyeDropperDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ColorPickerEyeDropperProps;
const { class: className } = defineProps<ColorPickerEyeDropperDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ColorPickerPrimitive.ColorPickerEyeDropperTrigger
    :class="colorPickerAction({ class: className })"
    v-bind="$attrs"
    data-slot="color-picker-eye-dropper"
  >
    <slot />
  </ColorPickerPrimitive.ColorPickerEyeDropperTrigger>
</template>

// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerEyeDropper.tsx
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import type * as React from "react";
import { colorPickerAction } from "./variants";

export type ColorPickerEyeDropperProps = React.ComponentPropsWithoutRef<"button">;

function ColorPickerEyeDropper(props: ColorPickerEyeDropperProps) {
  const { className, children, ...rest } = props;

  return (
    <ColorPickerPrimitive.EyeDropperTrigger
      className={colorPickerAction({ class: className })}
      {...rest}
      data-slot="color-picker-eye-dropper"
    >
      {children}
    </ColorPickerPrimitive.EyeDropperTrigger>
  );
}

export default ColorPickerEyeDropper;
