// apps/vue-demo/src/components/starwind-runtime/color-picker/ColorPickerSwatch.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes } from "vue";
import "./styles.css";
import * as ColorPickerPrimitive from "@starwind-ui/vue/color-picker";
import { colorPickerSwatch } from "./variants";

defineOptions({ inheritAttrs: false });

export type ColorPickerSwatchProps = Omit<ButtonHTMLAttributes, "class" | "disabled" | "value"> & {
  value: import("@starwind-ui/runtime/color-picker").ColorPickerValue;
  disabled?: boolean;
  class?: ClassValue;
};
type ColorPickerSwatchDeclaredProps = {
  value: import("@starwind-ui/runtime/color-picker").ColorPickerValue;
  disabled?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ ColorPickerSwatchProps;
const { value, disabled = false, class: className } = defineProps<ColorPickerSwatchDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ColorPickerPrimitive.ColorPickerSwatch
    :swatch-value="value"
    :swatch-disabled="disabled"
    :class="colorPickerSwatch({ class: className })"
    v-bind="$attrs"
    data-slot="color-picker-swatch"
  >
    <ColorPickerPrimitive.ColorPickerTransparencyGrid
      class="pointer-events-none absolute inset-0 size-full"
      data-slot="color-picker-transparency-grid"
    />
    <span
      class="pointer-events-none absolute inset-0 size-full"
      data-slot="color-picker-swatch-color"
    />
    <slot />
  </ColorPickerPrimitive.ColorPickerSwatch>
</template>

// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerSwatch.tsx
import type * as React from "react";
import "./styles.css";
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import { colorPickerSwatch } from "./variants";

export type ColorPickerSwatchProps = Omit<React.ComponentPropsWithoutRef<"button">, "value"> & {
  value: import("@starwind-ui/react/color-picker").ColorPickerValue;
  disabled?: boolean;
};

function ColorPickerSwatch(props: ColorPickerSwatchProps) {
  const { value, disabled = false, className, children, ...rest } = props;

  return (
    <ColorPickerPrimitive.Swatch
      swatchValue={value}
      swatchDisabled={disabled}
      className={colorPickerSwatch({ class: className })}
      {...rest}
      data-slot="color-picker-swatch"
    >
      <ColorPickerPrimitive.TransparencyGrid
        className="pointer-events-none absolute inset-0 size-full"
        data-slot="color-picker-transparency-grid"
      />

      <span
        className="pointer-events-none absolute inset-0 size-full"
        data-slot="color-picker-swatch-color"
      />

      {children}
    </ColorPickerPrimitive.Swatch>
  );
}

export default ColorPickerSwatch;
