// apps/svelte-demo/src/lib/starwind-runtime/color-picker/ColorPickerTrigger.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { colorPicker, colorPickerLabel, colorPickerControl, colorPickerTrigger, colorPickerContent, colorPickerInput, colorPickerValueInputLayout, colorPickerArea, colorPickerAreaThumb, colorPickerSliders, colorPickerSliderActionRow, colorPickerValueFormatRow, colorPickerSeparator, colorPickerChannelSlider, colorPickerChannelSliderThumb, colorPickerChannelInputLayout, colorPickerSwatch, colorPickerSwatchGroup, colorPickerValueSwatch, colorPickerFormatSelectTrigger, colorPickerAction, colorPickerHiddenInput, colorPickerChannelInput, colorPickerValueInput, colorPickerNativeFormatSelectWrapper, colorPickerNativeFormatSelect, colorPickerNativeFormatSelectIcon } from "./variants.js";
  import { PopoverTrigger } from "@starwind-ui/svelte/popover";
  import { ColorPickerValueSwatch } from "@starwind-ui/svelte/color-picker";
  import { ColorPickerTransparencyGrid } from "@starwind-ui/svelte/color-picker";
  import { ColorPickerValueText } from "@starwind-ui/svelte/color-picker";

  export type ColorPickerTriggerProps = ComponentProps<typeof PopoverTrigger> & {children?:Snippet; showValueText?: boolean; };
</script>

<script lang="ts">
  let {
    "class": className,
    "showValueText": showValueText = true,
    "children": children,
    ...rest
  }: ColorPickerTriggerProps = $props();
</script>

<PopoverTrigger
  class={colorPickerTrigger({ "class": cx(className) })}
  {...rest}
  data-slot={"color-picker-trigger"}
>
  {@render children?.()}
  <ColorPickerValueSwatch
    class={colorPickerValueSwatch({  })}
    data-slot={"color-picker-value-swatch"}
  >
    <ColorPickerTransparencyGrid
      class={"pointer-events-none absolute inset-0 size-full"}
      data-slot={"color-picker-transparency-grid"}
    >

    </ColorPickerTransparencyGrid>
    <span
      class={"pointer-events-none absolute inset-0 size-full"}
      data-slot={"color-picker-value-swatch-color"}
    >

    </span>
  </ColorPickerValueSwatch>
  {#if showValueText}
    <ColorPickerValueText
      data-slot={"color-picker-value-text"}
    >

    </ColorPickerValueText>
  {/if}
</PopoverTrigger>

// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerTrigger.tsx
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { PopoverTrigger } from "../popover";
import { colorPickerTrigger, colorPickerValueSwatch } from "./variants";

export type ColorPickerTriggerProps = React.ComponentProps<typeof PopoverTrigger> &
  VariantProps<typeof colorPickerTrigger> & {
    showValueText?: boolean;
  };

function ColorPickerTrigger(props: ColorPickerTriggerProps) {
  const { className, size = "md", showValueText = true, children, ...rest } = props;

  return (
    <PopoverTrigger
      className={colorPickerTrigger({ size, class: className })}
      {...rest}
      data-slot="color-picker-trigger"
    >
      {children}

      <ColorPickerPrimitive.ValueSwatch
        className={colorPickerValueSwatch({ size })}
        data-slot="color-picker-value-swatch"
      >
        <ColorPickerPrimitive.TransparencyGrid
          className="pointer-events-none absolute inset-0 size-full"
          data-slot="color-picker-transparency-grid"
        />

        <span
          className="pointer-events-none absolute inset-0 size-full"
          data-slot="color-picker-value-swatch-color"
        />
      </ColorPickerPrimitive.ValueSwatch>

      {showValueText && <ColorPickerPrimitive.ValueText data-slot="color-picker-value-text" />}
    </PopoverTrigger>
  );
}

export default ColorPickerTrigger;
