// apps/vue-demo/src/components/starwind-runtime/color-picker/ColorPickerChannelInput.vue
<script setup lang="ts">
import * as ColorPickerPrimitive from "@starwind-ui/vue/color-picker";
import type { ClassValue } from "tailwind-variants";
import { type InputHTMLAttributes } from "vue";
import { colorPickerChannelInput, colorPickerChannelInputLayout } from "./variants";

defineOptions({ inheritAttrs: false });

export type ColorPickerChannelInputProps = Omit<InputHTMLAttributes, "channel" | "class"> & {
  channel: import("@starwind-ui/runtime/color-picker").ColorPickerChannel;
  class?: ClassValue;
};
type ColorPickerChannelInputDeclaredProps = {
  channel: import("@starwind-ui/runtime/color-picker").ColorPickerChannel;
  class?: ClassValue;
};
const { channel, class: className } = defineProps<ColorPickerChannelInputDeclaredProps>();
defineSlots<{}>();
</script>

<template>
  <ColorPickerPrimitive.ColorPickerChannelInput
    :class="
      [colorPickerChannelInput(), colorPickerChannelInputLayout(), className]
        .filter(Boolean)
        .join(' ')
    "
    :channel="channel"
    v-bind="$attrs"
    data-slot="color-picker-channel-input"
  />
</template>

// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerChannelInput.tsx
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import type * as React from "react";
import { colorPickerChannelInput, colorPickerChannelInputLayout } from "./variants";

export type ColorPickerChannelInputProps = React.ComponentPropsWithoutRef<"input"> & {
  channel: import("@starwind-ui/react/color-picker").ColorPickerChannel;
};

function ColorPickerChannelInput(props: ColorPickerChannelInputProps) {
  const { channel, className, ...rest } = props;

  return (
    <ColorPickerPrimitive.ChannelInput
      className={[colorPickerChannelInput(), colorPickerChannelInputLayout(), className]
        .filter(Boolean)
        .join(" ")}
      channel={channel}
      {...rest}
      data-slot="color-picker-channel-input"
    />
  );
}

export default ColorPickerChannelInput;
