// apps/react-demo/src/components/starwind-runtime/select/SelectSeparator.tsx
import SelectPrimitive from "@starwind-ui/react/select";
import type * as React from "react";
import { selectSeparator } from "./variants";

export type SelectSeparatorProps = React.ComponentPropsWithoutRef<"div">;

function SelectSeparator(props: SelectSeparatorProps) {
  const { className, ...rest } = props;

  return (
    <SelectPrimitive.Separator
      className={selectSeparator({ class: className })}
      {...rest}
      data-slot="select-separator"
    />
  );
}

export default SelectSeparator;

// apps/vue-demo/src/components/starwind-runtime/select/SelectSeparator.vue
<script setup lang="ts">
import * as SelectPrimitive from "@starwind-ui/vue/select";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { selectSeparator } from "./variants";

defineOptions({ inheritAttrs: false });

export type SelectSeparatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type SelectSeparatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ SelectSeparatorProps;
const { class: className } = defineProps<SelectSeparatorDeclaredProps>();
defineSlots<{}>();
</script>

<template>
  <SelectPrimitive.SelectSeparator
    :class="selectSeparator({ class: className })"
    v-bind="$attrs"
    data-slot="select-separator"
  />
</template>
