// apps/react-demo/src/components/starwind-runtime/select/SelectLabel.tsx
import SelectPrimitive from "@starwind-ui/react/select";
import type * as React from "react";
import { selectLabel } from "./variants";

export type SelectLabelProps = React.ComponentPropsWithoutRef<"div">;

function SelectLabel(props: SelectLabelProps) {
  const { className, children, ...rest } = props;

  return (
    <SelectPrimitive.GroupLabel
      className={selectLabel({ class: className })}
      {...rest}
      data-slot="select-label"
    >
      {children}
    </SelectPrimitive.GroupLabel>
  );
}

export default SelectLabel;

// apps/vue-demo/src/components/starwind-runtime/select/SelectLabel.vue
<script setup lang="ts">
import * as SelectPrimitive from "@starwind-ui/vue/select";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { selectLabel } from "./variants";

defineOptions({ inheritAttrs: false });

export type SelectLabelProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type SelectLabelDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ SelectLabelProps;
const { class: className } = defineProps<SelectLabelDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <SelectPrimitive.SelectGroupLabel
    :class="selectLabel({ class: className })"
    v-bind="$attrs"
    data-slot="select-label"
  >
    <slot />
  </SelectPrimitive.SelectGroupLabel>
</template>
