// apps/react-demo/src/components/starwind-runtime/button/Button.tsx
import ButtonPrimitive from "@starwind-ui/react/button";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { button } from "./variants";

export type ButtonProps = React.ComponentPropsWithoutRef<"button"> &
  Omit<React.ComponentPropsWithoutRef<"a">, "type"> &
  VariantProps<typeof button> & {
    as?: "button" | "a";
    "data-slot"?: string;
    focusableWhenDisabled?: boolean;
    ref?: React.Ref<HTMLButtonElement | HTMLAnchorElement>;
  };

function Button(props: ButtonProps) {
  const {
    variant,
    size,
    as: buttonAs,
    href,
    disabled = false,
    focusableWhenDisabled,
    "data-slot": dataSlot = "button",
    ref,
    tabIndex,
    className,
    children,
    ...rest
  } = props;

  if (buttonAs === "a" || href !== undefined) {
    return (
      <a
        className={button({ variant, size, class: className })}
        href={disabled ? undefined : href}
        aria-disabled={disabled ? "true" : undefined}
        data-disabled={disabled ? "" : undefined}
        {...rest}
        tabIndex={disabled ? -1 : tabIndex}
        ref={ref as React.Ref<HTMLAnchorElement>}
        data-slot={dataSlot}
      >
        {children}
      </a>
    );
  }

  return (
    <ButtonPrimitive.Root
      className={button({ variant, size, class: className })}
      disabled={disabled}
      focusableWhenDisabled={focusableWhenDisabled}
      ref={ref as React.Ref<HTMLButtonElement>}
      {...rest}
      data-slot={dataSlot}
    >
      {children}
    </ButtonPrimitive.Root>
  );
}

export default Button;

// apps/svelte-demo/src/lib/starwind-runtime/button/Button.svelte
<script module lang="ts">
  import type { ComponentProps } from "svelte";
  import { untrack } from "svelte";
  import type { HTMLAnchorAttributes } from "svelte/elements";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { ButtonRoot } from "@starwind-ui/svelte/button";
  import { button } from "./variants.js";

  type NativeButtonProps = ComponentProps<typeof ButtonRoot>;
  type CommonProps = VariantProps<typeof button> & { "data-slot"?: string; "focusableWhenDisabled"?: boolean; };
  type AnchorProps = Omit<HTMLAnchorAttributes, "type" | "children"> & CommonProps & {
    children?: NativeButtonProps["children"];
    disabled?: boolean;
    ref?: (element: HTMLAnchorElement | null) => void;
  } & ({ as: "a"; href?: string } | { as?: "a" | "button"; href: string });
  export type ButtonProps = (NativeButtonProps & CommonProps & { as?: "button"; href?: undefined }) | AnchorProps;
</script>

<script lang="ts">
  let {
    "variant": variant,
    "size": size,
    "as": buttonAs,
    "href": href,
    "disabled": disabled = false,
    "focusableWhenDisabled": focusableWhenDisabled,
    "data-slot": dataSlot = "button",
    "class": className,
    "ref": ref,
    "tabindex": tabindex,
    "children": children,
    ...rest
  }: ButtonProps = $props();

  let nativeAnchorProps = $derived({ ...rest } as HTMLAnchorAttributes);
  let anchorRef = $derived(ref as ((element: HTMLAnchorElement | null) => void) | undefined);
  function attachAnchor(element: HTMLAnchorElement): () => void {
    $effect(() => {
      const callback = anchorRef;
      untrack(() => callback?.(element));
      return () => untrack(() => callback?.(null));
    });
    return () => {};
  }
</script>

{#if buttonAs === "a" || href !== undefined}
  <a
    class={button({ "variant": variant, "size": size, "class": cx(className) })}
    href={disabled ? undefined : href}
    aria-disabled={disabled ? "true" : undefined}
    data-disabled={disabled ? "" : undefined}
    {...nativeAnchorProps}
    data-slot={dataSlot}
    tabindex={disabled ? -1 : tabindex}
    {@attach attachAnchor}
  >
    {@render children?.()}
  </a>
{:else}
  <ButtonRoot
    class={button({ "variant": variant, "size": size, "class": cx(className) })}
    disabled={disabled}
    focusableWhenDisabled={focusableWhenDisabled}
    {...rest as NativeButtonProps}
    data-slot={dataSlot}
    ref={ref as NativeButtonProps["ref"]}
    tabindex={tabindex}
  >
    {@render children?.()}
  </ButtonRoot>
{/if}
