// apps/vue-demo/src/components/starwind-runtime/scroll-area/ScrollAreaViewport.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type ComponentPublicInstance, type HTMLAttributes, nextTick, ref } from "vue";
import "./styles.css";
import * as ScrollAreaPrimitive from "@starwind-ui/vue/scroll-area";
import { scrollAreaViewport } from "./variants";

defineOptions({ inheritAttrs: false });

export type ScrollAreaViewportProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ScrollAreaViewportDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ScrollAreaViewportProps;
const { class: className } = defineProps<ScrollAreaViewportDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLDivElement | null>(null);
let pendingPrimitiveRef: ({ element?: HTMLDivElement | null } & ComponentPublicInstance) | null =
  null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLDivElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as ({ element?: HTMLDivElement | null } & ComponentPublicInstance) | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLDivElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLDivElement ? exposed.element : null;
  });
}
</script>

<template>
  <ScrollAreaPrimitive.ScrollAreaViewport
    :ref="setElement"
    :class="scrollAreaViewport({ class: className })"
    v-bind="$attrs"
    data-slot="scroll-area-viewport"
  >
    <slot />
  </ScrollAreaPrimitive.ScrollAreaViewport>
</template>

// apps/react-demo/src/components/starwind-runtime/scroll-area/ScrollAreaViewport.tsx
import type * as React from "react";
import "./styles.css";
import ScrollAreaPrimitive from "@starwind-ui/react/scroll-area";
import { scrollAreaViewport } from "./variants";

export type ScrollAreaViewportProps = React.ComponentPropsWithoutRef<"div"> & {
  ref?: React.Ref<HTMLDivElement>;
};

function ScrollAreaViewport(props: ScrollAreaViewportProps) {
  const { ref, className, children, ...rest } = props;

  return (
    <ScrollAreaPrimitive.Viewport
      className={scrollAreaViewport({ class: className })}
      {...rest}
      ref={ref}
      data-slot="scroll-area-viewport"
    >
      {children}
    </ScrollAreaPrimitive.Viewport>
  );
}

export default ScrollAreaViewport;
