// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuCheckboxItemIndicator.tsx
import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import type * as React from "react";
import { contextMenuCheckboxItemIndicator } from "./variants";

export type ContextMenuCheckboxItemIndicatorProps = React.ComponentPropsWithoutRef<"span">;

function ContextMenuCheckboxItemIndicator(props: ContextMenuCheckboxItemIndicatorProps) {
  const { className, children, ...rest } = props;

  return (
    <ContextMenuPrimitive.CheckboxItemIndicator
      className={contextMenuCheckboxItemIndicator({ class: className })}
      {...rest}
      data-slot="context-menu-checkbox-item-indicator"
    >
      {children}
    </ContextMenuPrimitive.CheckboxItemIndicator>
  );
}

export default ContextMenuCheckboxItemIndicator;

// apps/vue-demo/src/components/starwind-runtime/context-menu/ContextMenuCheckboxItemIndicator.vue
<script setup lang="ts">
import * as ContextMenuPrimitive from "@starwind-ui/vue/context-menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { contextMenuCheckboxItemIndicator } from "./variants";

defineOptions({ inheritAttrs: false });

export type ContextMenuCheckboxItemIndicatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ContextMenuCheckboxItemIndicatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ContextMenuCheckboxItemIndicatorProps;
const { class: className } = defineProps<ContextMenuCheckboxItemIndicatorDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ContextMenuPrimitive.ContextMenuCheckboxItemIndicator
    :class="contextMenuCheckboxItemIndicator({ class: className })"
    v-bind="$attrs"
    data-slot="context-menu-checkbox-item-indicator"
  >
    <slot />
  </ContextMenuPrimitive.ContextMenuCheckboxItemIndicator>
</template>
