// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuSubContent.tsx
"use client";

import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import type * as React from "react";
import { contextMenuContent } from "./variants";

export type ContextMenuSubContentProps = React.ComponentPropsWithoutRef<"div"> & {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
  portalContainer?: string;
  disablePortal?: boolean;
};

function ContextMenuSubContent(props: ContextMenuSubContentProps) {
  const {
    className,
    side = "right",
    align = "start",
    sideOffset = 0,
    avoidCollisions = true,
    portalContainer,
    disablePortal = false,
    children,
    ...rest
  } = props;

  const subContentClassName = className;

  return (
    <ContextMenuPrimitive.Portal
      container={portalContainer}
      disabled={disablePortal}
      data-slot="context-menu-sub-portal"
    >
      <ContextMenuPrimitive.Popup
        className={contextMenuContent({ class: subContentClassName })}
        side={side}
        align={align}
        sideOffset={sideOffset}
        avoidCollisions={avoidCollisions}
        {...rest}
        data-slot="context-menu-sub-content"
      >
        {children}
      </ContextMenuPrimitive.Popup>
    </ContextMenuPrimitive.Portal>
  );
}

export default ContextMenuSubContent;

// apps/vue-demo/src/components/starwind-runtime/context-menu/ContextMenuSubContent.vue
<script setup lang="ts">
import * as ContextMenuPrimitive from "@starwind-ui/vue/context-menu";
import type { ClassValue } from "tailwind-variants";
import { computed, type HTMLAttributes } from "vue";
import { contextMenuContent } from "./variants";

defineOptions({ inheritAttrs: false });

export type ContextMenuSubContentProps = Omit<
  HTMLAttributes,
  | "align"
  | "avoidCollisions"
  | "class"
  | "disablePortal"
  | "portalContainer"
  | "side"
  | "sideOffset"
> & {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
  portalContainer?: string;
  disablePortal?: boolean;
  class?: ClassValue;
};
type ContextMenuSubContentDeclaredProps = {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
  portalContainer?: string;
  disablePortal?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ ContextMenuSubContentProps;
const {
  class: className,
  side = "right",
  align = "start",
  sideOffset = 0,
  avoidCollisions = true,
  portalContainer,
  disablePortal = false,
} = defineProps<ContextMenuSubContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const subContentClassName = computed(() => className);
</script>

<template>
  <ContextMenuPrimitive.ContextMenuPortal
    :container="portalContainer"
    :disabled="disablePortal"
    data-slot="context-menu-sub-portal"
  >
    <ContextMenuPrimitive.ContextMenuPopup
      :class="contextMenuContent({ class: subContentClassName })"
      :side="side"
      :align="align"
      :side-offset="sideOffset"
      :avoid-collisions="avoidCollisions"
      v-bind="$attrs"
      data-slot="context-menu-sub-content"
    >
      <slot />
    </ContextMenuPrimitive.ContextMenuPopup>
  </ContextMenuPrimitive.ContextMenuPortal>
</template>
