// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuTrigger.tsx
import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import type * as React from "react";
import { contextMenuTrigger } from "./variants";

export type ContextMenuTriggerProps = React.ComponentPropsWithoutRef<"div"> & {
  disabled?: boolean;
  ref?: React.Ref<HTMLDivElement>;
};

function ContextMenuTrigger(props: ContextMenuTriggerProps) {
  const { disabled = false, ref, className, children, ...rest } = props;

  return (
    <ContextMenuPrimitive.Trigger
      className={contextMenuTrigger({ class: className })}
      disabled={disabled}
      ref={ref}
      {...rest}
      data-slot="context-menu-trigger"
    >
      {children}
    </ContextMenuPrimitive.Trigger>
  );
}

export default ContextMenuTrigger;

// apps/vue-demo/src/components/starwind-runtime/context-menu/ContextMenuTrigger.vue
<script setup lang="ts">
import * as ContextMenuPrimitive from "@starwind-ui/vue/context-menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { contextMenuTrigger } from "./variants";

defineOptions({ inheritAttrs: false });

export type ContextMenuTriggerProps = Omit<HTMLAttributes, "class" | "disabled"> & {
  disabled?: boolean;
  class?: ClassValue;
};
type ContextMenuTriggerDeclaredProps = {
  disabled?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ ContextMenuTriggerProps;
const { disabled = false, class: className } = defineProps<ContextMenuTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ContextMenuPrimitive.ContextMenuTrigger
    :class="contextMenuTrigger({ class: className })"
    :disabled="disabled"
    v-bind="$attrs"
    data-slot="context-menu-trigger"
  >
    <slot />
  </ContextMenuPrimitive.ContextMenuTrigger>
</template>
