// apps/svelte-demo/src/lib/starwind-runtime/textarea/Textarea.svelte
<script module lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { textarea } from "./variants.js";

  export type TextareaProps = Omit<SvelteHTMLElements["textarea"], "children" | "value" | "defaultValue" | "defaultvalue"> & VariantProps<typeof textarea> & { value?: string | null; defaultValue?: string | null; defaultvalue?: string | null; } & { ref?: HTMLTextAreaElement;  };
</script>

<script lang="ts">
  let {
    "size": size,
    "data-slot": dataSlot = "textarea",
    "class": className,
    value = $bindable(),
    ref = $bindable(),
    ...rest
  }: TextareaProps = $props();

  let nativeProps = $derived.by(() => {
    const props = { ...rest };
    for (const key of ["children","value"]) delete (props as Record<string, unknown>)[key];
    return props;
  });
</script>

<textarea
  data-sw-textarea
  class={textarea({ "size": size, "class": cx(className) })}
  data-slot={dataSlot}
  {...nativeProps}
  bind:value={value}
  bind:this={ref}
></textarea>

// apps/react-demo/src/components/starwind-runtime/textarea/Textarea.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { textarea } from "./variants";

export type TextareaProps = Omit<React.ComponentPropsWithoutRef<"textarea">, "children"> &
  VariantProps<typeof textarea> & {
    "data-slot"?: string;
    ref?: React.Ref<HTMLTextAreaElement>;
  };

function Textarea(props: TextareaProps) {
  const { size, ref, "data-slot": dataSlot = "textarea", className, ...rest } = props;

  return (
    <textarea
      data-sw-textarea
      className={textarea({ size, class: className })}
      data-slot={dataSlot}
      {...rest}
      ref={ref}
    />
  );
}

export default Textarea;
