// apps/react-demo/src/components/starwind-runtime/dialog/DialogHeader.tsx
import type * as React from "react";
import { dialogHeader } from "./variants";

export type DialogHeaderProps = React.ComponentPropsWithoutRef<"div">;

function DialogHeader(props: DialogHeaderProps) {
  const { className, children, ...rest } = props;

  return (
    <div className={dialogHeader({ class: className })} {...rest} data-slot="dialog-header">
      {children}
    </div>
  );
}

export default DialogHeader;

// apps/svelte-demo/src/lib/starwind-runtime/dialog/DialogHeader.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { untrack } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  import { cx } from "tailwind-variants";
  import { dialogBackdrop, dialogContent, dialogCloseButton, dialogDescription, dialogFooter, dialogHeader, dialogTitle } from "./variants.js";

  export type DialogHeaderProps = HTMLAttributes<HTMLDivElement> & { ref?: (element: HTMLDivElement | null) => void; children?: Snippet };
</script>

<script lang="ts">
  let {
    "class": className,
    "ref": ref,
    "children": children,
    ...rest
  }: DialogHeaderProps = $props();

  let nativeProps = $derived({ ...rest });
  const attachNative: Attachment<HTMLDivElement> = (element) => {
    $effect(() => { const callback = ref; untrack(() => callback?.(element)); return () => untrack(() => callback?.(null)); });
  };
</script>

<div
  class={dialogHeader({ "class": cx(className) })}
  {...nativeProps}
  data-slot={"dialog-header"}
  {@attach attachNative}
>
  {@render children?.()}
</div>
