// apps/vue-demo/src/components/starwind-runtime/pagination/Pagination.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { pagination } from "./variants";

defineOptions({ inheritAttrs: false });

export type PaginationProps = Omit<HTMLAttributes, "class" | "size"> & {
  size?: "sm" | "md" | "lg";
  class?: ClassValue;
};
type PaginationDeclaredProps = {
  size?: "sm" | "md" | "lg";
  class?: ClassValue;
} & /* @vue-ignore */ PaginationProps;
const { size = "md", class: className } = defineProps<PaginationDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLElement | null>(null);
defineExpose({ element });
</script>

<template>
  <nav
    ref="element"
    role="navigation"
    aria-label="pagination"
    :class="pagination({ class: className })"
    v-bind="$attrs"
    :data-size="size"
    data-slot="pagination"
  >
    <slot />
  </nav>
</template>

// apps/react-demo/src/components/starwind-runtime/pagination/Pagination.tsx
import type * as React from "react";
import { pagination } from "./variants";

export type PaginationProps = React.ComponentPropsWithoutRef<"nav"> & {
  size?: "sm" | "md" | "lg";
  ref?: React.Ref<HTMLElement>;
};

function Pagination(props: PaginationProps) {
  const { size = "md", ref, className, children, ...rest } = props;

  return (
    <nav
      role="navigation"
      aria-label="pagination"
      className={pagination({ class: className })}
      {...rest}
      ref={ref}
      data-size={size}
      data-slot="pagination"
    >
      {children}
    </nav>
  );
}

export default Pagination;
