// apps/vue-demo/src/components/starwind-runtime/label/Label.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { label } from "./variants";

defineOptions({ inheritAttrs: false });

export type LabelProps = Omit<HTMLAttributes, "class"> &
  VariantProps<typeof label> & {
    class?: ClassValue;
  };
type LabelDeclaredProps = {
  class?: ClassValue;
  size?: LabelProps["size"];
} & /* @vue-ignore */ LabelProps;
const { size, class: className } = defineProps<LabelDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLLabelElement | null>(null);
defineExpose({ element });
</script>

<template>
  <label
    ref="element"
    data-sw-label
    :class="label({ size, class: className })"
    v-bind="$attrs"
    data-slot="label"
  >
    <slot />
  </label>
</template>

// apps/react-demo/src/components/starwind-runtime/label/Label.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { label } from "./variants";

export type LabelProps = React.ComponentPropsWithoutRef<"label"> &
  VariantProps<typeof label> & {
    ref?: React.Ref<HTMLLabelElement>;
  };

function Label(props: LabelProps) {
  const { size, ref, className, children, ...rest } = props;

  return (
    <label
      data-sw-label
      className={label({ size, class: className })}
      {...rest}
      ref={ref}
      data-slot="label"
    >
      {children}
    </label>
  );
}

export default Label;
