// apps/react-demo/src/components/starwind-runtime/alert-dialog/AlertDialogTitle.tsx
import AlertDialogPrimitive from "@starwind-ui/react/alert-dialog";
import type * as React from "react";
import { alertDialogTitle } from "./variants";

export type AlertDialogTitleProps = React.ComponentPropsWithoutRef<"h2">;

function AlertDialogTitle(props: AlertDialogTitleProps) {
  const { className, children, ...rest } = props;

  return (
    <AlertDialogPrimitive.Title
      className={alertDialogTitle({ class: className })}
      {...rest}
      data-slot="alert-dialog-title"
    >
      {children}
    </AlertDialogPrimitive.Title>
  );
}

export default AlertDialogTitle;

// apps/vue-demo/src/components/starwind-runtime/alert-dialog/AlertDialogTitle.vue
<script setup lang="ts">
import * as AlertDialogPrimitive from "@starwind-ui/vue/alert-dialog";
import type { ClassValue } from "tailwind-variants";
import { type ComponentPublicInstance, type HTMLAttributes, nextTick, ref } from "vue";
import { alertDialogTitle } from "./variants";

defineOptions({ inheritAttrs: false });

export type AlertDialogTitleProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type AlertDialogTitleDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ AlertDialogTitleProps;
const { class: className } = defineProps<AlertDialogTitleDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLHeadingElement | null>(null);
let pendingPrimitiveRef:
  | ({ element?: HTMLHeadingElement | null } & ComponentPublicInstance)
  | null = null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLHeadingElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as
    | ({ element?: HTMLHeadingElement | null } & ComponentPublicInstance)
    | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLHeadingElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLHeadingElement ? exposed.element : null;
  });
}
</script>

<template>
  <AlertDialogPrimitive.AlertDialogTitle
    :ref="setElement"
    :class="alertDialogTitle({ class: className })"
    v-bind="$attrs"
    data-slot="alert-dialog-title"
  >
    <slot />
  </AlertDialogPrimitive.AlertDialogTitle>
</template>
