// apps/react-demo/src/components/starwind-runtime/alert-dialog/AlertDialogFooter.tsx
import type * as React from "react";
import { alertDialogFooter } from "./variants";

export type AlertDialogFooterProps = React.ComponentPropsWithoutRef<"div">;

function AlertDialogFooter(props: AlertDialogFooterProps) {
  const { className, children, ...rest } = props;

  return (
    <div
      className={alertDialogFooter({ class: className })}
      {...rest}
      data-slot="alert-dialog-footer"
    >
      {children}
    </div>
  );
}

export default AlertDialogFooter;

// apps/vue-demo/src/components/starwind-runtime/alert-dialog/AlertDialogFooter.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { alertDialogFooter } from "./variants";

defineOptions({ inheritAttrs: false });

export type AlertDialogFooterProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type AlertDialogFooterDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ AlertDialogFooterProps;
const { class: className } = defineProps<AlertDialogFooterDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    :class="alertDialogFooter({ class: className })"
    v-bind="$attrs"
    data-slot="alert-dialog-footer"
  >
    <slot />
  </div>
</template>
