// apps/react-demo/src/components/starwind-runtime/combobox/ComboboxContent.tsx
"use client";

import ComboboxPrimitive from "@starwind-ui/react/combobox";
import type * as React from "react";
import { comboboxContent, comboboxList } from "./variants";

export type ComboboxContentProps = React.ComponentPropsWithoutRef<"div"> & {
  align?: "start" | "center" | "end";
  alignOffset?: number;
  avoidCollisions?: boolean;
  keepMounted?: boolean;
  side?: "top" | "right" | "bottom" | "left";
  sideOffset?: number;
  size?: "sm" | "md" | "lg";
  portalContainer?: string;
  disablePortal?: boolean;
};

function ComboboxContent(props: ComboboxContentProps) {
  const {
    align = "start",
    alignOffset = 0,
    avoidCollisions = true,
    className,
    keepMounted = false,
    side = "bottom",
    sideOffset = 4,
    size = "md",
    portalContainer,
    disablePortal = false,
    children,
    ...rest
  } = props;

  return (
    <ComboboxPrimitive.Portal
      container={portalContainer}
      disabled={disablePortal}
      data-slot="combobox-portal"
    >
      <ComboboxPrimitive.Positioner
        align={align}
        alignOffset={alignOffset}
        avoidCollisions={avoidCollisions}
        side={side}
        sideOffset={sideOffset}
        data-slot="combobox-positioner"
      >
        <ComboboxPrimitive.Popup
          className={comboboxContent({ size, class: className })}
          align={align}
          alignOffset={alignOffset}
          avoidCollisions={avoidCollisions}
          keepMounted={keepMounted}
          side={side}
          sideOffset={sideOffset}
          {...rest}
          data-size={size}
          data-slot="combobox-content"
        >
          <ComboboxPrimitive.List className={comboboxList()} data-slot="combobox-list">
            {children}
          </ComboboxPrimitive.List>
        </ComboboxPrimitive.Popup>
      </ComboboxPrimitive.Positioner>
    </ComboboxPrimitive.Portal>
  );
}

export default ComboboxContent;

// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxContent.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxContent, comboboxList } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxContentProps = Omit<
  HTMLAttributes,
  | "align"
  | "alignOffset"
  | "avoidCollisions"
  | "class"
  | "disablePortal"
  | "portalContainer"
  | "side"
  | "sideOffset"
  | "size"
> & {
  align?: "start" | "center" | "end";
  alignOffset?: number;
  avoidCollisions?: boolean;
  side?: "top" | "right" | "bottom" | "left";
  sideOffset?: number;
  size?: "sm" | "md" | "lg";
  portalContainer?: string;
  disablePortal?: boolean;
  class?: ClassValue;
};
type ComboboxContentDeclaredProps = {
  align?: "start" | "center" | "end";
  alignOffset?: number;
  avoidCollisions?: boolean;
  side?: "top" | "right" | "bottom" | "left";
  sideOffset?: number;
  size?: "sm" | "md" | "lg";
  portalContainer?: string;
  disablePortal?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ ComboboxContentProps;
const {
  align = "start",
  alignOffset = 0,
  avoidCollisions = true,
  class: className,
  side = "bottom",
  sideOffset = 4,
  size = "md",
  portalContainer,
  disablePortal = false,
} = defineProps<ComboboxContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxPortal
    :container="portalContainer"
    :disabled="disablePortal"
    data-slot="combobox-portal"
  >
    <ComboboxPrimitive.ComboboxPositioner
      :align="align"
      :align-offset="alignOffset"
      :avoid-collisions="avoidCollisions"
      :side="side"
      :side-offset="sideOffset"
      data-slot="combobox-positioner"
    >
      <ComboboxPrimitive.ComboboxPopup
        :class="comboboxContent({ size, class: className })"
        :align="align"
        :align-offset="alignOffset"
        :avoid-collisions="avoidCollisions"
        :side="side"
        :side-offset="sideOffset"
        v-bind="$attrs"
        :data-size="size"
        data-slot="combobox-content"
      >
        <ComboboxPrimitive.ComboboxList :class="comboboxList()" data-slot="combobox-list">
          <slot />
        </ComboboxPrimitive.ComboboxList>
      </ComboboxPrimitive.ComboboxPopup>
    </ComboboxPrimitive.ComboboxPositioner>
  </ComboboxPrimitive.ComboboxPortal>
</template>
