// apps/react-demo/src/components/starwind-runtime/input-otp/InputOtp.tsx
import InputOtpPrimitive from "@starwind-ui/react/input-otp";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { inputOtp } from "./variants";

export type InputOtpProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "defaultValue" | "id" | "onChange" | "pattern" | "value"
> &
  VariantProps<typeof inputOtp> & {
    defaultValue?: string;
    disabled?: boolean;
    form?: string;
    id?: string;
    maxLength?: number;
    name?: string;
    onValueChange?: (
      value: string,
      details: import("@starwind-ui/react/input-otp").InputOtpValueChangeDetails,
    ) => void;
    pattern?: RegExp | string;
    ref?: React.Ref<HTMLDivElement>;
    readOnly?: boolean;
    required?: boolean;
    size?: "sm" | "md" | "lg";
    value?: string;
  };

function InputOtp(props: InputOtpProps) {
  const {
    defaultValue,
    disabled = false,
    form,
    id,
    maxLength = 6,
    name,
    onValueChange,
    pattern,
    ref,
    readOnly = false,
    required = false,
    size = "md",
    value,
    className,
    children,
    ...rest
  } = props;

  return (
    <InputOtpPrimitive.Root
      className={inputOtp({ class: className })}
      defaultValue={defaultValue}
      disabled={disabled}
      form={form}
      id={id}
      maxLength={maxLength}
      name={name}
      onValueChange={onValueChange}
      pattern={pattern}
      ref={ref}
      readOnly={readOnly}
      required={required}
      value={value}
      {...rest}
      data-size={size}
      data-slot="input-otp"
    >
      {children}
    </InputOtpPrimitive.Root>
  );
}

export default InputOtp;

// apps/svelte-demo/src/lib/starwind-runtime/input-otp/InputOtp.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { untrack } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { InputOtpRoot as PrimitivePart } from "@starwind-ui/svelte/input-otp";
  import { inputOtp, inputOtpGroup, inputOtpSeparator, inputOtpSlot } from "./variants.js";
  import { InputOtpRoot } from "@starwind-ui/svelte/input-otp";

  export type InputOtpProps = ComponentProps<typeof PrimitivePart> & VariantProps<typeof inputOtp> & { size?: "sm" | "md" | "lg" };
</script>

<script lang="ts">
  let {
    "defaultValue": defaultValue,
    "disabled": disabled = false,
    "form": form,
    "id": id,
    "maxLength": maxLength = 6,
    "name": name,
    "pattern": pattern,
    "readOnly": readOnly = false,
    "required": required = false,
    "size": size = "md",
    "class": className,
    "ref": ref,
    value = $bindable(),
    "value": commandValue,
    "onValueChange": onValueChange,
    "children": children,
    ...rest
  }: InputOtpProps = $props();

  // Observe incoming commands after local bindable publication shadows a plain prop.
  let observedCommand = untrack(() => commandValue);
  $effect(() => {
    const next = commandValue;
    untrack(() => {
      if (Object.is(next, observedCommand)) return;
      observedCommand = next;
      if (!Object.is(next, value)) value = next;
    });
  });
</script>

<InputOtpRoot
  class={inputOtp({ "class": cx(className) })}
  defaultValue={defaultValue}
  disabled={disabled}
  form={form}
  id={id}
  maxLength={maxLength}
  name={name}
  onValueChange={onValueChange}
  pattern={pattern}
  ref={ref}
  readOnly={readOnly}
  required={required}
  {...rest}
  data-size={size}
  data-slot={"input-otp"}
  bind:value={value}
>
  {@render children?.()}
</InputOtpRoot>
