// apps/vue-demo/src/components/starwind-runtime/radio-group/RadioGroup.vue
<script setup lang="ts">
import * as RadioGroupPrimitive from "@starwind-ui/vue/radio-group";
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, useAttrs } from "vue";
import { radioGroup } from "./variants";

defineOptions({ inheritAttrs: false });

export type RadioGroupProps = Omit<
  HTMLAttributes,
  | "class"
  | "defaultValue"
  | "disabled"
  | "form"
  | "legend"
  | "modelValue"
  | "name"
  | "onChange"
  | "orientation"
  | "readOnly"
  | "required"
  | "size"
> &
  VariantProps<typeof radioGroup> & {
    defaultValue?: string;
    disabled?: boolean;
    form?: string;
    legend?: string;
    name?: string;
    orientation?: "horizontal" | "vertical";
    readOnly?: boolean;
    required?: boolean;
    size?: "sm" | "md" | "lg";
    class?: ClassValue;
    modelValue?: import("@starwind-ui/vue/radio-group").RadioGroupValue;
  };
type RadioGroupDeclaredProps = {
  defaultValue?: string;
  disabled?: boolean;
  form?: string;
  legend?: string;
  name?: string;
  orientation?: "horizontal" | "vertical";
  readOnly?: boolean;
  required?: boolean;
  size?: "sm" | "md" | "lg";
  class?: ClassValue;
  modelValue?: import("@starwind-ui/vue/radio-group").RadioGroupValue;
} & /* @vue-ignore */ RadioGroupProps;
const {
  defaultValue,
  disabled = false,
  form,
  legend,
  name,
  orientation = "vertical",
  readOnly = false,
  required = false,
  size = "md",
  class: className,
  modelValue,
} = defineProps<RadioGroupDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const emit = defineEmits<{
  valueChange: [
    value: string,
    detail: import("@starwind-ui/vue/radio-group").RadioGroupValueChangeDetails,
  ];
  "update:modelValue": [value: import("@starwind-ui/vue/radio-group").RadioGroupValue];
}>();
function handleValueChange(
  value: string,
  detail: import("@starwind-ui/vue/radio-group").RadioGroupValueChangeDetails,
): void {
  emit("valueChange", value, detail);
}
</script>

<template>
  <RadioGroupPrimitive.RadioGroupRoot
    :class="radioGroup({ orientation, class: className })"
    :default-value="defaultValue"
    :disabled="disabled"
    :form="form"
    :name="name"
    :orientation="orientation"
    :read-only="readOnly"
    :required="required"
    :model-value="modelValue"
    v-bind="{ ...(legend === undefined ? {} : { 'aria-label': legend }), ...attrs }"
    :data-size="size"
    data-slot="radio-group"
    @update:model-value="emit('update:modelValue', $event)"
    @value-change="handleValueChange"
  >
    <template v-if="legend">
      <div class="sr-only" data-slot="radio-group-legend">
        {{ legend }}
      </div>
    </template>
    <slot />
  </RadioGroupPrimitive.RadioGroupRoot>
</template>

// apps/react-demo/src/components/starwind-runtime/radio-group/RadioGroup.tsx
import RadioGroupPrimitive from "@starwind-ui/react/radio-group";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { radioGroup } from "./variants";

export type RadioGroupProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "defaultValue" | "onChange"
> &
  VariantProps<typeof radioGroup> & {
    defaultValue?: string;
    disabled?: boolean;
    form?: string;
    legend?: string;
    name?: string;
    onValueChange?: (
      value: string,
      details: import("@starwind-ui/react/radio-group").RadioGroupValueChangeDetails,
    ) => void;
    orientation?: "horizontal" | "vertical";
    readOnly?: boolean;
    ref?: React.Ref<HTMLDivElement>;
    required?: boolean;
    size?: "sm" | "md" | "lg";
    value?: import("@starwind-ui/react/radio-group").RadioGroupValue;
  };

function RadioGroup(props: RadioGroupProps) {
  const {
    defaultValue,
    disabled = false,
    form,
    legend,
    name,
    onValueChange,
    orientation = "vertical",
    readOnly = false,
    ref,
    required = false,
    size = "md",
    value,
    className,
    children,
    ...rest
  } = props;

  return (
    <RadioGroupPrimitive.Root
      className={radioGroup({ orientation, class: className })}
      defaultValue={defaultValue}
      disabled={disabled}
      form={form}
      name={name}
      onValueChange={onValueChange}
      orientation={orientation}
      readOnly={readOnly}
      ref={ref}
      required={required}
      value={value}
      aria-label={legend}
      {...rest}
      data-size={size}
      data-slot="radio-group"
    >
      {legend && (
        <div className="sr-only" data-slot="radio-group-legend">
          {legend}
        </div>
      )}

      {children}
    </RadioGroupPrimitive.Root>
  );
}

export default RadioGroup;
