// apps/react-demo/src/components/starwind-runtime/table/Table.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { table } from "./variants";

export type TableProps = React.ComponentPropsWithoutRef<"table"> &
  VariantProps<typeof table> & {
    ref?: React.Ref<HTMLTableElement>;
  };

function Table(props: TableProps) {
  const { ref, className, children, ...rest } = props;

  return (
    <div data-slot="table-container" className="relative w-full overflow-x-auto">
      <table className={table({ class: className })} {...rest} ref={ref} data-slot="table">
        {children}
      </table>
    </div>
  );
}

export default Table;

// apps/svelte-demo/src/lib/starwind-runtime/table/Table.svelte
<script module lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { table } from "./variants.js";

  export type TableProps = SvelteHTMLElements["table"] & VariantProps<typeof table> & { ref?: HTMLTableElement;  };
</script>

<script lang="ts">
  let {
    "class": className,
    ref = $bindable(),
    "children": children,
    ...rest
  }: TableProps = $props();
</script>

<div
  data-slot={"table-container"}
  class={"relative w-full overflow-x-auto"}
>
  <table
    class={table({ "class": cx(className) })}
    {...rest}
    data-slot={"table"}
    bind:this={ref}
  >
    {@render children?.()}
  </table>
</div>
