// apps/react-demo/src/components/starwind-runtime/video/Video.tsx
import type * as React from "react";
import { video } from "./variants";

export type VideoProps = React.ComponentPropsWithoutRef<"video"> &
  React.ComponentPropsWithoutRef<"iframe"> & {
    src: string;
    title?: string;
    autoPlay?: boolean;
    muted?: boolean;
    loop?: boolean;
    controls?: boolean;
    poster?: string;
    ref?: React.Ref<HTMLVideoElement | HTMLIFrameElement>;
  };

function Video(props: VideoProps) {
  const {
    src,
    title = "Video",
    autoPlay: autoplay = false,
    muted = false,
    loop = false,
    controls = true,
    poster,
    srcDoc: srcdoc,
    ref,
    className,
    ...rest
  } = props;

  const videoType =
    src.includes("youtube.com/shorts/") || src.includes("youtu.be/shorts/")
      ? "youtube-shorts"
      : src.includes("youtube.com") ||
          src.includes("youtu.be") ||
          src.includes("youtube-nocookie.com")
        ? "youtube"
        : "native";
  const youtubeId =
    videoType !== "native"
      ? ([
          /youtube\.com\/shorts\/([^?&]+)/,
          /youtube\.com\/watch\?v=([^&]+)/,
          /youtube\.com\/embed\/([^?&]+)/,
          /youtu\.be\/([^?&]+)/,
          /youtube-nocookie\.com\/embed\/([^?&]+)/,
        ]
          .map((pattern) => src.match(pattern)?.[1])
          .find(Boolean) ?? null)
      : null;
  const isShort = videoType === "youtube-shorts";
  const embedUrl = youtubeId
    ? (() => {
        const params = new URLSearchParams();
        if (autoplay) params.set("autoplay", "1");
        if (muted) params.set("mute", "1");
        if (loop) {
          params.set("loop", "1");
          params.set("playlist", youtubeId);
        }
        if (!controls) params.set("controls", "0");

        const baseUrl = "https://www.youtube-nocookie.com/embed/" + youtubeId;
        const queryString = params.toString();
        return queryString ? baseUrl + "?" + queryString : baseUrl;
      })()
    : null;
  const iframeSrc = srcdoc ? undefined : (embedUrl ?? undefined);

  if (videoType === "native" || !embedUrl) {
    return (
      <video
        data-sw-video
        className={video({ class: className })}
        src={src}
        autoPlay={autoplay}
        muted={muted}
        loop={loop}
        controls={controls}
        poster={poster}
        {...rest}
        ref={ref as React.Ref<HTMLVideoElement>}
        data-slot="video"
      >
        <track kind="captions" />
      </video>
    );
  }

  return (
    <iframe
      data-sw-video
      className={video({ class: className })}
      src={iframeSrc}
      srcDoc={srcdoc}
      title={title}
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      referrerPolicy="strict-origin-when-cross-origin"
      allowFullScreen
      data-video-type={isShort ? "youtube-shorts" : "youtube"}
      {...rest}
      ref={ref as React.Ref<HTMLIFrameElement>}
      data-slot="video"
    />
  );
}

export default Video;

// apps/svelte-demo/src/lib/starwind-runtime/video/Video.svelte
<script module lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import { cx } from "tailwind-variants";
  import { video } from "./variants.js";

  export type VideoProps = SvelteHTMLElements["video"] & SvelteHTMLElements["iframe"] & { src: string; title?: string; autoplay?: boolean; muted?: boolean; loop?: boolean; controls?: boolean; poster?: string; srcdoc?: string; ref?: HTMLVideoElement | HTMLIFrameElement; };
</script>

<script lang="ts">
  let {
    "src": src,
    "title": title = "Video",
    "autoplay": autoplay = false,
    "muted": muted = false,
    "loop": loop = false,
    "controls": controls = true,
    "poster": poster,
    "srcdoc": srcdoc,
    "class": className,
    ref = $bindable(),
    "children": children,
    ...rest
  }: VideoProps = $props();

  let videoType = $derived(src.includes("youtube.com/shorts/") || src.includes("youtu.be/shorts/")
    ? "youtube-shorts"
    : src.includes("youtube.com") ||
        src.includes("youtu.be") ||
        src.includes("youtube-nocookie.com")
      ? "youtube"
      : "native");

  let youtubeId = $derived(videoType !== "native"
    ? ([
        /youtube\.com\/shorts\/([^?&]+)/,
        /youtube\.com\/watch\?v=([^&]+)/,
        /youtube\.com\/embed\/([^?&]+)/,
        /youtu\.be\/([^?&]+)/,
        /youtube-nocookie\.com\/embed\/([^?&]+)/,
      ]
        .map((pattern) => src.match(pattern)?.[1])
        .find(Boolean) ?? null)
    : null);

  let isShort = $derived(videoType === "youtube-shorts");

  let embedUrl = $derived(youtubeId
    ? (() => {
        const params = new URLSearchParams();
        if (autoplay) params.set("autoplay", "1");
        if (muted) params.set("mute", "1");
        if (loop) {
          params.set("loop", "1");
          params.set("playlist", youtubeId);
        }
        if (!controls) params.set("controls", "0");

        const baseUrl = "https://www.youtube-nocookie.com/embed/" + youtubeId;
        const queryString = params.toString();
        return queryString ? baseUrl + "?" + queryString : baseUrl;
      })()
    : null);

  let iframeSrc = $derived(srcdoc ? undefined : (embedUrl ?? undefined));
</script>

{#if videoType === "native" || !embedUrl}
  <video
    data-sw-video
    class={video({ "class": cx(className) })}
    src={src}
    autoplay={autoplay}
    muted={muted}
    loop={loop}
    controls={controls}
    poster={poster}
    {...rest}
    data-slot={"video"}
    bind:this={ref}
  >
    <track
      kind={"captions"}
    />
  </video>
{:else}
  <iframe
    data-sw-video
    class={video({ "class": cx(className) })}
    src={iframeSrc}
    srcdoc={srcdoc}
    title={title}
    allow={"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"}
    referrerpolicy={"strict-origin-when-cross-origin"}
    allowfullscreen
    data-video-type={isShort ? "youtube-shorts" : "youtube"}
    {...rest}
    data-slot={"video"}
    bind:this={ref}
  >

  </iframe>
{/if}
