// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerTrigger.tsx
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { PopoverTrigger } from "../popover";
import { colorPickerTrigger, colorPickerValueSwatch } from "./variants";

export type ColorPickerTriggerProps = React.ComponentProps<typeof PopoverTrigger> &
  VariantProps<typeof colorPickerTrigger> & {
    showValueText?: boolean;
  };

function ColorPickerTrigger(props: ColorPickerTriggerProps) {
  const { className, size = "md", showValueText = true, children, ...rest } = props;

  return (
    <PopoverTrigger
      className={colorPickerTrigger({ size, class: className })}
      {...rest}
      data-slot="color-picker-trigger"
    >
      {children}

      <ColorPickerPrimitive.ValueSwatch
        className={colorPickerValueSwatch({ size })}
        data-slot="color-picker-value-swatch"
      >
        <ColorPickerPrimitive.TransparencyGrid
          className="pointer-events-none absolute inset-0 size-full"
          data-slot="color-picker-transparency-grid"
        />

        <span
          className="pointer-events-none absolute inset-0 size-full"
          data-slot="color-picker-value-swatch-color"
        />
      </ColorPickerPrimitive.ValueSwatch>

      {showValueText && <ColorPickerPrimitive.ValueText data-slot="color-picker-value-text" />}
    </PopoverTrigger>
  );
}

export default ColorPickerTrigger;

// apps/vue-demo/src/components/starwind-runtime/color-picker/ColorPickerTrigger.vue
<script setup lang="ts">
import * as ColorPickerPrimitive from "@starwind-ui/vue/color-picker";
import type { ClassValue } from "tailwind-variants";
import { useAttrs } from "vue";
import { PopoverTrigger } from "../popover";
import { colorPickerTrigger, colorPickerValueSwatch } from "./variants";

defineOptions({ inheritAttrs: false });

export type ColorPickerTriggerProps = InstanceType<typeof PopoverTrigger>["$props"] & {
  showValueText?: boolean;
  class?: ClassValue;
};
type ColorPickerTriggerDeclaredProps = {
  showValueText?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ ColorPickerTriggerProps;
const { class: className, showValueText = true } = defineProps<ColorPickerTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
</script>

<template>
  <PopoverTrigger
    :class="colorPickerTrigger({ class: className })"
    v-bind="attrs as Omit<InstanceType<typeof PopoverTrigger>['$props'], 'class' | 'style'>"
    data-slot="color-picker-trigger"
  >
    <slot />
    <ColorPickerPrimitive.ColorPickerValueSwatch
      :class="colorPickerValueSwatch()"
      data-slot="color-picker-value-swatch"
    >
      <ColorPickerPrimitive.ColorPickerTransparencyGrid
        class="pointer-events-none absolute inset-0 size-full"
        data-slot="color-picker-transparency-grid"
      />
      <span
        class="pointer-events-none absolute inset-0 size-full"
        data-slot="color-picker-value-swatch-color"
      />
    </ColorPickerPrimitive.ColorPickerValueSwatch>
    <template v-if="showValueText">
      <ColorPickerPrimitive.ColorPickerValueText data-slot="color-picker-value-text" />
    </template>
  </PopoverTrigger>
</template>
