// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerClear.tsx
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import type * as React from "react";
import { colorPickerAction } from "./variants";

export type ColorPickerClearProps = React.ComponentPropsWithoutRef<"button">;

function ColorPickerClear(props: ColorPickerClearProps) {
  const { className, children, ...rest } = props;

  return (
    <ColorPickerPrimitive.Clear
      className={colorPickerAction({ class: className })}
      {...rest}
      data-slot="color-picker-clear"
    >
      {children}
    </ColorPickerPrimitive.Clear>
  );
}

export default ColorPickerClear;

// apps/vue-demo/src/components/starwind-runtime/color-picker/ColorPickerClear.vue
<script setup lang="ts">
import * as ColorPickerPrimitive from "@starwind-ui/vue/color-picker";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes } from "vue";
import { colorPickerAction } from "./variants";

defineOptions({ inheritAttrs: false });

export type ColorPickerClearProps = Omit<ButtonHTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ColorPickerClearDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ColorPickerClearProps;
const { class: className } = defineProps<ColorPickerClearDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ColorPickerPrimitive.ColorPickerClear
    :class="colorPickerAction({ class: className })"
    v-bind="$attrs"
    data-slot="color-picker-clear"
  >
    <slot />
  </ColorPickerPrimitive.ColorPickerClear>
</template>
