// apps/react-demo/src/components/starwind-runtime/color-picker/ColorPickerInput.tsx
import type * as React from "react";
import "./styles.css";
import ColorPickerPrimitive from "@starwind-ui/react/color-picker";
import { IconChevronDown as ChevronDown } from "@tabler/icons-react";
import { NativeSelectOption } from "../native-select";
import { Select, SelectContent, SelectItem, SelectTrigger } from "../select";
import {
  colorPickerFormatSelectTrigger,
  colorPickerInput,
  colorPickerNativeFormatSelect,
  colorPickerNativeFormatSelectIcon,
  colorPickerNativeFormatSelectWrapper,
  colorPickerValueInput,
  colorPickerValueInputLayout,
} from "./variants";

export type ColorPickerInputProps = React.ComponentPropsWithoutRef<"div"> & {
  formatControl?: "select" | "native" | "none";
  formats?: readonly import("@starwind-ui/react/color-picker").ColorPickerFormat[];
  formatContentSize?: "sm" | "md" | "lg";
};

function ColorPickerInput(props: ColorPickerInputProps) {
  const {
    formatControl = "select",
    formats = ["hex", "rgb", "hsl", "hsb"],
    formatContentSize = "md",
    className,
    ...rest
  } = props;

  const normalizedFormats = Array.from(new Set(formats));

  return (
    <div
      className={colorPickerInput({ class: className })}
      {...rest}
      data-slot="color-picker-input"
    >
      <ColorPickerPrimitive.ValueInput
        className={[colorPickerValueInput(), colorPickerValueInputLayout()]
          .filter(Boolean)
          .join(" ")}
        data-slot="color-picker-value-input"
      />

      {formatControl === "native" && (
        <div
          className={colorPickerNativeFormatSelectWrapper()}
          data-slot="color-picker-native-format-select-wrapper"
        >
          <ColorPickerPrimitive.FormatSelect
            className={colorPickerNativeFormatSelect()}
            aria-label="Color format"
            data-slot="color-picker-native-format-select"
          >
            {normalizedFormats.map((formatOption, formatIndex) => (
              <NativeSelectOption value={formatOption} key={`${formatOption}-${formatIndex}`}>
                {formatOption.toUpperCase()}
              </NativeSelectOption>
            ))}
          </ColorPickerPrimitive.FormatSelect>

          <ChevronDown
            className={colorPickerNativeFormatSelectIcon()}
            aria-hidden="true"
            data-slot="color-picker-native-format-select-icon"
          />
        </div>
      )}

      {formatControl === "select" && (
        <ColorPickerPrimitive.FormatControl
          className="shrink-0"
          data-slot="color-picker-format-control"
        >
          <Select>
            <SelectTrigger aria-label="Color format" className={colorPickerFormatSelectTrigger()} />

            <SelectContent size={formatContentSize} data-sw-color-picker-format-options="">
              {normalizedFormats.map((formatOption, formatIndex) => (
                <SelectItem value={formatOption} key={`${formatOption}-${formatIndex}`}>
                  {formatOption.toUpperCase()}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </ColorPickerPrimitive.FormatControl>
      )}
    </div>
  );
}

export default ColorPickerInput;

// apps/vue-demo/src/components/starwind-runtime/color-picker/ColorPickerInput.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { computed, type HTMLAttributes, useAttrs } from "vue";
import "./styles.css";
import * as ColorPickerPrimitive from "@starwind-ui/vue/color-picker";
import { NativeSelectOption } from "../native-select";
import { Select, SelectContent, SelectItem, SelectTrigger } from "../select";
import {
  colorPickerFormatSelectTrigger,
  colorPickerInput,
  colorPickerNativeFormatSelect,
  colorPickerNativeFormatSelectIcon,
  colorPickerNativeFormatSelectWrapper,
  colorPickerValueInput,
  colorPickerValueInputLayout,
} from "./variants";

defineOptions({ inheritAttrs: false });

export type ColorPickerInputProps = Omit<
  HTMLAttributes,
  "class" | "formatContentSize" | "formatControl" | "formats"
> & {
  formatControl?: "select" | "native" | "none";
  formats?: readonly import("@starwind-ui/runtime/color-picker").ColorPickerFormat[];
  formatContentSize?: "sm" | "md" | "lg";
  class?: ClassValue;
};
type ColorPickerInputDeclaredProps = {
  formatControl?: "select" | "native" | "none";
  formats?: readonly import("@starwind-ui/runtime/color-picker").ColorPickerFormat[];
  formatContentSize?: "sm" | "md" | "lg";
  class?: ClassValue;
} & /* @vue-ignore */ ColorPickerInputProps;
const {
  formatControl = "select",
  formats = ["hex", "rgb", "hsl", "hsb"],
  formatContentSize = "md",
  class: className,
} = defineProps<ColorPickerInputDeclaredProps>();
defineSlots<{}>();
const attrs = useAttrs();
const normalizedFormats = computed(() => Array.from(new Set(formats)));
</script>

<template>
  <div
    :class="colorPickerInput({ class: className })"
    v-bind="attrs"
    data-slot="color-picker-input"
  >
    <ColorPickerPrimitive.ColorPickerValueInput
      :class="[colorPickerValueInput(), colorPickerValueInputLayout()].filter(Boolean).join(' ')"
      data-slot="color-picker-value-input"
    />
    <template v-if="formatControl === 'native'">
      <div
        :class="colorPickerNativeFormatSelectWrapper()"
        data-slot="color-picker-native-format-select-wrapper"
      >
        <ColorPickerPrimitive.ColorPickerFormatSelect
          :class="colorPickerNativeFormatSelect()"
          v-bind="{ 'aria-label': 'Color format' } as Record<string, unknown>"
          data-slot="color-picker-native-format-select"
        >
          <template v-for="(formatOption, formatIndex) in normalizedFormats">
            <NativeSelectOption :value="formatOption">
              {{ formatOption.toUpperCase() }}
            </NativeSelectOption>
          </template>
        </ColorPickerPrimitive.ColorPickerFormatSelect>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
          :class="colorPickerNativeFormatSelectIcon()"
          data-slot="color-picker-native-format-select-icon"
        >
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M6 9l6 6l6 -6" />
        </svg>
      </div>
    </template>
    <template v-if="formatControl === 'select'">
      <ColorPickerPrimitive.ColorPickerFormatControl
        class="shrink-0"
        data-slot="color-picker-format-control"
      >
        <Select>
          <SelectTrigger aria-label="Color format" :class="colorPickerFormatSelectTrigger()" />
          <SelectContent :size="formatContentSize" data-sw-color-picker-format-options="">
            <template v-for="(formatOption, formatIndex) in normalizedFormats">
              <SelectItem :value="formatOption">
                {{ formatOption.toUpperCase() }}
              </SelectItem>
            </template>
          </SelectContent>
        </Select>
      </ColorPickerPrimitive.ColorPickerFormatControl>
    </template>
  </div>
</template>
