// apps/vue-demo/src/components/starwind-runtime/alert-dialog/AlertDialogHeader.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { alertDialogHeader } from "./variants";

defineOptions({ inheritAttrs: false });

export type AlertDialogHeaderProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type AlertDialogHeaderDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ AlertDialogHeaderProps;
const { class: className } = defineProps<AlertDialogHeaderDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    :class="alertDialogHeader({ class: className })"
    v-bind="$attrs"
    data-slot="alert-dialog-header"
  >
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/alert-dialog/AlertDialogHeader.tsx
import type * as React from "react";
import { alertDialogHeader } from "./variants";

export type AlertDialogHeaderProps = React.ComponentPropsWithoutRef<"div">;

function AlertDialogHeader(props: AlertDialogHeaderProps) {
  const { className, children, ...rest } = props;

  return (
    <div
      className={alertDialogHeader({ class: className })}
      {...rest}
      data-slot="alert-dialog-header"
    >
      {children}
    </div>
  );
}

export default AlertDialogHeader;
