// apps/svelte-demo/src/lib/starwind-runtime/breadcrumb/BreadcrumbLink.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAnchorAttributes } from "svelte/elements";
  import { cx } from "tailwind-variants";
  import { breadcrumbLink } from "./variants.js";

  export type BreadcrumbLinkProps = Omit<HTMLAnchorAttributes, "children"> & { asChild?: boolean; children?: Snippet; ref?: HTMLAnchorElement; };
</script>

<script lang="ts">
  let {
    "asChild": asChild = false,
    "class": className,
    ref = $bindable(),
    "children": children,
    ...rest
  }: BreadcrumbLinkProps = $props();
</script>

{#if asChild}
  {@render children?.()}
{:else}
  <a
    data-sw-breadcrumb-link
    class={breadcrumbLink({ "class": cx(className) })}
    {...rest}
    data-slot={"breadcrumb-link"}
    bind:this={ref}
  >
    {@render children?.()}
  </a>
{/if}

// apps/react-demo/src/components/starwind-runtime/breadcrumb/BreadcrumbLink.tsx
import type * as React from "react";
import { breadcrumbLink } from "./variants";

export type BreadcrumbLinkProps = React.ComponentPropsWithoutRef<"a"> & {
  asChild?: boolean;
  ref?: React.Ref<HTMLAnchorElement>;
};

function BreadcrumbLink(props: BreadcrumbLinkProps) {
  const { asChild = false, ref, className, children, ...rest } = props;

  if (asChild) {
    return children;
  }

  return (
    <a
      data-sw-breadcrumb-link
      className={breadcrumbLink({ class: className })}
      {...rest}
      ref={ref}
      data-slot="breadcrumb-link"
    >
      {children}
    </a>
  );
}

export default BreadcrumbLink;
