// apps/react-demo/src/components/starwind-runtime/popover/PopoverTrigger.tsx
import PopoverPrimitive from "@starwind-ui/react/popover";
import type * as React from "react";
import { popoverTrigger } from "./variants";

export type PopoverTriggerProps = React.ComponentPropsWithoutRef<"button"> & {
  asChild?: boolean;
};

function PopoverTrigger(props: PopoverTriggerProps) {
  const { asChild = false, className, children, ...rest } = props;

  const triggerBaseClassName = popoverTrigger({ class: className });
  const triggerClassName = asChild ? className : triggerBaseClassName;

  return (
    <PopoverPrimitive.Trigger
      className={triggerClassName}
      asChild={asChild}
      {...rest}
      data-slot="popover-trigger"
    >
      {children}
    </PopoverPrimitive.Trigger>
  );
}

export default PopoverTrigger;

// apps/svelte-demo/src/lib/starwind-runtime/popover/PopoverTrigger.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { PopoverTrigger } from "@starwind-ui/svelte/popover";
  import { cx } from "tailwind-variants";
  import { popover, popoverContent, popoverDescription, popoverHeader, popoverTitle, popoverTrigger } from "./variants.js";

  export type PopoverTriggerProps = ComponentProps<typeof PopoverTrigger>;
</script>

<script lang="ts">
  let {
    "class": className,
    "child": child,
    "children": children,
    ...rest
  }: PopoverTriggerProps = $props();

  let triggerBaseClassName = $derived(popoverTrigger({ "class": cx(className) }));

  let triggerClassName = $derived(child ? className : triggerBaseClassName);
</script>

<PopoverTrigger
  class={triggerClassName}
  data-slot={"popover-trigger"}
  {...rest}
  child={child}
>
  {@render children?.()}
</PopoverTrigger>
