// apps/react-demo/src/components/starwind-runtime/popover/PopoverHeader.tsx
import type * as React from "react";
import { popoverHeader } from "./variants";

export type PopoverHeaderProps = React.ComponentPropsWithoutRef<"div">;

function PopoverHeader(props: PopoverHeaderProps) {
  const { className, children, ...rest } = props;

  return (
    <div className={popoverHeader({ class: className })} {...rest} data-slot="popover-header">
      {children}
    </div>
  );
}

export default PopoverHeader;

// apps/svelte-demo/src/lib/starwind-runtime/popover/PopoverHeader.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { untrack } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  import { cx } from "tailwind-variants";
  import { popover, popoverContent, popoverDescription, popoverHeader, popoverTitle, popoverTrigger } from "./variants.js";

  export type PopoverHeaderProps = HTMLAttributes<HTMLDivElement> & { ref?: (element: HTMLDivElement | null) => void; children?: Snippet };
</script>

<script lang="ts">
  let {
    "class": className,
    "ref": ref,
    "children": children,
    ...rest
  }: PopoverHeaderProps = $props();

  let nativeProps = $derived({ ...rest });
  const attachNative: Attachment<HTMLDivElement> = (element) => {
    $effect(() => { const callback = ref; untrack(() => callback?.(element)); return () => untrack(() => callback?.(null)); });
  };
</script>

<div
  class={popoverHeader({ "class": cx(className) })}
  {...nativeProps}
  data-slot={"popover-header"}
  {@attach attachNative}
>
  {@render children?.()}
</div>
