// apps/react-demo/src/components/starwind-runtime/separator/Separator.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { separator } from "./variants";

export type SeparatorProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "role" | "aria-orientation"
> &
  VariantProps<typeof separator> & {
    "data-slot"?: string;
    ref?: React.Ref<HTMLDivElement>;
  };

function Separator(props: SeparatorProps) {
  const {
    orientation = "horizontal",
    "data-slot": dataSlot = "separator",
    ref,
    className,
    ...rest
  } = props;

  return (
    <div
      data-sw-separator
      role="separator"
      aria-orientation={orientation}
      data-orientation={orientation}
      className={separator({ orientation, class: className })}
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    />
  );
}

export default Separator;

// apps/vue-demo/src/components/starwind-runtime/separator/Separator.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { separator } from "./variants";

defineOptions({ inheritAttrs: false });

export type SeparatorProps = Omit<
  HTMLAttributes,
  "aria-orientation" | "class" | "data-slot" | "role"
> &
  VariantProps<typeof separator> & {
    "data-slot"?: string;
    class?: ClassValue;
  };
type SeparatorDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
  orientation?: SeparatorProps["orientation"];
} & /* @vue-ignore */ Omit<SeparatorProps, "data-slot">;
const {
  orientation = "horizontal",
  dataSlot = "separator",
  class: className,
} = defineProps<SeparatorDeclaredProps>();
defineSlots<{}>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    data-sw-separator
    role="separator"
    :aria-orientation="orientation"
    :data-orientation="orientation"
    :class="separator({ orientation, class: className })"
    v-bind="$attrs"
    :data-slot="dataSlot"
  />
</template>
