// apps/react-demo/src/components/starwind-runtime/table/Table.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { table } from "./variants";

export type TableProps = React.ComponentPropsWithoutRef<"table"> &
  VariantProps<typeof table> & {
    ref?: React.Ref<HTMLTableElement>;
  };

function Table(props: TableProps) {
  const { ref, className, children, ...rest } = props;

  return (
    <div data-slot="table-container" className="relative w-full overflow-x-auto">
      <table className={table({ class: className })} {...rest} ref={ref} data-slot="table">
        {children}
      </table>
    </div>
  );
}

export default Table;

// apps/vue-demo/src/components/starwind-runtime/table/Table.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { table } from "./variants";

defineOptions({ inheritAttrs: false });

export type TableProps = Omit<HTMLAttributes, "class"> &
  VariantProps<typeof table> & {
    class?: ClassValue;
  };
type TableDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ TableProps;
const { class: className } = defineProps<TableDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLTableElement | null>(null);
defineExpose({ element });
</script>

<template>
  <div data-slot="table-container" class="relative w-full overflow-x-auto">
    <table ref="element" :class="table({ class: className })" v-bind="$attrs" data-slot="table">
      <slot />
    </table>
  </div>
</template>
