// apps/react-demo/src/components/starwind-runtime/alert-dialog/AlertDialogFooter.tsx
import type * as React from "react";
import { alertDialogFooter } from "./variants";

export type AlertDialogFooterProps = React.ComponentPropsWithoutRef<"div">;

function AlertDialogFooter(props: AlertDialogFooterProps) {
  const { className, children, ...rest } = props;

  return (
    <div
      className={alertDialogFooter({ class: className })}
      {...rest}
      data-slot="alert-dialog-footer"
    >
      {children}
    </div>
  );
}

export default AlertDialogFooter;

// apps/svelte-demo/src/lib/starwind-runtime/alert-dialog/AlertDialogFooter.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { untrack } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Attachment } from "svelte/attachments";
  import { cx } from "tailwind-variants";
  import { alertDialogBackdrop, alertDialogContent, alertDialogDescription, alertDialogFooter, alertDialogHeader, alertDialogTitle, alertDialogAction, alertDialogActionAsChild, alertDialogCancel, alertDialogCancelAsChild } from "./variants.js";

  export type AlertDialogFooterProps = HTMLAttributes<HTMLDivElement> & { ref?: (element: HTMLDivElement | null) => void; children?: Snippet };
</script>

<script lang="ts">
  let {
    "class": className,
    "ref": ref,
    "children": children,
    ...rest
  }: AlertDialogFooterProps = $props();

  let nativeProps = $derived({ ...rest });
  const attachNative: Attachment<HTMLDivElement> = (element) => {
    $effect(() => { const callback = ref; untrack(() => callback?.(element)); return () => untrack(() => callback?.(null)); });
  };
</script>

<div
  class={alertDialogFooter({ "class": cx(className) })}
  {...nativeProps}
  data-slot={"alert-dialog-footer"}
  {@attach attachNative}
>
  {@render children?.()}
</div>
