// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxItemIndicator.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxItemIndicator } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxItemIndicatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ComboboxItemIndicatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ComboboxItemIndicatorProps;
const { class: className } = defineProps<ComboboxItemIndicatorDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxItemIndicator
    :class="comboboxItemIndicator({ class: className })"
    v-bind="$attrs"
    data-slot="combobox-item-indicator"
  >
    <slot />
  </ComboboxPrimitive.ComboboxItemIndicator>
</template>

// apps/react-demo/src/components/starwind-runtime/combobox/ComboboxItemIndicator.tsx
import ComboboxPrimitive from "@starwind-ui/react/combobox";
import type * as React from "react";
import { comboboxItemIndicator } from "./variants";

export type ComboboxItemIndicatorProps = React.ComponentPropsWithoutRef<"span">;

function ComboboxItemIndicator(props: ComboboxItemIndicatorProps) {
  const { className, children, ...rest } = props;

  return (
    <ComboboxPrimitive.ItemIndicator
      className={comboboxItemIndicator({ class: className })}
      {...rest}
      data-slot="combobox-item-indicator"
    >
      {children}
    </ComboboxPrimitive.ItemIndicator>
  );
}

export default ComboboxItemIndicator;
