// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxEmpty.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxEmpty } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxEmptyProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ComboboxEmptyDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ComboboxEmptyProps;
const { class: className } = defineProps<ComboboxEmptyDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxEmpty
    :class="comboboxEmpty({ class: className })"
    v-bind="$attrs"
    data-slot="combobox-empty"
  >
    <slot />
  </ComboboxPrimitive.ComboboxEmpty>
</template>

// apps/react-demo/src/components/starwind-runtime/combobox/ComboboxEmpty.tsx
import ComboboxPrimitive from "@starwind-ui/react/combobox";
import type * as React from "react";
import { comboboxEmpty } from "./variants";

export type ComboboxEmptyProps = React.ComponentPropsWithoutRef<"div">;

function ComboboxEmpty(props: ComboboxEmptyProps) {
  const { className, children, ...rest } = props;

  return (
    <ComboboxPrimitive.Empty
      className={comboboxEmpty({ class: className })}
      {...rest}
      data-slot="combobox-empty"
    >
      {children}
    </ComboboxPrimitive.Empty>
  );
}

export default ComboboxEmpty;
