// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxValue.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxValue } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxValueProps = Omit<HTMLAttributes, "class" | "placeholder"> & {
  placeholder?: string;
  class?: ClassValue;
};
type ComboboxValueDeclaredProps = {
  placeholder?: string;
  class?: ClassValue;
} & /* @vue-ignore */ ComboboxValueProps;
const { class: className, placeholder } = defineProps<ComboboxValueDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxValue
    :class="comboboxValue({ class: className })"
    :placeholder="placeholder"
    v-bind="$attrs"
    data-slot="combobox-value"
  >
    <slot />
  </ComboboxPrimitive.ComboboxValue>
</template>

// apps/react-demo/src/components/starwind-runtime/combobox/ComboboxValue.tsx
import ComboboxPrimitive from "@starwind-ui/react/combobox";
import type * as React from "react";
import { comboboxValue } from "./variants";

export type ComboboxValueProps = React.ComponentPropsWithoutRef<"span"> & {
  placeholder?: string;
};

function ComboboxValue(props: ComboboxValueProps) {
  const { className, placeholder, children, ...rest } = props;

  return (
    <ComboboxPrimitive.Value
      className={comboboxValue({ class: className })}
      placeholder={placeholder}
      {...rest}
      data-slot="combobox-value"
    >
      {children}
    </ComboboxPrimitive.Value>
  );
}

export default ComboboxValue;
