// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxGroupLabel.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxGroupLabel } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxGroupLabelProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ComboboxGroupLabelDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ComboboxGroupLabelProps;
const { class: className } = defineProps<ComboboxGroupLabelDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxGroupLabel
    :class="comboboxGroupLabel({ class: className })"
    v-bind="$attrs"
    data-slot="combobox-group-label"
  >
    <slot />
  </ComboboxPrimitive.ComboboxGroupLabel>
</template>

// apps/react-demo/src/components/starwind-runtime/combobox/ComboboxGroupLabel.tsx
import ComboboxPrimitive from "@starwind-ui/react/combobox";
import type * as React from "react";
import { comboboxGroupLabel } from "./variants";

export type ComboboxGroupLabelProps = React.ComponentPropsWithoutRef<"div">;

function ComboboxGroupLabel(props: ComboboxGroupLabelProps) {
  const { className, children, ...rest } = props;

  return (
    <ComboboxPrimitive.GroupLabel
      className={comboboxGroupLabel({ class: className })}
      {...rest}
      data-slot="combobox-group-label"
    >
      {children}
    </ComboboxPrimitive.GroupLabel>
  );
}

export default ComboboxGroupLabel;
