// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxSeparator.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxSeparator } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxSeparatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ComboboxSeparatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ComboboxSeparatorProps;
const { class: className } = defineProps<ComboboxSeparatorDeclaredProps>();
defineSlots<{}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxSeparator
    :class="comboboxSeparator({ class: className })"
    v-bind="$attrs"
    data-slot="combobox-separator"
  />
</template>

// apps/react-demo/src/components/starwind-runtime/combobox/ComboboxSeparator.tsx
import ComboboxPrimitive from "@starwind-ui/react/combobox";
import type * as React from "react";
import { comboboxSeparator } from "./variants";

export type ComboboxSeparatorProps = React.ComponentPropsWithoutRef<"div">;

function ComboboxSeparator(props: ComboboxSeparatorProps) {
  const { className, ...rest } = props;

  return (
    <ComboboxPrimitive.Separator
      className={comboboxSeparator({ class: className })}
      {...rest}
      data-slot="combobox-separator"
    />
  );
}

export default ComboboxSeparator;
