// apps/react-demo/src/components/starwind-runtime/toggle-group/ToggleGroupItem.tsx
import TogglePrimitive from "@starwind-ui/react/toggle";
import type * as React from "react";
import { toggleGroupItem } from "./variants";

export type ToggleGroupItemProps = Omit<
  React.ComponentPropsWithoutRef<"button">,
  "aria-pressed" | "defaultPressed" | "disabled" | "onChange" | "type" | "value"
> & {
  defaultPressed?: boolean;
  disabled?: boolean;
  nativeButton?: boolean;
  onPressedChange?: (
    pressed: boolean,
    details: import("@starwind-ui/react/toggle").TogglePressedChangeDetails,
  ) => void;
  pressed?: boolean;
  ref?: React.Ref<HTMLButtonElement | HTMLSpanElement>;
  value?: string;
  variant?: "default" | "outline";
};

function ToggleGroupItem(props: ToggleGroupItemProps) {
  const {
    variant,
    defaultPressed,
    disabled = false,
    nativeButton,
    onPressedChange,
    pressed,
    ref,
    value,
    className,
    children,
    ...rest
  } = props;

  return (
    <TogglePrimitive.Root
      className={toggleGroupItem({ variant, class: className })}
      data-variant={variant}
      defaultPressed={defaultPressed}
      disabled={disabled}
      nativeButton={nativeButton}
      onPressedChange={onPressedChange}
      pressed={pressed}
      ref={ref}
      value={value}
      {...rest}
      data-slot="toggle-group-item"
    >
      {children}
    </TogglePrimitive.Root>
  );
}

export default ToggleGroupItem;

// apps/svelte-demo/src/lib/starwind-runtime/toggle-group/ToggleGroupItem.svelte
<script module lang="ts">
  import type { ComponentProps } from "svelte";
  import { untrack } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { ToggleRoot } from "@starwind-ui/svelte/toggle";
  import { toggleGroup, toggleGroupItem } from "./variants.js";

  type PrimitiveProps=ComponentProps<typeof ToggleRoot>;
  type StyledProps<T>=T extends unknown?Omit<T,"syncGroup"> & {variant?:"default"|"outline"}:never;
  export type ToggleGroupItemProps=StyledProps<PrimitiveProps>;
</script>

<script lang="ts">
  let {
    "variant": variant,
    "defaultPressed": defaultPressed,
    "disabled": disabled = false,
    "nativeButton": nativeButton,
    "value": value,
    "class": className,
    pressed = $bindable(),
    "pressed": commandValue,
    "ref": ref,
    "onPressedChange": onPressedChange,
    "children": children,
    ...rest
  }: ToggleGroupItemProps = $props();

  let observedCommand=untrack(()=>commandValue);
  $effect(()=>{const next=commandValue;untrack(()=>{if(Object.is(next,observedCommand))return;observedCommand=next;if(!Object.is(next,pressed))pressed=next;});});
</script>

<ToggleRoot
  class={toggleGroupItem({ "variant": variant, "class": cx(className) })}
  data-variant={variant}
  {...({ ...rest, nativeButton, ref, value, defaultPressed, disabled, onPressedChange } as PrimitiveProps)}
  data-slot={"toggle-group-item"}
  bind:pressed={pressed}
>
  {@render children?.()}
</ToggleRoot>
