// apps/svelte-demo/src/lib/starwind-runtime/context-menu/ContextMenuRadioItem.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { ContextMenuRadioItem } from "@starwind-ui/svelte/context-menu";
  import { cx } from "tailwind-variants";
  import { contextMenu, contextMenuCheckboxItem, contextMenuCheckboxItemIndicator, contextMenuContent, contextMenuItem, contextMenuLabel, contextMenuRadioGroup, contextMenuRadioItem, contextMenuRadioItemIndicator, contextMenuSeparator, contextMenuShortcut, contextMenuTrigger } from "./variants.js";
  import { ContextMenuRadioItemIndicator } from "@starwind-ui/svelte/context-menu";

  export type ContextMenuRadioItemProps = ComponentProps<typeof ContextMenuRadioItem> & { closeOnClick?: boolean; inset?: boolean; disabled?: boolean; indicatorClass?: string; showIndicator?: boolean; indicator?: Snippet; };
</script>

<script lang="ts">
  let {
    "class": className,
    "value": value,
    "checked": checked,
    "defaultChecked": defaultChecked = false,
    "closeOnClick": closeOnClick = false,
    "inset": inset = false,
    "disabled": disabled = false,
    "indicatorClass": indicatorClassName,
    "showIndicator": showIndicator = true,
    "children": children,
    "indicator": indicator,
    ...rest
  }: ContextMenuRadioItemProps = $props();
</script>

<ContextMenuRadioItem
  class={contextMenuRadioItem({ "inset": inset, "disabled": disabled, "class": cx(className) })}
  value={value}
  checked={checked}
  defaultChecked={defaultChecked}
  closeOnClick={closeOnClick}
  disabled={disabled}
  {...rest}
  data-slot={"context-menu-radio-item"}
>
  {#if showIndicator}
    <ContextMenuRadioItemIndicator
      class={contextMenuRadioItemIndicator({ "class": cx(indicatorClassName) })}
      data-slot={"context-menu-radio-item-indicator"}
    >
      {#if indicator}{@render indicator()}{:else}<span
        class={"size-2 rounded-full bg-current"}
      >

      </span>{/if}
    </ContextMenuRadioItemIndicator>
  {/if}
  {@render children?.()}
</ContextMenuRadioItem>

// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuRadioItem.tsx
import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import type * as React from "react";
import { contextMenuRadioItem, contextMenuRadioItemIndicator } from "./variants";

export type ContextMenuRadioItemProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "aria-checked" | "role"
> & {
  value: string;
  checked?: boolean;
  defaultChecked?: boolean;
  closeOnClick?: boolean;
  inset?: boolean;
  disabled?: boolean;
  indicatorClass?: string;
  showIndicator?: boolean;
  indicator?: React.ReactNode;
};

function ContextMenuRadioItem(props: ContextMenuRadioItemProps) {
  const {
    className,
    value,
    checked,
    defaultChecked = false,
    closeOnClick = false,
    inset = false,
    disabled = false,
    indicatorClass: indicatorClassName,
    showIndicator = true,
    children,
    indicator,
    ...rest
  } = props;

  return (
    <ContextMenuPrimitive.RadioItem
      className={contextMenuRadioItem({ inset, disabled, class: className })}
      value={value}
      checked={checked}
      defaultChecked={defaultChecked}
      closeOnClick={closeOnClick}
      disabled={disabled}
      {...rest}
      data-slot="context-menu-radio-item"
    >
      {showIndicator && (
        <ContextMenuPrimitive.RadioItemIndicator
          className={contextMenuRadioItemIndicator({ class: indicatorClassName })}
          data-slot="context-menu-radio-item-indicator"
        >
          {indicator ?? <span className="size-2 rounded-full bg-current" />}
        </ContextMenuPrimitive.RadioItemIndicator>
      )}

      {children}
    </ContextMenuPrimitive.RadioItem>
  );
}

export default ContextMenuRadioItem;
