// apps/vue-demo/src/components/starwind-runtime/context-menu/ContextMenuSeparator.vue
<script setup lang="ts">
import * as ContextMenuPrimitive from "@starwind-ui/vue/context-menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { contextMenuSeparator } from "./variants";

defineOptions({ inheritAttrs: false });

export type ContextMenuSeparatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ContextMenuSeparatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ContextMenuSeparatorProps;
const { class: className } = defineProps<ContextMenuSeparatorDeclaredProps>();
defineSlots<{}>();
</script>

<template>
  <ContextMenuPrimitive.ContextMenuSeparator
    :class="contextMenuSeparator({ class: className })"
    v-bind="$attrs"
    data-slot="context-menu-separator"
  />
</template>

// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuSeparator.tsx
import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import type * as React from "react";
import { contextMenuSeparator } from "./variants";

export type ContextMenuSeparatorProps = React.ComponentPropsWithoutRef<"div">;

function ContextMenuSeparator(props: ContextMenuSeparatorProps) {
  const { className, ...rest } = props;

  return (
    <ContextMenuPrimitive.Separator
      className={contextMenuSeparator({ class: className })}
      {...rest}
      data-slot="context-menu-separator"
    />
  );
}

export default ContextMenuSeparator;
