// apps/vue-demo/src/components/starwind-runtime/context-menu/ContextMenuShortcut.vue
<script setup lang="ts">
import * as ContextMenuPrimitive from "@starwind-ui/vue/context-menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { contextMenuShortcut } from "./variants";

defineOptions({ inheritAttrs: false });

export type ContextMenuShortcutProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type ContextMenuShortcutDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ ContextMenuShortcutProps;
const { class: className } = defineProps<ContextMenuShortcutDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ContextMenuPrimitive.ContextMenuShortcut
    :class="contextMenuShortcut({ class: className })"
    v-bind="$attrs"
    data-slot="context-menu-shortcut"
  >
    <slot />
  </ContextMenuPrimitive.ContextMenuShortcut>
</template>

// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuShortcut.tsx
import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import type * as React from "react";
import { contextMenuShortcut } from "./variants";

export type ContextMenuShortcutProps = React.ComponentPropsWithoutRef<"span">;

function ContextMenuShortcut(props: ContextMenuShortcutProps) {
  const { className, children, ...rest } = props;

  return (
    <ContextMenuPrimitive.Shortcut
      className={contextMenuShortcut({ class: className })}
      {...rest}
      data-slot="context-menu-shortcut"
    >
      {children}
    </ContextMenuPrimitive.Shortcut>
  );
}

export default ContextMenuShortcut;
