// apps/vue-demo/src/components/starwind-runtime/context-menu/ContextMenuSubTrigger.vue
<script setup lang="ts">
import * as ContextMenuPrimitive from "@starwind-ui/vue/context-menu";
import type { ClassValue } from "tailwind-variants";
import { computed, type HTMLAttributes } from "vue";
import { contextMenuItem } from "./variants";

defineOptions({ inheritAttrs: false });

export type ContextMenuSubTriggerProps = Omit<HTMLAttributes, "class" | "disabled" | "inset"> & {
  inset?: boolean;
  disabled?: boolean;
  class?: ClassValue;
};
type ContextMenuSubTriggerDeclaredProps = {
  inset?: boolean;
  disabled?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ ContextMenuSubTriggerProps;
const {
  class: className,
  inset = false,
  disabled = false,
} = defineProps<ContextMenuSubTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const subTriggerClassName = computed(() => className);
</script>

<template>
  <ContextMenuPrimitive.ContextMenuSubmenuTrigger
    :class="contextMenuItem({ inset, disabled, class: subTriggerClassName })"
    :disabled="disabled"
    v-bind="$attrs"
    data-slot="context-menu-sub-trigger"
  >
    <slot />
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      class="ml-auto size-4"
    >
      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
      <path d="M9 6l6 6l-6 6" />
    </svg>
  </ContextMenuPrimitive.ContextMenuSubmenuTrigger>
</template>

// apps/react-demo/src/components/starwind-runtime/context-menu/ContextMenuSubTrigger.tsx
import ContextMenuPrimitive from "@starwind-ui/react/context-menu";
import { IconChevronRight as ChevronRight } from "@tabler/icons-react";
import type * as React from "react";
import { contextMenuItem } from "./variants";

export type ContextMenuSubTriggerProps = React.ComponentPropsWithoutRef<"div"> & {
  inset?: boolean;
  disabled?: boolean;
};

function ContextMenuSubTrigger(props: ContextMenuSubTriggerProps) {
  const { className, inset = false, disabled = false, children, ...rest } = props;

  const subTriggerClassName = className;

  return (
    <ContextMenuPrimitive.SubmenuTrigger
      className={contextMenuItem({ inset, disabled, class: subTriggerClassName })}
      disabled={disabled}
      {...rest}
      data-slot="context-menu-sub-trigger"
    >
      {children}

      <ChevronRight className="ml-auto size-4" />
    </ContextMenuPrimitive.SubmenuTrigger>
  );
}

export default ContextMenuSubTrigger;
