// apps/svelte-demo/src/lib/starwind-runtime/sidebar/SidebarMenuButton.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { sidebar, sidebarContent, sidebarFooter, sidebarGap, sidebarContainer, sidebarGroup, sidebarGroupAction, sidebarGroupContent, sidebarGroupLabel, sidebarHeader, sidebarInner, sidebarInput, sidebarInset, sidebarMenu, sidebarMenuAction, sidebarMenuBadge, sidebarMenuButton, sidebarMenuItem, sidebarMenuSkeleton, sidebarMenuSub, sidebarMenuSubButton, sidebarMenuSubItem, sidebarMobileContent, sidebarProvider, sidebarRail, sidebarSeparator, sidebarTrigger } from "./variants.js";
  import { SidebarMenuButton } from "@starwind-ui/svelte/sidebar";
  import { Tooltip } from "../tooltip/index.js";
  import { TooltipContent } from "../tooltip/index.js";
  import "./styles.css";

  export type SidebarMenuButtonProps = ComponentProps<typeof SidebarMenuButton> & VariantProps<typeof sidebarMenuButton> & {children?:Snippet; "isActive"?:boolean; "tooltip"?:string;  };
</script>

<script lang="ts">
  let {
    "isActive": isActive = false,
    "tooltip": tooltip,
    "variant": variant,
    "size": size = "md",
    "href": href,
    "class": className,
    "children": children,
    ...rest
  }: SidebarMenuButtonProps = $props();

  let buttonClassName = $derived(sidebarMenuButton({ "variant": variant, "size": size, "class": cx(className) }));

  let menuProps = $derived(({ "class": buttonClassName, "data-sidebar": "menu-button", "data-size": size, "data-active": isActive, "data-tooltip": tooltip, "href": href, "data-slot": "sidebar-menu-button", ...rest, "data-sw-tooltip-trigger": tooltip ? "" : undefined }) as ComponentProps<typeof SidebarMenuButton>);
</script>

{#if Boolean(tooltip)}
  <Tooltip
    openDelay={0}
    closeDelay={0}
    class={"w-full"}
  >
    <SidebarMenuButton
      {...menuProps}
    >
      {@render children?.()}
    </SidebarMenuButton>
    <TooltipContent
      side={"right"}
      align={"center"}
      class={"whitespace-nowrap"}
      data-sw-sidebar-tooltip-content
    >
      {tooltip}
    </TooltipContent>
  </Tooltip>
{:else}
  <SidebarMenuButton
    {...menuProps}
  >
    {@render children?.()}
  </SidebarMenuButton>
{/if}

// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarMenuButton.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import "./styles.css";
import SidebarPrimitive from "@starwind-ui/react/sidebar";
import { Tooltip, TooltipContent, TooltipTrigger } from "../tooltip";
import { sidebarMenuButton } from "./variants";

export type SidebarMenuButtonProps = React.ComponentPropsWithoutRef<"button"> &
  Omit<React.ComponentPropsWithoutRef<"a">, "type"> &
  VariantProps<typeof sidebarMenuButton> & {
    asChild?: boolean;
    isActive?: boolean;
    tooltip?: string;
  };

function SidebarMenuButton(props: SidebarMenuButtonProps) {
  const {
    asChild = false,
    isActive = false,
    tooltip,
    variant,
    size = "md",
    href,
    className,
    children,
    ...rest
  } = props;

  const Tag = (asChild ? "div" : href ? "a" : "button") as React.ElementType;
  const buttonClassName = sidebarMenuButton({ variant, size, class: className });

  if (Boolean(tooltip)) {
    return (
      <Tooltip openDelay={0} closeDelay={0} className="w-full">
        <TooltipTrigger className="w-full">
          <SidebarPrimitive.MenuButton asChild={true}>
            <Tag
              className={buttonClassName}
              data-sidebar="menu-button"
              data-size={size}
              data-active={isActive}
              data-tooltip={tooltip}
              href={href}
              data-slot="sidebar-menu-button"
              type={Tag === "button" ? "button" : undefined}
              data-as-child={asChild ? true : undefined}
              {...rest}
            >
              {children}
            </Tag>
          </SidebarPrimitive.MenuButton>
        </TooltipTrigger>

        <TooltipContent
          side="right"
          align="center"
          className="whitespace-nowrap"
          data-sw-sidebar-tooltip-content
        >
          {tooltip}
        </TooltipContent>
      </Tooltip>
    );
  }

  return (
    <SidebarPrimitive.MenuButton asChild={true}>
      <Tag
        className={buttonClassName}
        data-sidebar="menu-button"
        data-size={size}
        data-active={isActive}
        data-tooltip={tooltip}
        href={href}
        data-slot="sidebar-menu-button"
        type={Tag === "button" ? "button" : undefined}
        data-as-child={asChild ? true : undefined}
        {...rest}
      >
        {children}
      </Tag>
    </SidebarPrimitive.MenuButton>
  );
}

export default SidebarMenuButton;
