// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarGroupContent.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarGroupContent } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarGroupContentProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarGroupContentDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarGroupContentProps, "data-slot">;
const { dataSlot = "sidebar-group-content", class: className } =
  defineProps<SidebarGroupContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    :class="sidebarGroupContent({ class: className })"
    data-sidebar="group-content"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarGroupContent.tsx
import type * as React from "react";
import { sidebarGroupContent } from "./variants";

export type SidebarGroupContentProps = React.ComponentPropsWithoutRef<"div"> & {
  ref?: React.Ref<HTMLDivElement>;
  "data-slot"?: string;
};

function SidebarGroupContent(props: SidebarGroupContentProps) {
  const {
    ref,
    "data-slot": dataSlot = "sidebar-group-content",
    className,
    children,
    ...rest
  } = props;

  return (
    <div
      className={sidebarGroupContent({ class: className })}
      data-sidebar="group-content"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </div>
  );
}

export default SidebarGroupContent;
