// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarMenuSkeleton.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { computed, type HTMLAttributes } from "vue";
import { Skeleton } from "../skeleton";
import { sidebarMenuSkeleton } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarMenuSkeletonProps = Omit<HTMLAttributes, "class" | "showIcon" | "width"> & {
  showIcon?: boolean;
  width?: string;
  class?: ClassValue;
};
type SidebarMenuSkeletonDeclaredProps = {
  showIcon?: boolean;
  width?: string;
  class?: ClassValue;
} & /* @vue-ignore */ SidebarMenuSkeletonProps;
const {
  showIcon = false,
  width,
  class: className,
} = defineProps<SidebarMenuSkeletonDeclaredProps>();
defineSlots<{}>();
const skeletonWidth = computed(() => width ?? "70%");
const skeletonStyle = computed(() => ({ "--skeleton-width": skeletonWidth.value }));
</script>

<template>
  <div
    :class="sidebarMenuSkeleton({ class: className })"
    data-sidebar="menu-skeleton"
    v-bind="$attrs"
    data-slot="sidebar-menu-skeleton"
  >
    <template v-if="showIcon">
      <Skeleton class="size-4 rounded-md" data-sidebar="menu-skeleton-icon" />
    </template>
    <Skeleton
      class="h-4 max-w-(--skeleton-width) flex-1"
      :style="skeletonStyle"
      data-sidebar="menu-skeleton-text"
    />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarMenuSkeleton.tsx
import type * as React from "react";
import { Skeleton } from "../skeleton";
import { sidebarMenuSkeleton } from "./variants";

export type SidebarMenuSkeletonProps = React.ComponentPropsWithoutRef<"div"> & {
  showIcon?: boolean;
  width?: string;
};

function SidebarMenuSkeleton(props: SidebarMenuSkeletonProps) {
  const { showIcon = false, width, className, ...rest } = props;

  const skeletonWidth = width ?? "70%";
  const skeletonStyle = { "--skeleton-width": skeletonWidth } as React.CSSProperties;

  return (
    <div
      className={sidebarMenuSkeleton({ class: className })}
      data-sidebar="menu-skeleton"
      {...rest}
      data-slot="sidebar-menu-skeleton"
    >
      {showIcon && <Skeleton className="size-4 rounded-md" data-sidebar="menu-skeleton-icon" />}

      <Skeleton
        className="h-4 max-w-(--skeleton-width) flex-1"
        style={skeletonStyle}
        data-sidebar="menu-skeleton-text"
      />
    </div>
  );
}

export default SidebarMenuSkeleton;
