// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarMenuSub.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarMenuSub } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarMenuSubProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarMenuSubDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarMenuSubProps, "data-slot">;
const { dataSlot = "sidebar-menu-sub", class: className } =
  defineProps<SidebarMenuSubDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ul
    :class="sidebarMenuSub({ class: className })"
    data-sidebar="menu-sub"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </ul>
</template>

// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarMenuSub.tsx
import type * as React from "react";
import { sidebarMenuSub } from "./variants";

export type SidebarMenuSubProps = React.ComponentPropsWithoutRef<"ul"> & {
  ref?: React.Ref<HTMLUListElement>;
  "data-slot"?: string;
};

function SidebarMenuSub(props: SidebarMenuSubProps) {
  const { ref, "data-slot": dataSlot = "sidebar-menu-sub", className, children, ...rest } = props;

  return (
    <ul
      className={sidebarMenuSub({ class: className })}
      data-sidebar="menu-sub"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </ul>
  );
}

export default SidebarMenuSub;
