// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarRail.vue
<script setup lang="ts">
import * as SidebarPrimitive from "@starwind-ui/vue/sidebar";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes, useAttrs } from "vue";
import { sidebarRail } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarRailProps = Omit<ButtonHTMLAttributes, "class"> & {
  class?: ClassValue;
};
type SidebarRailDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ SidebarRailProps;
const { class: className } = defineProps<SidebarRailDeclaredProps>();
defineSlots<{}>();
const attrs = useAttrs();
</script>

<template>
  <SidebarPrimitive.SidebarRail
    :class="sidebarRail({ class: className })"
    data-sidebar="rail"
    v-bind="{ ...attrs, 'aria-label': 'Toggle Sidebar' } as Record<string, unknown>"
    data-slot="sidebar-rail"
  />
</template>

// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarRail.tsx
import SidebarPrimitive from "@starwind-ui/react/sidebar";
import type * as React from "react";
import { sidebarRail } from "./variants";

export type SidebarRailProps = React.ComponentPropsWithoutRef<"button"> & {
  ref?: React.Ref<HTMLButtonElement>;
};

function SidebarRail(props: SidebarRailProps) {
  const { ref, className, ...rest } = props;

  return (
    <SidebarPrimitive.Rail
      className={sidebarRail({ class: className })}
      data-sidebar="rail"
      aria-label="Toggle Sidebar"
      tabIndex={-1}
      {...rest}
      ref={ref}
      data-slot="sidebar-rail"
    />
  );
}

export default SidebarRail;
