// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarMenu.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarMenu } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarMenuProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarMenuDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarMenuProps, "data-slot">;
const { dataSlot = "sidebar-menu", class: className } = defineProps<SidebarMenuDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <ul
    :class="sidebarMenu({ class: className })"
    data-sidebar="menu"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </ul>
</template>

// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarMenu.tsx
import type * as React from "react";
import { sidebarMenu } from "./variants";

export type SidebarMenuProps = React.ComponentPropsWithoutRef<"ul"> & {
  ref?: React.Ref<HTMLUListElement>;
  "data-slot"?: string;
};

function SidebarMenu(props: SidebarMenuProps) {
  const { ref, "data-slot": dataSlot = "sidebar-menu", className, children, ...rest } = props;

  return (
    <ul
      className={sidebarMenu({ class: className })}
      data-sidebar="menu"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </ul>
  );
}

export default SidebarMenu;
