// apps/vue-demo/src/components/starwind-runtime/select/SelectGroup.vue
<script setup lang="ts">
import * as SelectPrimitive from "@starwind-ui/vue/select";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { selectGroup } from "./variants";

defineOptions({ inheritAttrs: false });

export type SelectGroupProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type SelectGroupDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ SelectGroupProps;
const { class: className } = defineProps<SelectGroupDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <SelectPrimitive.SelectGroup
    :class="selectGroup({ class: className })"
    v-bind="$attrs"
    data-slot="select-group"
  >
    <slot />
  </SelectPrimitive.SelectGroup>
</template>

// apps/react-demo/src/components/starwind-runtime/select/SelectGroup.tsx
import SelectPrimitive from "@starwind-ui/react/select";
import type * as React from "react";
import { selectGroup } from "./variants";

export type SelectGroupProps = React.ComponentPropsWithoutRef<"div">;

function SelectGroup(props: SelectGroupProps) {
  const { className, children, ...rest } = props;

  return (
    <SelectPrimitive.Group
      className={selectGroup({ class: className })}
      {...rest}
      data-slot="select-group"
    >
      {children}
    </SelectPrimitive.Group>
  );
}

export default SelectGroup;
