// apps/vue-demo/src/components/starwind-runtime/select/SelectItemText.vue
<script setup lang="ts">
import * as SelectPrimitive from "@starwind-ui/vue/select";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { selectItemText } from "./variants";

defineOptions({ inheritAttrs: false });

export type SelectItemTextProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type SelectItemTextDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ SelectItemTextProps;
const { class: className } = defineProps<SelectItemTextDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <SelectPrimitive.SelectItemText
    :class="selectItemText({ class: className })"
    v-bind="$attrs"
    data-slot="select-item-text"
  >
    <slot />
  </SelectPrimitive.SelectItemText>
</template>

// apps/react-demo/src/components/starwind-runtime/select/SelectItemText.tsx
import SelectPrimitive from "@starwind-ui/react/select";
import type * as React from "react";
import { selectItemText } from "./variants";

export type SelectItemTextProps = React.ComponentPropsWithoutRef<"span">;

function SelectItemText(props: SelectItemTextProps) {
  const { className, children, ...rest } = props;

  return (
    <SelectPrimitive.ItemText
      className={selectItemText({ class: className })}
      {...rest}
      data-slot="select-item-text"
    >
      {children}
    </SelectPrimitive.ItemText>
  );
}

export default SelectItemText;
