// apps/vue-demo/src/components/starwind-runtime/popover/PopoverHeader.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { popoverHeader } from "./variants";

defineOptions({ inheritAttrs: false });

export type PopoverHeaderProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type PopoverHeaderDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ PopoverHeaderProps;
const { class: className } = defineProps<PopoverHeaderDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div :class="popoverHeader({ class: className })" v-bind="$attrs" data-slot="popover-header">
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/popover/PopoverHeader.tsx
import type * as React from "react";
import { popoverHeader } from "./variants";

export type PopoverHeaderProps = React.ComponentPropsWithoutRef<"div">;

function PopoverHeader(props: PopoverHeaderProps) {
  const { className, children, ...rest } = props;

  return (
    <div className={popoverHeader({ class: className })} {...rest} data-slot="popover-header">
      {children}
    </div>
  );
}

export default PopoverHeader;
