// apps/vue-demo/src/components/starwind-runtime/popover/PopoverTrigger.vue
<script setup lang="ts">
import * as PopoverPrimitive from "@starwind-ui/vue/popover";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes, computed } from "vue";
import { popoverTrigger } from "./variants";

defineOptions({ inheritAttrs: false });

export type PopoverTriggerProps = Omit<ButtonHTMLAttributes, "asChild" | "class"> & {
  asChild?: boolean;
  class?: ClassValue;
};
type PopoverTriggerDeclaredProps = {
  asChild?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ PopoverTriggerProps;
const { asChild = false, class: className } = defineProps<PopoverTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const triggerBaseClassName = computed(() => popoverTrigger({ class: className }));
const triggerClassName = computed(() => (asChild ? className : triggerBaseClassName.value));
</script>

<template>
  <PopoverPrimitive.PopoverTrigger
    :class="triggerClassName"
    :as-child="asChild"
    data-slot="popover-trigger"
    v-bind="$attrs"
  >
    <slot />
  </PopoverPrimitive.PopoverTrigger>
</template>

// apps/react-demo/src/components/starwind-runtime/popover/PopoverTrigger.tsx
import PopoverPrimitive from "@starwind-ui/react/popover";
import type * as React from "react";
import { popoverTrigger } from "./variants";

export type PopoverTriggerProps = React.ComponentPropsWithoutRef<"button"> & {
  asChild?: boolean;
};

function PopoverTrigger(props: PopoverTriggerProps) {
  const { asChild = false, className, children, ...rest } = props;

  const triggerBaseClassName = popoverTrigger({ class: className });
  const triggerClassName = asChild ? className : triggerBaseClassName;

  return (
    <PopoverPrimitive.Trigger
      className={triggerClassName}
      asChild={asChild}
      {...rest}
      data-slot="popover-trigger"
    >
      {children}
    </PopoverPrimitive.Trigger>
  );
}

export default PopoverTrigger;
