// apps/vue-demo/src/components/starwind-runtime/popover/Popover.vue
<script setup lang="ts">
import * as PopoverPrimitive from "@starwind-ui/vue/popover";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes, useAttrs } from "vue";
import { popover } from "./variants";

defineOptions({ inheritAttrs: false });

export type PopoverProps = Omit<
  HTMLAttributes,
  | "class"
  | "closeDelay"
  | "closeOnEscape"
  | "closeOnOutsideInteract"
  | "defaultOpen"
  | "modal"
  | "open"
  | "openOnHover"
> & {
  defaultOpen?: boolean;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  class?: ClassValue;
  open?: boolean;
};
type PopoverDeclaredProps = {
  defaultOpen?: boolean;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  class?: ClassValue;
  open?: boolean;
} & /* @vue-ignore */ PopoverProps;
const {
  defaultOpen = false,
  closeOnEscape = true,
  closeOnOutsideInteract = true,
  modal = false,
  openOnHover = false,
  closeDelay = 200,
  class: className,
  open = undefined,
} = defineProps<PopoverDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const emit = defineEmits<{
  closeComplete: [detail: import("@starwind-ui/vue/popover").PopoverCloseCompleteDetails];
  openChange: [open: boolean, detail: import("@starwind-ui/vue/popover").PopoverOpenChangeDetails];
  "update:open": [value: boolean];
}>();
function handleCloseComplete(
  detail: import("@starwind-ui/vue/popover").PopoverCloseCompleteDetails,
): void {
  emit("closeComplete", detail);
}

function handleOpenChange(
  open: boolean,
  detail: import("@starwind-ui/vue/popover").PopoverOpenChangeDetails,
): void {
  emit("openChange", open, detail);
}
</script>

<template>
  <PopoverPrimitive.PopoverRoot
    :class="popover({ class: className })"
    :default-open="defaultOpen"
    :close-on-escape="closeOnEscape"
    :close-on-outside-interact="closeOnOutsideInteract"
    :modal="modal"
    :open-on-hover="openOnHover"
    :close-delay="closeDelay"
    v-bind="attrs"
    data-slot="popover"
    :open="open"
    @update:open="emit('update:open', $event)"
    @close-complete="handleCloseComplete"
    @open-change="handleOpenChange"
  >
    <slot />
  </PopoverPrimitive.PopoverRoot>
</template>

// apps/react-demo/src/components/starwind-runtime/popover/Popover.tsx
import PopoverPrimitive from "@starwind-ui/react/popover";
import type * as React from "react";
import { popover } from "./variants";

export type PopoverProps = React.ComponentPropsWithoutRef<"div"> & {
  defaultOpen?: boolean;
  open?: boolean;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  modal?: boolean;
  openOnHover?: boolean;
  closeDelay?: number;
  onOpenChange?: (
    open: boolean,
    details: import("@starwind-ui/react/popover").PopoverOpenChangeDetails,
  ) => void;
  onCloseComplete?: (
    details: import("@starwind-ui/react/popover").PopoverCloseCompleteDetails,
  ) => void;
};

function Popover(props: PopoverProps) {
  const {
    defaultOpen = false,
    open,
    closeOnEscape = true,
    closeOnOutsideInteract = true,
    modal = false,
    openOnHover = false,
    closeDelay = 200,
    onOpenChange,
    onCloseComplete,
    className,
    children,
    ...rest
  } = props;

  return (
    <PopoverPrimitive.Root
      className={popover({ class: className })}
      defaultOpen={defaultOpen}
      open={open}
      closeOnEscape={closeOnEscape}
      closeOnOutsideInteract={closeOnOutsideInteract}
      modal={modal}
      openOnHover={openOnHover}
      closeDelay={closeDelay}
      onOpenChange={onOpenChange}
      onCloseComplete={onCloseComplete}
      {...rest}
      data-slot="popover"
    >
      {children}
    </PopoverPrimitive.Root>
  );
}

export default Popover;
