// apps/vue-demo/src/components/starwind-runtime/popover/PopoverContent.vue
<script setup lang="ts">
import * as PopoverPrimitive from "@starwind-ui/vue/popover";
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { popoverContent } from "./variants";

defineOptions({ inheritAttrs: false });

export type PopoverContentProps = Omit<
  HTMLAttributes,
  | "align"
  | "avoidCollisions"
  | "class"
  | "collisionStrategy"
  | "disablePortal"
  | "portalContainer"
  | "side"
  | "sideOffset"
> &
  VariantProps<typeof popoverContent> & {
    side?: "top" | "right" | "bottom" | "left";
    align?: "start" | "center" | "end";
    sideOffset?: number;
    avoidCollisions?: boolean;
    collisionStrategy?: "initial-placement" | "best-fit";
    portalContainer?: string;
    disablePortal?: boolean;
    class?: ClassValue;
  };
type PopoverContentDeclaredProps = {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  avoidCollisions?: boolean;
  collisionStrategy?: "initial-placement" | "best-fit";
  portalContainer?: string;
  disablePortal?: boolean;
  class?: ClassValue;
  exitMotion?: PopoverContentProps["exitMotion"];
} & /* @vue-ignore */ PopoverContentProps;
const {
  class: className,
  side = "bottom",
  align = "center",
  sideOffset = 4,
  avoidCollisions = true,
  collisionStrategy = "initial-placement",
  exitMotion = "popover",
  portalContainer,
  disablePortal = false,
} = defineProps<PopoverContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <PopoverPrimitive.PopoverPortal
    :container="portalContainer"
    :disabled="disablePortal"
    data-slot="popover-portal"
  >
    <PopoverPrimitive.PopoverPopup
      :class="popoverContent({ exitMotion, class: className })"
      :side="side"
      :align="align"
      :side-offset="sideOffset"
      :avoid-collisions="avoidCollisions"
      :collision-strategy="collisionStrategy"
      v-bind="$attrs"
      data-slot="popover-content"
    >
      <slot />
    </PopoverPrimitive.PopoverPopup>
  </PopoverPrimitive.PopoverPortal>
</template>

// apps/react-demo/src/components/starwind-runtime/popover/PopoverContent.tsx
"use client";

import PopoverPrimitive from "@starwind-ui/react/popover";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { popoverContent } from "./variants";

export type PopoverContentProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof popoverContent> & {
    side?: "top" | "right" | "bottom" | "left";
    align?: "start" | "center" | "end";
    sideOffset?: number;
    avoidCollisions?: boolean;
    collisionStrategy?: "initial-placement" | "best-fit";
    portalContainer?: string;
    disablePortal?: boolean;
  };

function PopoverContent(props: PopoverContentProps) {
  const {
    className,
    side = "bottom",
    align = "center",
    sideOffset = 4,
    avoidCollisions = true,
    collisionStrategy = "initial-placement",
    exitMotion = "popover",
    portalContainer,
    disablePortal = false,
    children,
    ...rest
  } = props;

  return (
    <PopoverPrimitive.Portal
      container={portalContainer}
      disabled={disablePortal}
      data-slot="popover-portal"
    >
      <PopoverPrimitive.Popup
        className={popoverContent({ exitMotion, class: className })}
        side={side}
        align={align}
        sideOffset={sideOffset}
        avoidCollisions={avoidCollisions}
        collisionStrategy={collisionStrategy}
        data-slot="popover-content"
        {...rest}
      >
        {children}
      </PopoverPrimitive.Popup>
    </PopoverPrimitive.Portal>
  );
}

export default PopoverContent;
