// apps/svelte-demo/src/lib/starwind-runtime/popover/PopoverContent.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { PopoverPopup } from "@starwind-ui/svelte/popover";
  import { cx } from "tailwind-variants";
  import type { VariantProps } from "tailwind-variants";
  import { popover, popoverContent, popoverDescription, popoverHeader, popoverTitle, popoverTrigger } from "./variants.js";
  import { PopoverPortal } from "@starwind-ui/svelte/popover";

  export type PopoverContentProps = ComponentProps<typeof PopoverPopup> & VariantProps<typeof popoverContent> & { portalContainer?: string; disablePortal?: boolean; };
</script>

<script lang="ts">
  let {
    "class": className,
    "side": side = "bottom",
    "align": align = "center",
    "sideOffset": sideOffset = 4,
    "avoidCollisions": avoidCollisions = true,
    "collisionStrategy": collisionStrategy = "initial-placement",
    "exitMotion": exitMotion = "popover",
    "portalContainer": portalContainer,
    "disablePortal": disablePortal = false,
    "children": children,
    ...rest
  }: PopoverContentProps = $props();
</script>

<PopoverPortal
  container={portalContainer}
  disabled={disablePortal}
  data-slot={"popover-portal"}
>
  <PopoverPopup
    class={popoverContent({ "exitMotion": exitMotion, "class": cx(className) })}
    side={side}
    align={align}
    sideOffset={sideOffset}
    avoidCollisions={avoidCollisions}
    collisionStrategy={collisionStrategy}
    data-slot={"popover-content"}
    {...rest}
  >
    {@render children?.()}
  </PopoverPopup>
</PopoverPortal>

// apps/react-demo/src/components/starwind-runtime/popover/PopoverContent.tsx
"use client";

import PopoverPrimitive from "@starwind-ui/react/popover";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { popoverContent } from "./variants";

export type PopoverContentProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof popoverContent> & {
    side?: "top" | "right" | "bottom" | "left";
    align?: "start" | "center" | "end";
    sideOffset?: number;
    avoidCollisions?: boolean;
    collisionStrategy?: "initial-placement" | "best-fit";
    portalContainer?: string;
    disablePortal?: boolean;
  };

function PopoverContent(props: PopoverContentProps) {
  const {
    className,
    side = "bottom",
    align = "center",
    sideOffset = 4,
    avoidCollisions = true,
    collisionStrategy = "initial-placement",
    exitMotion = "popover",
    portalContainer,
    disablePortal = false,
    children,
    ...rest
  } = props;

  return (
    <PopoverPrimitive.Portal
      container={portalContainer}
      disabled={disablePortal}
      data-slot="popover-portal"
    >
      <PopoverPrimitive.Popup
        className={popoverContent({ exitMotion, class: className })}
        side={side}
        align={align}
        sideOffset={sideOffset}
        avoidCollisions={avoidCollisions}
        collisionStrategy={collisionStrategy}
        data-slot="popover-content"
        {...rest}
      >
        {children}
      </PopoverPrimitive.Popup>
    </PopoverPrimitive.Portal>
  );
}

export default PopoverContent;
