// apps/vue-demo/src/components/starwind-runtime/alert/Alert.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { computed, type HTMLAttributes, ref } from "vue";
import { alert } from "./variants";

defineOptions({ inheritAttrs: false });

export type AlertProps = Omit<HTMLAttributes, "class"> &
  VariantProps<typeof alert> & {
    class?: ClassValue;
  };
type AlertDeclaredProps = {
  class?: ClassValue;
  variant?: AlertProps["variant"];
  role?: AlertProps["role"];
} & /* @vue-ignore */ AlertProps;
const { variant, role, class: className } = defineProps<AlertDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const inferredRole = computed(
  () => role ?? (variant === "error" || variant === "warning" ? "alert" : "status"),
);
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    data-sw-alert
    :class="alert({ variant, class: className })"
    :role="inferredRole"
    v-bind="$attrs"
    data-slot="alert"
  >
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/alert/Alert.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { alert } from "./variants";

export type AlertProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof alert> & {
    ref?: React.Ref<HTMLDivElement>;
  };

function Alert(props: AlertProps) {
  const { variant, role, ref, className, children, ...rest } = props;

  const inferredRole = role ?? (variant === "error" || variant === "warning" ? "alert" : "status");

  return (
    <div
      data-sw-alert
      className={alert({ variant, class: className })}
      role={inferredRole}
      {...rest}
      ref={ref}
      data-slot="alert"
    >
      {children}
    </div>
  );
}

export default Alert;
