// apps/vue-demo/src/components/starwind-runtime/field/FieldContent.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { fieldContent } from "./variants";

defineOptions({ inheritAttrs: false });

export type FieldContentProps = Omit<HTMLAttributes, "class"> &
  VariantProps<typeof fieldContent> & {
    class?: ClassValue;
  };
type FieldContentDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ FieldContentProps;
const { class: className } = defineProps<FieldContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    :class="fieldContent({ class: className })"
    v-bind="$attrs"
    data-slot="field-content"
  >
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/field/FieldContent.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { fieldContent } from "./variants";

export type FieldContentProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof fieldContent> & {
    ref?: React.Ref<HTMLDivElement>;
  };

function FieldContent(props: FieldContentProps) {
  const { ref, className, children, ...rest } = props;

  return (
    <div
      className={fieldContent({ class: className })}
      ref={ref}
      {...rest}
      data-slot="field-content"
    >
      {children}
    </div>
  );
}

export default FieldContent;
