// apps/vue-demo/src/components/starwind-runtime/field/FieldItem.vue
<script setup lang="ts">
import * as FieldPrimitive from "@starwind-ui/vue/field";
import type { ClassValue } from "tailwind-variants";
import { type ComponentPublicInstance, type HTMLAttributes, nextTick, ref } from "vue";
import { fieldItem } from "./variants";

defineOptions({ inheritAttrs: false });

export type FieldItemProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type FieldItemDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ FieldItemProps;
const { class: className } = defineProps<FieldItemDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLDivElement | null>(null);
let pendingPrimitiveRef: ({ element?: HTMLDivElement | null } & ComponentPublicInstance) | null =
  null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLDivElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as ({ element?: HTMLDivElement | null } & ComponentPublicInstance) | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLDivElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLDivElement ? exposed.element : null;
  });
}
</script>

<template>
  <FieldPrimitive.FieldItem
    :ref="setElement"
    :class="fieldItem({ class: className })"
    v-bind="$attrs"
    data-slot="field-item"
  >
    <slot />
  </FieldPrimitive.FieldItem>
</template>

// apps/react-demo/src/components/starwind-runtime/field/FieldItem.tsx
import FieldPrimitive from "@starwind-ui/react/field";
import type * as React from "react";
import { fieldItem } from "./variants";

export type FieldItemProps = React.ComponentPropsWithoutRef<"div"> & {
  ref?: React.Ref<HTMLDivElement>;
};

function FieldItem(props: FieldItemProps) {
  const { ref, className, children, ...rest } = props;

  return (
    <FieldPrimitive.Item
      className={fieldItem({ class: className })}
      ref={ref}
      {...rest}
      data-slot="field-item"
    >
      {children}
    </FieldPrimitive.Item>
  );
}

export default FieldItem;
