// apps/vue-demo/src/components/starwind-runtime/field/FieldTitle.vue
<script setup lang="ts">
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { fieldTitle } from "./variants";

defineOptions({ inheritAttrs: false });

export type FieldTitleProps = Omit<HTMLAttributes, "class"> &
  VariantProps<typeof fieldTitle> & {
    class?: ClassValue;
  };
type FieldTitleDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ FieldTitleProps;
const { class: className } = defineProps<FieldTitleDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    :class="fieldTitle({ class: className })"
    v-bind="$attrs"
    data-slot="field-title"
  >
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/field/FieldTitle.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { fieldTitle } from "./variants";

export type FieldTitleProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof fieldTitle> & {
    ref?: React.Ref<HTMLDivElement>;
  };

function FieldTitle(props: FieldTitleProps) {
  const { ref, className, children, ...rest } = props;

  return (
    <div className={fieldTitle({ class: className })} ref={ref} {...rest} data-slot="field-title">
      {children}
    </div>
  );
}

export default FieldTitle;
