// apps/react-demo/src/components/starwind-runtime/navigation-menu/NavigationMenuLink.tsx
import NavigationMenuPrimitive from "@starwind-ui/react/navigation-menu";
import type * as React from "react";
import { navigationMenuLink } from "./variants";

export type NavigationMenuLinkProps = React.ComponentPropsWithoutRef<"a"> & {
  active?: boolean;
  closeOnClick?: boolean;
};

function NavigationMenuLink(props: NavigationMenuLinkProps) {
  const { active = false, closeOnClick = true, className, children, ...rest } = props;

  return (
    <NavigationMenuPrimitive.Link
      className={navigationMenuLink({ class: className })}
      active={active}
      closeOnClick={closeOnClick}
      {...rest}
      data-slot="navigation-menu-link"
    >
      {children}
    </NavigationMenuPrimitive.Link>
  );
}

export default NavigationMenuLink;

// apps/vue-demo/src/components/starwind-runtime/navigation-menu/NavigationMenuLink.vue
<script setup lang="ts">
import * as NavigationMenuPrimitive from "@starwind-ui/vue/navigation-menu";
import type { ClassValue } from "tailwind-variants";
import { type AnchorHTMLAttributes } from "vue";
import { navigationMenuLink } from "./variants";

defineOptions({ inheritAttrs: false });

export type NavigationMenuLinkProps = Omit<
  AnchorHTMLAttributes,
  "active" | "class" | "closeOnClick"
> & {
  active?: boolean;
  closeOnClick?: boolean;
  class?: ClassValue;
};
type NavigationMenuLinkDeclaredProps = {
  active?: boolean;
  closeOnClick?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ NavigationMenuLinkProps;
const {
  active = false,
  closeOnClick = true,
  class: className,
} = defineProps<NavigationMenuLinkDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <NavigationMenuPrimitive.NavigationMenuLink
    :class="navigationMenuLink({ class: className })"
    :active="active"
    :close-on-click="closeOnClick"
    v-bind="$attrs"
    data-slot="navigation-menu-link"
  >
    <slot />
  </NavigationMenuPrimitive.NavigationMenuLink>
</template>
