// apps/react-demo/src/components/starwind-runtime/navigation-menu/NavigationMenuList.tsx
import NavigationMenuPrimitive from "@starwind-ui/react/navigation-menu";
import type * as React from "react";
import { navigationMenuList } from "./variants";

export type NavigationMenuListProps = React.ComponentPropsWithoutRef<"ul">;

function NavigationMenuList(props: NavigationMenuListProps) {
  const { className, children, ...rest } = props;

  return (
    <NavigationMenuPrimitive.List
      className={navigationMenuList({ class: className })}
      {...rest}
      data-slot="navigation-menu-list"
    >
      {children}
    </NavigationMenuPrimitive.List>
  );
}

export default NavigationMenuList;

// apps/vue-demo/src/components/starwind-runtime/navigation-menu/NavigationMenuList.vue
<script setup lang="ts">
import * as NavigationMenuPrimitive from "@starwind-ui/vue/navigation-menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { navigationMenuList } from "./variants";

defineOptions({ inheritAttrs: false });

export type NavigationMenuListProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type NavigationMenuListDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ NavigationMenuListProps;
const { class: className } = defineProps<NavigationMenuListDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <NavigationMenuPrimitive.NavigationMenuList
    :class="navigationMenuList({ class: className })"
    v-bind="$attrs"
    data-slot="navigation-menu-list"
  >
    <slot />
  </NavigationMenuPrimitive.NavigationMenuList>
</template>
