// apps/vue-demo/src/components/starwind-runtime/combobox/ComboboxItem.vue
<script setup lang="ts">
import * as ComboboxPrimitive from "@starwind-ui/vue/combobox";
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { comboboxItem, comboboxItemIndicator, comboboxItemText } from "./variants";

defineOptions({ inheritAttrs: false });

export type ComboboxItemProps = Omit<
  HTMLAttributes,
  "class" | "disabled" | "indicatorClass" | "inset" | "role" | "showIndicator" | "value"
> &
  VariantProps<typeof comboboxItem> & {
    disabled?: boolean;
    indicatorClass?: string;
    showIndicator?: boolean;
    value: string;
    class?: ClassValue;
    inset?: boolean;
  };
type ComboboxItemDeclaredProps = {
  disabled?: boolean;
  indicatorClass?: string;
  showIndicator?: boolean;
  value: string;
  class?: ClassValue;
  inset?: boolean;
} & /* @vue-ignore */ ComboboxItemProps;
const {
  class: className,
  disabled = false,
  indicatorClass: indicatorClassName,
  inset = false,
  showIndicator = true,
  value,
} = defineProps<ComboboxItemDeclaredProps>();
defineSlots<{
  default?: () => unknown;
  indicator?: () => unknown;
}>();
</script>

<template>
  <ComboboxPrimitive.ComboboxItem
    :class="comboboxItem({ inset, disabled, class: className })"
    :disabled="disabled"
    :value="value"
    v-bind="$attrs"
    data-slot="combobox-item"
  >
    <ComboboxPrimitive.ComboboxItemText :class="comboboxItemText()" data-slot="combobox-item-text">
      <slot />
    </ComboboxPrimitive.ComboboxItemText>
    <template v-if="showIndicator">
      <ComboboxPrimitive.ComboboxItemIndicator
        :class="comboboxItemIndicator({ class: indicatorClassName })"
        data-slot="combobox-item-indicator"
      >
        <slot name="indicator">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
            class="size-4"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M5 12l5 5l10 -10" />
          </svg>
        </slot>
      </ComboboxPrimitive.ComboboxItemIndicator>
    </template>
  </ComboboxPrimitive.ComboboxItem>
</template>

// apps/svelte-demo/src/lib/starwind-runtime/combobox/ComboboxItem.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { ComboboxItem } from "@starwind-ui/svelte/combobox";
  import { combobox, comboboxClear, comboboxContent, comboboxEmpty, comboboxGroup, comboboxGroupLabel, comboboxInput, comboboxInputGroup, comboboxItem, comboboxItemIndicator, comboboxItemText, comboboxLabel, comboboxList, comboboxSeparator, comboboxTrigger, comboboxValue } from "./variants.js";
  import { ComboboxItemText } from "@starwind-ui/svelte/combobox";
  import { ComboboxItemIndicator } from "@starwind-ui/svelte/combobox";

  export type ComboboxItemProps = Omit<ComponentProps<typeof ComboboxItem>, "children"> & VariantProps<typeof comboboxItem> & { children?: Snippet;  indicator?: Snippet; disabled?: boolean; indicatorClass?: string; showIndicator?: boolean; value: string; };
</script>

<script lang="ts">
  let {
    "class": className,
    "disabled": disabled = false,
    "indicatorClass": indicatorClassName,
    "inset": inset = false,
    "showIndicator": showIndicator = true,
    "value": value,
    "children": children,
    "indicator": indicator,
    ...rest
  }: ComboboxItemProps = $props();
</script>

<ComboboxItem
  class={comboboxItem({ "inset": inset, "disabled": disabled, "class": cx(className) })}
  disabled={disabled}
  value={value}
  {...rest}
  data-slot={"combobox-item"}
>
  <ComboboxItemText
    class={comboboxItemText({  })}
    data-slot={"combobox-item-text"}
  >
    {@render children?.()}
  </ComboboxItemText>
  {#if showIndicator}
    <ComboboxItemIndicator
      class={comboboxItemIndicator({ "class": cx(indicatorClassName) })}
      data-slot={"combobox-item-indicator"}
    >
      {#if indicator}{@render indicator()}{:else}<svg
        xmlns={"http://www.w3.org/2000/svg"}
        viewBox={"0 0 24 24"}
        fill={"none"}
        stroke={"currentColor"}
        stroke-width={"2"}
        stroke-linecap={"round"}
        stroke-linejoin={"round"}
        aria-hidden={"true"}
        class={"size-4"}
      >
        <path
          stroke={"none"}
          d={"M0 0h24v24H0z"}
          fill={"none"}
        />
        <path
          d={"M5 12l5 5l10 -10"}
        />
      </svg>{/if}
    </ComboboxItemIndicator>
  {/if}
</ComboboxItem>
