// apps/react-demo/src/components/starwind-runtime/dialog/DialogFooter.tsx
import type * as React from "react";
import { dialogFooter } from "./variants";

export type DialogFooterProps = React.ComponentPropsWithoutRef<"div">;

function DialogFooter(props: DialogFooterProps) {
  const { className, children, ...rest } = props;

  return (
    <div className={dialogFooter({ class: className })} {...rest} data-slot="dialog-footer">
      {children}
    </div>
  );
}

export default DialogFooter;

// apps/vue-demo/src/components/starwind-runtime/dialog/DialogFooter.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dialogFooter } from "./variants";

defineOptions({ inheritAttrs: false });

export type DialogFooterProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type DialogFooterDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ DialogFooterProps;
const { class: className } = defineProps<DialogFooterDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div :class="dialogFooter({ class: className })" v-bind="$attrs" data-slot="dialog-footer">
    <slot />
  </div>
</template>
