// apps/vue-demo/src/components/starwind-runtime/accordion/AccordionItem.vue
<script setup lang="ts">
import * as AccordionPrimitive from "@starwind-ui/vue/accordion";
import type { ClassValue } from "tailwind-variants";
import { type ComponentPublicInstance, type HTMLAttributes, nextTick, ref } from "vue";
import { accordionItem } from "./variants";

defineOptions({ inheritAttrs: false });

export type AccordionItemProps = Omit<HTMLAttributes, "class" | "disabled" | "value"> & {
  value: string;
  disabled?: boolean;
  class?: ClassValue;
};
type AccordionItemDeclaredProps = {
  value: string;
  disabled?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ AccordionItemProps;
const { value, disabled = false, class: className } = defineProps<AccordionItemDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLElement | null>(null);
let pendingPrimitiveRef: ({ element?: HTMLElement | null } & ComponentPublicInstance) | null = null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as ({ element?: HTMLElement | null } & ComponentPublicInstance) | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLElement ? exposed.element : null;
  });
}
</script>

<template>
  <AccordionPrimitive.AccordionItem
    :ref="setElement"
    :class="accordionItem({ class: className })"
    :value="value"
    :disabled="disabled"
    v-bind="$attrs"
    data-slot="accordion-item"
  >
    <slot />
  </AccordionPrimitive.AccordionItem>
</template>

// apps/react-demo/src/components/starwind-runtime/accordion/AccordionItem.tsx
import AccordionPrimitive from "@starwind-ui/react/accordion";
import type * as React from "react";
import { accordionItem } from "./variants";

export type AccordionItemProps = React.ComponentPropsWithoutRef<"div"> & {
  value: string;
  disabled?: boolean;
};

function AccordionItem(props: AccordionItemProps) {
  const { value, disabled = false, className, children, ...rest } = props;

  return (
    <AccordionPrimitive.Item
      className={accordionItem({ class: className })}
      value={value}
      disabled={disabled}
      {...rest}
      data-slot="accordion-item"
    >
      {children}
    </AccordionPrimitive.Item>
  );
}

export default AccordionItem;
