// apps/react-demo/src/components/starwind-runtime/checkbox/Checkbox.tsx
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import "./styles.css";
import CheckboxPrimitive from "@starwind-ui/react/checkbox";
import { IconCheck as Check } from "@tabler/icons-react";
import { checkbox, checkboxIndicator, checkboxLabel, checkboxWrapper } from "./variants";

export type CheckboxProps = Omit<
  React.ComponentPropsWithoutRef<"span">,
  "defaultChecked" | "id" | "onChange"
> &
  VariantProps<typeof checkbox> & {
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    form?: string;
    id?: string;
    indeterminate?: boolean;
    label?: string;
    name?: string;
    nativeButton?: boolean;
    onCheckedChange?: (
      checked: boolean,
      details: import("@starwind-ui/react/checkbox").CheckboxCheckedChangeDetails,
    ) => void;
    readOnly?: boolean;
    ref?: React.Ref<HTMLSpanElement | HTMLButtonElement>;
    required?: boolean;
    uncheckedValue?: string;
    value?: string;
  };

function Checkbox(props: CheckboxProps) {
  const {
    variant,
    size,
    checked,
    defaultChecked,
    disabled = false,
    form,
    id,
    indeterminate = false,
    label,
    name,
    nativeButton = false,
    onCheckedChange,
    readOnly = false,
    ref,
    required = false,
    uncheckedValue,
    value,
    className,
    ...rest
  } = props;

  const ariaLabel = rest["aria-label"] ?? label;

  return (
    <div className={checkboxWrapper()} data-sw-checkbox-wrapper data-slot="checkbox-wrapper">
      <CheckboxPrimitive.Root
        className={checkbox({ variant, size, class: className })}
        checked={checked}
        defaultChecked={defaultChecked}
        disabled={disabled}
        form={form}
        id={id}
        indeterminate={indeterminate}
        name={name}
        nativeButton={nativeButton}
        onCheckedChange={onCheckedChange}
        readOnly={readOnly}
        ref={ref}
        required={required}
        uncheckedValue={uncheckedValue}
        value={value}
        {...rest}
        aria-label={ariaLabel}
        data-slot="checkbox"
      >
        <CheckboxPrimitive.Indicator
          keepMounted
          className={checkboxIndicator({ variant, size })}
          data-slot="checkbox-indicator"
        >
          <Check data-sw-checkbox-check-icon />
        </CheckboxPrimitive.Indicator>
      </CheckboxPrimitive.Root>

      {label && (
        <label htmlFor={id} className={checkboxLabel({ size })} data-slot="checkbox-label">
          {label}
        </label>
      )}
    </div>
  );
}

export default Checkbox;

// apps/svelte-demo/src/lib/starwind-runtime/checkbox/Checkbox.svelte
<script module lang="ts">
  import type { ComponentProps } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { CheckboxRoot } from "@starwind-ui/svelte/checkbox";
  import { checkboxWrapper, checkbox, checkboxIndicator, checkboxLabel } from "./variants.js";
  import { CheckboxIndicator } from "@starwind-ui/svelte/checkbox";
  import "./styles.css";

  type PrimitiveProps = ComponentProps<typeof CheckboxRoot>;
  type WithStyledProps<T> = T extends unknown ? Omit<T, "children"> & VariantProps<typeof checkbox> & { label?: string } : never;
  export type CheckboxProps = WithStyledProps<PrimitiveProps>;
</script>

<script lang="ts">
  let {
    "variant": variant,
    "size": size,
    "defaultChecked": defaultChecked,
    "disabled": disabled = false,
    "form": form,
    "id": id,
    "indeterminate": indeterminate = false,
    "label": label,
    "name": name,
    "nativeButton": nativeButton = false,
    "readOnly": readOnly = false,
    "required": required = false,
    "uncheckedValue": uncheckedValue,
    "value": value,
    "class": className,
    checked = $bindable(),
    "onCheckedChange": onCheckedChange,
    "ref": ref,
    ...rest
  }: CheckboxProps = $props();

  let ariaLabel = $derived(rest["aria-label"] ?? label);
</script>

<div
  class={checkboxWrapper({  })}
  data-sw-checkbox-wrapper
  data-slot={"checkbox-wrapper"}
>
  <CheckboxRoot
    class={checkbox({ "variant": variant, "size": size, "class": cx(className) })}
    defaultChecked={defaultChecked}
    disabled={disabled}
    form={form}
    id={id}
    indeterminate={indeterminate}
    name={name}
    onCheckedChange={onCheckedChange}
    readOnly={readOnly}
    required={required}
    uncheckedValue={uncheckedValue}
    value={value}
    {...({ ...rest, nativeButton, ref } as PrimitiveProps)}
    aria-label={ariaLabel}
    data-slot={"checkbox"}
    bind:checked={checked}
  >
    <CheckboxIndicator
      keepMounted
      class={checkboxIndicator({ "variant": variant, "size": size })}
      data-slot={"checkbox-indicator"}
    >
      <svg
        xmlns={"http://www.w3.org/2000/svg"}
        viewBox={"0 0 24 24"}
        fill={"none"}
        stroke={"currentColor"}
        stroke-width={"2"}
        stroke-linecap={"round"}
        stroke-linejoin={"round"}
        aria-hidden={"true"}
        data-sw-checkbox-check-icon
      >
        <path
          stroke={"none"}
          d={"M0 0h24v24H0z"}
          fill={"none"}
        />
        <path
          d={"M5 12l5 5l10 -10"}
        />
      </svg>
    </CheckboxIndicator>
  </CheckboxRoot>
  {#if label}
    <label
      for={id}
      class={checkboxLabel({ "size": size })}
      data-slot={"checkbox-label"}
    >
      {label}
    </label>
  {/if}
</div>
