// apps/react-demo/src/components/starwind-runtime/hover-card/HoverCardTrigger.tsx
import PreviewCardPrimitive from "@starwind-ui/react/preview-card";
import type * as React from "react";
import { hoverCardTrigger } from "./variants";

export type HoverCardTriggerProps = React.ComponentPropsWithoutRef<"a"> & {
  asChild?: boolean;
  closeDelay?: number;
  disabled?: boolean;
  openDelay?: number;
};

function HoverCardTrigger(props: HoverCardTriggerProps) {
  const {
    asChild = false,
    closeDelay,
    disabled = false,
    openDelay,
    className,
    children,
    ...rest
  } = props;

  const triggerBaseClassName = hoverCardTrigger({ class: className });
  const triggerClassName = asChild ? className : triggerBaseClassName;

  return (
    <PreviewCardPrimitive.Trigger
      className={triggerClassName}
      asChild={asChild}
      closeDelay={closeDelay}
      disabled={disabled}
      openDelay={openDelay}
      {...rest}
      data-slot="hover-card-trigger"
    >
      {children}
    </PreviewCardPrimitive.Trigger>
  );
}

export default HoverCardTrigger;

// apps/vue-demo/src/components/starwind-runtime/hover-card/HoverCardTrigger.vue
<script setup lang="ts">
import * as PreviewCardPrimitive from "@starwind-ui/vue/preview-card";
import type { ClassValue } from "tailwind-variants";
import { type AnchorHTMLAttributes, computed } from "vue";
import { hoverCardTrigger } from "./variants";

defineOptions({ inheritAttrs: false });

export type HoverCardTriggerProps = Omit<
  AnchorHTMLAttributes,
  "asChild" | "class" | "closeDelay" | "disabled" | "openDelay"
> & {
  asChild?: boolean;
  closeDelay?: number;
  disabled?: boolean;
  openDelay?: number;
  class?: ClassValue;
};
type HoverCardTriggerDeclaredProps = {
  asChild?: boolean;
  closeDelay?: number;
  disabled?: boolean;
  openDelay?: number;
  class?: ClassValue;
} & /* @vue-ignore */ HoverCardTriggerProps;
const {
  asChild = false,
  closeDelay,
  disabled = false,
  openDelay,
  class: className,
} = defineProps<HoverCardTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const triggerBaseClassName = computed(() => hoverCardTrigger({ class: className }));
const triggerClassName = computed(() => (asChild ? className : triggerBaseClassName.value));
</script>

<template>
  <PreviewCardPrimitive.PreviewCardTrigger
    :class="triggerClassName"
    :as-child="asChild"
    :close-delay="closeDelay"
    :disabled="disabled"
    :open-delay="openDelay"
    v-bind="$attrs"
    data-slot="hover-card-trigger"
  >
    <slot />
  </PreviewCardPrimitive.PreviewCardTrigger>
</template>
