// apps/svelte-demo/src/lib/starwind-runtime/toggle/Toggle.svelte
<script module lang="ts">
  import type { ComponentProps } from "svelte";
  import { untrack } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { ToggleRoot } from "@starwind-ui/svelte/toggle";
  import { toggle } from "./variants.js";

  type PrimitiveProps=ComponentProps<typeof ToggleRoot>;
  type StyledProps<T>=T extends unknown?T & VariantProps<typeof toggle>:never;
  export type ToggleProps=StyledProps<PrimitiveProps>;
</script>

<script lang="ts">
  let {
    "variant": variant,
    "size": size,
    "defaultPressed": defaultPressed,
    "disabled": disabled = false,
    "nativeButton": nativeButton,
    "syncGroup": syncGroup,
    "value": value,
    "data-slot": dataSlot = "toggle",
    "class": className,
    pressed = $bindable(),
    "pressed": commandValue,
    "ref": ref,
    "onPressedChange": onPressedChange,
    "children": children,
    ...rest
  }: ToggleProps = $props();

  let observedCommand=untrack(()=>commandValue);
  $effect(()=>{const next=commandValue;untrack(()=>{if(Object.is(next,observedCommand))return;observedCommand=next;if(!Object.is(next,pressed))pressed=next;});});
</script>

<ToggleRoot
  class={toggle({ "variant": variant, "size": size, "class": cx(className) })}
  {...({ ...rest, nativeButton, ref, value, defaultPressed, disabled, onPressedChange, syncGroup } as PrimitiveProps)}
  data-slot={dataSlot}
  bind:pressed={pressed}
>
  {@render children?.()}
</ToggleRoot>

// apps/react-demo/src/components/starwind-runtime/toggle/Toggle.tsx
import TogglePrimitive from "@starwind-ui/react/toggle";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { toggle } from "./variants";

export type ToggleProps = Omit<
  React.ComponentPropsWithoutRef<"button">,
  "aria-pressed" | "defaultPressed" | "disabled" | "onChange" | "type" | "value"
> &
  VariantProps<typeof toggle> & {
    defaultPressed?: boolean;
    disabled?: boolean;
    nativeButton?: boolean;
    "data-slot"?: string;
    onPressedChange?: (
      pressed: boolean,
      details: import("@starwind-ui/react/toggle").TogglePressedChangeDetails,
    ) => void;
    pressed?: boolean;
    ref?: React.Ref<HTMLButtonElement | HTMLSpanElement>;
    syncGroup?: string;
    value?: string;
  };

function Toggle(props: ToggleProps) {
  const {
    variant,
    size,
    defaultPressed,
    disabled = false,
    nativeButton,
    onPressedChange,
    pressed,
    ref,
    syncGroup,
    value,
    "data-slot": dataSlot = "toggle",
    className,
    children,
    ...rest
  } = props;

  return (
    <TogglePrimitive.Root
      className={toggle({ variant, size, class: className })}
      defaultPressed={defaultPressed}
      disabled={disabled}
      nativeButton={nativeButton}
      onPressedChange={onPressedChange}
      pressed={pressed}
      ref={ref}
      syncGroup={syncGroup}
      value={value}
      {...rest}
      data-slot={dataSlot}
    >
      {children}
    </TogglePrimitive.Root>
  );
}

export default Toggle;
