// apps/vue-demo/src/components/starwind-runtime/input-group/InputGroup.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { inputGroup } from "./variants";

defineOptions({ inheritAttrs: false });

export type InputGroupProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type InputGroupDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ InputGroupProps;
const { class: className } = defineProps<InputGroupDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    role="group"
    :class="inputGroup({ class: className })"
    data-slot="input-group"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/input-group/InputGroup.tsx
import type * as React from "react";
import { inputGroup } from "./variants";

export type InputGroupProps = React.ComponentPropsWithoutRef<"div">;

function InputGroup(props: InputGroupProps) {
  const { className, children, ...rest } = props;

  return (
    <div
      role="group"
      className={inputGroup({ class: className })}
      {...rest}
      data-slot="input-group"
    >
      {children}
    </div>
  );
}

export default InputGroup;
