// apps/react-demo/src/components/starwind-runtime/field/FieldValidity.tsx
import FieldPrimitive from "@starwind-ui/react/field";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { fieldValidity } from "./variants";

export type FieldValidityProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof fieldValidity> & {
    match?:
      | boolean
      | "badInput"
      | "customError"
      | "patternMismatch"
      | "rangeOverflow"
      | "rangeUnderflow"
      | "stepMismatch"
      | "tooLong"
      | "tooShort"
      | "typeMismatch"
      | "valid"
      | "valueMissing";
    ref?: React.Ref<HTMLDivElement>;
  };

function FieldValidity(props: FieldValidityProps) {
  const { match, ref, className, children, ...rest } = props;

  return (
    <FieldPrimitive.Validity
      className={fieldValidity({ class: className })}
      match={match}
      ref={ref}
      {...rest}
      data-slot="field-validity"
    >
      {children}
    </FieldPrimitive.Validity>
  );
}

export default FieldValidity;

// apps/vue-demo/src/components/starwind-runtime/field/FieldValidity.vue
<script setup lang="ts">
import * as FieldPrimitive from "@starwind-ui/vue/field";
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type ComponentPublicInstance, type HTMLAttributes, nextTick, ref } from "vue";
import { fieldValidity } from "./variants";

defineOptions({ inheritAttrs: false });

export type FieldValidityProps = Omit<HTMLAttributes, "class" | "match"> &
  VariantProps<typeof fieldValidity> & {
    match?:
      | boolean
      | "badInput"
      | "customError"
      | "patternMismatch"
      | "rangeOverflow"
      | "rangeUnderflow"
      | "stepMismatch"
      | "tooLong"
      | "tooShort"
      | "typeMismatch"
      | "valid"
      | "valueMissing";
    class?: ClassValue;
  };
type FieldValidityDeclaredProps = {
  match?:
    | boolean
    | "badInput"
    | "customError"
    | "patternMismatch"
    | "rangeOverflow"
    | "rangeUnderflow"
    | "stepMismatch"
    | "tooLong"
    | "tooShort"
    | "typeMismatch"
    | "valid"
    | "valueMissing";
  class?: ClassValue;
} & /* @vue-ignore */ FieldValidityProps;
const { match, class: className } = defineProps<FieldValidityDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLDivElement | null>(null);
let pendingPrimitiveRef: ({ element?: HTMLDivElement | null } & ComponentPublicInstance) | null =
  null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLDivElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as ({ element?: HTMLDivElement | null } & ComponentPublicInstance) | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLDivElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLDivElement ? exposed.element : null;
  });
}
</script>

<template>
  <FieldPrimitive.FieldValidity
    :ref="setElement"
    :class="fieldValidity({ class: className })"
    :match="match"
    v-bind="$attrs"
    data-slot="field-validity"
  >
    <slot />
  </FieldPrimitive.FieldValidity>
</template>
