// apps/react-demo/src/components/starwind-runtime/field/FieldLabel.tsx
import FieldPrimitive from "@starwind-ui/react/field";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { fieldLabel } from "./variants";

export type FieldLabelProps = React.ComponentPropsWithoutRef<"label"> &
  VariantProps<typeof fieldLabel> & {
    ref?: React.Ref<HTMLLabelElement>;
  };

function FieldLabel(props: FieldLabelProps) {
  const { size, ref, className, children, ...rest } = props;

  return (
    <FieldPrimitive.Label
      className={fieldLabel({ size, class: className })}
      ref={ref}
      {...rest}
      data-slot="field-label"
    >
      {children}
    </FieldPrimitive.Label>
  );
}

export default FieldLabel;

// apps/vue-demo/src/components/starwind-runtime/field/FieldLabel.vue
<script setup lang="ts">
import * as FieldPrimitive from "@starwind-ui/vue/field";
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type ComponentPublicInstance, type HTMLAttributes, nextTick, ref } from "vue";
import { fieldLabel } from "./variants";

defineOptions({ inheritAttrs: false });

export type FieldLabelProps = Omit<HTMLAttributes, "class"> &
  VariantProps<typeof fieldLabel> & {
    class?: ClassValue;
  };
type FieldLabelDeclaredProps = {
  class?: ClassValue;
  size?: FieldLabelProps["size"];
} & /* @vue-ignore */ FieldLabelProps;
const { size, class: className } = defineProps<FieldLabelDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const element = ref<HTMLLabelElement | null>(null);
let pendingPrimitiveRef: ({ element?: HTMLLabelElement | null } & ComponentPublicInstance) | null =
  null;
defineExpose({ element });

function setElement(value: Element | ComponentPublicInstance | null): void {
  if (value instanceof HTMLLabelElement) {
    pendingPrimitiveRef = null;
    element.value = value;
    return;
  }
  const exposed = value as ({ element?: HTMLLabelElement | null } & ComponentPublicInstance) | null;
  pendingPrimitiveRef = exposed;
  element.value = exposed?.element instanceof HTMLLabelElement ? exposed.element : null;
  if (!exposed || element.value) return;

  void nextTick(() => {
    if (pendingPrimitiveRef !== exposed) return;
    element.value = exposed.element instanceof HTMLLabelElement ? exposed.element : null;
  });
}
</script>

<template>
  <FieldPrimitive.FieldLabel
    :ref="setElement"
    :class="fieldLabel({ size, class: className })"
    v-bind="$attrs"
    data-slot="field-label"
  >
    <slot />
  </FieldPrimitive.FieldLabel>
</template>
