// apps/svelte-demo/src/lib/starwind-runtime/input-otp/InputOtpSlot.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import type { VariantProps } from "tailwind-variants";
  import { cx } from "tailwind-variants";
  import { InputOtpSlot as PrimitivePart } from "@starwind-ui/svelte/input-otp";
  import { inputOtp, inputOtpGroup, inputOtpSeparator, inputOtpSlot } from "./variants.js";
  import { InputOtpSlot } from "@starwind-ui/svelte/input-otp";

  export type InputOtpSlotProps = Omit<ComponentProps<typeof PrimitivePart>, "caret">;
</script>

<script lang="ts">
  let {
    "index": index,
    "class": className,
    "ref": ref,
    ...rest
  }: InputOtpSlotProps = $props();
</script>

<InputOtpSlot
  class={inputOtpSlot({ "class": cx(className) })}
  index={index}
  ref={ref}
  {...rest}
  data-slot={"input-otp-slot"}
/>

// apps/react-demo/src/components/starwind-runtime/input-otp/InputOtpSlot.tsx
import InputOtpPrimitive from "@starwind-ui/react/input-otp";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { inputOtpSlot } from "./variants";

export type InputOtpSlotProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof inputOtpSlot> & {
    index?: number;
    ref?: React.Ref<HTMLDivElement>;
  };

function InputOtpSlot(props: InputOtpSlotProps) {
  const { size, index, ref, className, ...rest } = props;

  return (
    <InputOtpPrimitive.Slot
      className={inputOtpSlot({ size, class: className })}
      index={index}
      ref={ref}
      {...rest}
      data-slot="input-otp-slot"
    />
  );
}

export default InputOtpSlot;
