// apps/react-demo/src/components/starwind-runtime/checkbox-group/CheckboxGroup.tsx
import CheckboxGroupPrimitive from "@starwind-ui/react/checkbox-group";
import type * as React from "react";
import type { VariantProps } from "tailwind-variants";
import { checkboxGroup } from "./variants";

export type CheckboxGroupProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "defaultValue" | "onChange"
> &
  VariantProps<typeof checkboxGroup> & {
    defaultValue?: string[];
    disabled?: boolean;
    onValueChange?: (
      value: import("@starwind-ui/react/checkbox-group").CheckboxGroupValue,
      details: import("@starwind-ui/react/checkbox-group").CheckboxGroupValueChangeDetails,
    ) => void;
    ref?: React.Ref<HTMLDivElement>;
    value?: import("@starwind-ui/react/checkbox-group").CheckboxGroupValue;
  };

function CheckboxGroup(props: CheckboxGroupProps) {
  const {
    defaultValue,
    disabled = false,
    onValueChange,
    ref,
    value,
    className,
    children,
    ...rest
  } = props;

  return (
    <CheckboxGroupPrimitive.Root
      className={checkboxGroup({ class: className })}
      defaultValue={defaultValue}
      disabled={disabled}
      onValueChange={onValueChange}
      ref={ref}
      value={value}
      {...rest}
      data-slot="checkbox-group"
    >
      {children}
    </CheckboxGroupPrimitive.Root>
  );
}

export default CheckboxGroup;

// apps/vue-demo/src/components/starwind-runtime/checkbox-group/CheckboxGroup.vue
<script setup lang="ts">
import * as CheckboxGroupPrimitive from "@starwind-ui/vue/checkbox-group";
import type { ClassValue, VariantProps } from "tailwind-variants";
import { type HTMLAttributes, useAttrs } from "vue";
import { checkboxGroup } from "./variants";

defineOptions({ inheritAttrs: false });

export type CheckboxGroupProps = Omit<
  HTMLAttributes,
  "class" | "defaultValue" | "disabled" | "modelValue" | "onChange"
> &
  VariantProps<typeof checkboxGroup> & {
    defaultValue?: string[];
    disabled?: boolean;
    class?: ClassValue;
    modelValue?: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValue;
  };
type CheckboxGroupDeclaredProps = {
  defaultValue?: string[];
  disabled?: boolean;
  class?: ClassValue;
  modelValue?: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValue;
} & /* @vue-ignore */ CheckboxGroupProps;
const {
  defaultValue,
  disabled = false,
  class: className,
  modelValue,
} = defineProps<CheckboxGroupDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const emit = defineEmits<{
  valueChange: [
    value: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValue,
    detail: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValueChangeDetails,
  ];
  "update:modelValue": [value: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValue];
}>();
function handleValueChange(
  value: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValue,
  detail: import("@starwind-ui/vue/checkbox-group").CheckboxGroupValueChangeDetails,
): void {
  emit("valueChange", value, detail);
}
</script>

<template>
  <CheckboxGroupPrimitive.CheckboxGroupRoot
    :class="checkboxGroup({ class: className })"
    :default-value="defaultValue"
    :disabled="disabled"
    v-bind="attrs"
    data-slot="checkbox-group"
    :model-value="modelValue"
    @update:model-value="emit('update:modelValue', $event)"
    @value-change="handleValueChange"
  >
    <slot />
  </CheckboxGroupPrimitive.CheckboxGroupRoot>
</template>
