// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownRadioGroup.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes, useAttrs } from "vue";
import { dropdownRadioGroup } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownRadioGroupProps = Omit<
  HTMLAttributes,
  "class" | "defaultValue" | "modelValue"
> & {
  defaultValue?: string;
  class?: ClassValue;
  modelValue?: string;
};
type DropdownRadioGroupDeclaredProps = {
  defaultValue?: string;
  class?: ClassValue;
  modelValue?: string;
} & /* @vue-ignore */ DropdownRadioGroupProps;
const {
  class: className,
  defaultValue,
  modelValue,
} = defineProps<DropdownRadioGroupDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const attrs = useAttrs();
const emit = defineEmits<{
  valueChange: [value: string, detail: import("@starwind-ui/vue/menu").MenuValueChangeDetails];
  "update:modelValue": [value: string];
}>();
function handleValueChange(
  value: string,
  detail: import("@starwind-ui/vue/menu").MenuValueChangeDetails,
): void {
  emit("valueChange", value, detail);
}
</script>

<template>
  <MenuPrimitive.MenuRadioGroup
    :class="dropdownRadioGroup({ class: className })"
    :model-value="modelValue"
    :default-value="defaultValue"
    v-bind="attrs"
    data-slot="dropdown-radio-group"
    @update:model-value="emit('update:modelValue', $event)"
    @value-change="handleValueChange"
  >
    <slot />
  </MenuPrimitive.MenuRadioGroup>
</template>

// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownRadioGroup.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdownRadioGroup } from "./variants";

export type DropdownRadioGroupProps = React.ComponentPropsWithoutRef<"div"> & {
  value?: string;
  defaultValue?: string;
  onValueChange?: (
    value: string,
    details: import("@starwind-ui/react/menu").MenuValueChangeDetails,
  ) => void;
};

function DropdownRadioGroup(props: DropdownRadioGroupProps) {
  const { className, value, defaultValue, onValueChange, children, ...rest } = props;

  return (
    <MenuPrimitive.RadioGroup
      className={dropdownRadioGroup({ class: className })}
      value={value}
      defaultValue={defaultValue}
      onValueChange={onValueChange}
      {...rest}
      data-slot="dropdown-radio-group"
    >
      {children}
    </MenuPrimitive.RadioGroup>
  );
}

export default DropdownRadioGroup;
