// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownCheckboxItem.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dropdownCheckboxItem, dropdownCheckboxItemIndicator } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownCheckboxItemProps = Omit<
  HTMLAttributes,
  | "aria-checked"
  | "checked"
  | "class"
  | "closeOnClick"
  | "defaultChecked"
  | "disabled"
  | "indicatorClass"
  | "inset"
  | "role"
  | "showIndicator"
> & {
  checked?: boolean;
  defaultChecked?: boolean;
  closeOnClick?: boolean;
  inset?: boolean;
  disabled?: boolean;
  indicatorClass?: string;
  showIndicator?: boolean;
  class?: ClassValue;
};
type DropdownCheckboxItemDeclaredProps = {
  checked?: boolean;
  defaultChecked?: boolean;
  closeOnClick?: boolean;
  inset?: boolean;
  disabled?: boolean;
  indicatorClass?: string;
  showIndicator?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ DropdownCheckboxItemProps;
const {
  class: className,
  checked,
  defaultChecked = false,
  closeOnClick = false,
  inset = false,
  disabled = false,
  indicatorClass: indicatorClassName,
  showIndicator = true,
} = defineProps<DropdownCheckboxItemDeclaredProps>();
defineSlots<{
  default?: () => unknown;
  indicator?: () => unknown;
}>();
</script>

<template>
  <MenuPrimitive.MenuCheckboxItem
    :class="dropdownCheckboxItem({ inset, disabled, class: className })"
    :checked="checked"
    :default-checked="defaultChecked"
    :close-on-click="closeOnClick"
    :disabled="disabled"
    v-bind="$attrs"
    data-slot="dropdown-checkbox-item"
  >
    <template v-if="showIndicator">
      <MenuPrimitive.MenuCheckboxItemIndicator
        :class="dropdownCheckboxItemIndicator({ class: indicatorClassName })"
        data-slot="dropdown-checkbox-item-indicator"
      >
        <slot name="indicator">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
            class="size-4"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M5 12l5 5l10 -10" />
          </svg>
        </slot>
      </MenuPrimitive.MenuCheckboxItemIndicator>
    </template>
    <slot />
  </MenuPrimitive.MenuCheckboxItem>
</template>

// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownCheckboxItem.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import { IconCheck as Check } from "@tabler/icons-react";
import type * as React from "react";
import { dropdownCheckboxItem, dropdownCheckboxItemIndicator } from "./variants";

export type DropdownCheckboxItemProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  "aria-checked" | "role"
> & {
  checked?: boolean;
  defaultChecked?: boolean;
  closeOnClick?: boolean;
  inset?: boolean;
  disabled?: boolean;
  indicatorClass?: string;
  showIndicator?: boolean;
  indicator?: React.ReactNode;
};

function DropdownCheckboxItem(props: DropdownCheckboxItemProps) {
  const {
    className,
    checked,
    defaultChecked = false,
    closeOnClick = false,
    inset = false,
    disabled = false,
    indicatorClass: indicatorClassName,
    showIndicator = true,
    children,
    indicator,
    ...rest
  } = props;

  return (
    <MenuPrimitive.CheckboxItem
      className={dropdownCheckboxItem({ inset, disabled, class: className })}
      checked={checked}
      defaultChecked={defaultChecked}
      closeOnClick={closeOnClick}
      disabled={disabled}
      {...rest}
      data-slot="dropdown-checkbox-item"
    >
      {showIndicator && (
        <MenuPrimitive.CheckboxItemIndicator
          className={dropdownCheckboxItemIndicator({ class: indicatorClassName })}
          data-slot="dropdown-checkbox-item-indicator"
        >
          {indicator ?? <Check className="size-4" />}
        </MenuPrimitive.CheckboxItemIndicator>
      )}

      {children}
    </MenuPrimitive.CheckboxItem>
  );
}

export default DropdownCheckboxItem;
