// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownTrigger.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type ButtonHTMLAttributes, computed } from "vue";
import { dropdownTrigger } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownTriggerProps = Omit<ButtonHTMLAttributes, "asChild" | "class"> & {
  asChild?: boolean;
  class?: ClassValue;
};
type DropdownTriggerDeclaredProps = {
  asChild?: boolean;
  class?: ClassValue;
} & /* @vue-ignore */ DropdownTriggerProps;
const { asChild = false, class: className } = defineProps<DropdownTriggerDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
const triggerBaseClassName = computed(() => dropdownTrigger({ class: className }));
const triggerClassName = computed(() => (asChild ? className : triggerBaseClassName.value));
</script>

<template>
  <MenuPrimitive.MenuTrigger
    :class="triggerClassName"
    :as-child="asChild"
    v-bind="$attrs"
    data-slot="dropdown-trigger"
  >
    <slot />
  </MenuPrimitive.MenuTrigger>
</template>

// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownTrigger.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdownTrigger } from "./variants";

export type DropdownTriggerProps = React.ComponentPropsWithoutRef<"button"> & {
  asChild?: boolean;
  ref?: React.Ref<HTMLElement>;
};

function DropdownTrigger(props: DropdownTriggerProps) {
  const { asChild = false, ref, className, children, ...rest } = props;

  const triggerBaseClassName = dropdownTrigger({ class: className });
  const triggerClassName = asChild ? className : triggerBaseClassName;

  return (
    <MenuPrimitive.Trigger
      className={triggerClassName}
      asChild={asChild}
      ref={ref}
      {...rest}
      data-slot="dropdown-trigger"
    >
      {children}
    </MenuPrimitive.Trigger>
  );
}

export default DropdownTrigger;
