// apps/vue-demo/src/components/starwind-runtime/dropdown/DropdownRadioItemIndicator.vue
<script setup lang="ts">
import * as MenuPrimitive from "@starwind-ui/vue/menu";
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dropdownRadioItemIndicator } from "./variants";

defineOptions({ inheritAttrs: false });

export type DropdownRadioItemIndicatorProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type DropdownRadioItemIndicatorDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ DropdownRadioItemIndicatorProps;
const { class: className } = defineProps<DropdownRadioItemIndicatorDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <MenuPrimitive.MenuRadioItemIndicator
    :class="dropdownRadioItemIndicator({ class: className })"
    v-bind="$attrs"
    data-slot="dropdown-radio-item-indicator"
  >
    <slot />
  </MenuPrimitive.MenuRadioItemIndicator>
</template>

// apps/react-demo/src/components/starwind-runtime/dropdown/DropdownRadioItemIndicator.tsx
import MenuPrimitive from "@starwind-ui/react/menu";
import type * as React from "react";
import { dropdownRadioItemIndicator } from "./variants";

export type DropdownRadioItemIndicatorProps = React.ComponentPropsWithoutRef<"span">;

function DropdownRadioItemIndicator(props: DropdownRadioItemIndicatorProps) {
  const { className, children, ...rest } = props;

  return (
    <MenuPrimitive.RadioItemIndicator
      className={dropdownRadioItemIndicator({ class: className })}
      {...rest}
      data-slot="dropdown-radio-item-indicator"
    >
      {children}
    </MenuPrimitive.RadioItemIndicator>
  );
}

export default DropdownRadioItemIndicator;
