// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarContent.tsx
import type * as React from "react";
import { sidebarContent } from "./variants";

export type SidebarContentProps = React.ComponentPropsWithoutRef<"div"> & {
  ref?: React.Ref<HTMLDivElement>;
  "data-slot"?: string;
};

function SidebarContent(props: SidebarContentProps) {
  const { ref, "data-slot": dataSlot = "sidebar-content", className, children, ...rest } = props;

  return (
    <div
      className={sidebarContent({ class: className })}
      data-sidebar="content"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </div>
  );
}

export default SidebarContent;

// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarContent.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarContent } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarContentProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarContentDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarContentProps, "data-slot">;
const { dataSlot = "sidebar-content", class: className } =
  defineProps<SidebarContentDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    :class="sidebarContent({ class: className })"
    data-sidebar="content"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </div>
</template>
