// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarFooter.tsx
import type * as React from "react";
import { sidebarFooter } from "./variants";

export type SidebarFooterProps = React.ComponentPropsWithoutRef<"div"> & {
  ref?: React.Ref<HTMLDivElement>;
  "data-slot"?: string;
};

function SidebarFooter(props: SidebarFooterProps) {
  const { ref, "data-slot": dataSlot = "sidebar-footer", className, children, ...rest } = props;

  return (
    <div
      className={sidebarFooter({ class: className })}
      data-sidebar="footer"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </div>
  );
}

export default SidebarFooter;

// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarFooter.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarFooter } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarFooterProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarFooterDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarFooterProps, "data-slot">;
const { dataSlot = "sidebar-footer", class: className } = defineProps<SidebarFooterDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    :class="sidebarFooter({ class: className })"
    data-sidebar="footer"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </div>
</template>
