// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarGroup.tsx
import type * as React from "react";
import { sidebarGroup } from "./variants";

export type SidebarGroupProps = React.ComponentPropsWithoutRef<"div"> & {
  ref?: React.Ref<HTMLDivElement>;
  "data-slot"?: string;
};

function SidebarGroup(props: SidebarGroupProps) {
  const { ref, "data-slot": dataSlot = "sidebar-group", className, children, ...rest } = props;

  return (
    <div
      className={sidebarGroup({ class: className })}
      data-sidebar="group"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </div>
  );
}

export default SidebarGroup;

// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarGroup.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarGroup } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarGroupProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarGroupDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarGroupProps, "data-slot">;
const { dataSlot = "sidebar-group", class: className } = defineProps<SidebarGroupDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div
    :class="sidebarGroup({ class: className })"
    data-sidebar="group"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </div>
</template>
