// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarInset.tsx
import type * as React from "react";
import { sidebarInset } from "./variants";

export type SidebarInsetProps = React.ComponentPropsWithoutRef<"main"> & {
  ref?: React.Ref<HTMLDivElement>;
  "data-slot"?: string;
};

function SidebarInset(props: SidebarInsetProps) {
  const { ref, "data-slot": dataSlot = "sidebar-inset", className, children, ...rest } = props;

  return (
    <main className={sidebarInset({ class: className })} {...rest} ref={ref} data-slot={dataSlot}>
      {children}
    </main>
  );
}

export default SidebarInset;

// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarInset.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarInset } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarInsetProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarInsetDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarInsetProps, "data-slot">;
const { dataSlot = "sidebar-inset", class: className } = defineProps<SidebarInsetDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <main :class="sidebarInset({ class: className })" v-bind="$attrs" :data-slot="dataSlot">
    <slot />
  </main>
</template>
