// apps/react-demo/src/components/starwind-runtime/sidebar/SidebarMenuSubItem.tsx
import type * as React from "react";
import { sidebarMenuSubItem } from "./variants";

export type SidebarMenuSubItemProps = React.ComponentPropsWithoutRef<"li"> & {
  ref?: React.Ref<HTMLLIElement>;
  "data-slot"?: string;
};

function SidebarMenuSubItem(props: SidebarMenuSubItemProps) {
  const {
    ref,
    "data-slot": dataSlot = "sidebar-menu-sub-item",
    className,
    children,
    ...rest
  } = props;

  return (
    <li
      className={sidebarMenuSubItem({ class: className })}
      data-sidebar="menu-sub-item"
      {...rest}
      ref={ref}
      data-slot={dataSlot}
    >
      {children}
    </li>
  );
}

export default SidebarMenuSubItem;

// apps/vue-demo/src/components/starwind-runtime/sidebar/SidebarMenuSubItem.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { sidebarMenuSubItem } from "./variants";

defineOptions({ inheritAttrs: false });

export type SidebarMenuSubItemProps = Omit<HTMLAttributes, "class" | "data-slot"> & {
  "data-slot"?: string;
  class?: ClassValue;
};
type SidebarMenuSubItemDeclaredProps = {
  dataSlot?: string;
  class?: ClassValue;
} & /* @vue-ignore */ Omit<SidebarMenuSubItemProps, "data-slot">;
const { dataSlot = "sidebar-menu-sub-item", class: className } =
  defineProps<SidebarMenuSubItemDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <li
    :class="sidebarMenuSubItem({ class: className })"
    data-sidebar="menu-sub-item"
    v-bind="$attrs"
    :data-slot="dataSlot"
  >
    <slot />
  </li>
</template>
