// apps/react-demo/src/components/starwind-runtime/navigation-menu/NavigationMenuPositioner.tsx
"use client";

import NavigationMenuPrimitive from "@starwind-ui/react/navigation-menu";
import type * as React from "react";
import { navigationMenuPopup, navigationMenuPositioner, navigationMenuViewport } from "./variants";

export type NavigationMenuPositionerProps = React.ComponentPropsWithoutRef<"div"> & {
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  alignOffset?: number;
  avoidCollisions?: boolean;
  collisionPadding?: number;
  size?: "sm" | "md";
  portalContainer?: string;
  disablePortal?: boolean;
};

function NavigationMenuPositioner(props: NavigationMenuPositionerProps) {
  const {
    side = "bottom",
    align = "start",
    sideOffset = 8,
    alignOffset = 0,
    avoidCollisions = true,
    collisionPadding = 8,
    size = "md",
    className,
    portalContainer,
    disablePortal = false,
    ...rest
  } = props;

  return (
    <NavigationMenuPrimitive.Portal
      container={portalContainer}
      disabled={disablePortal}
      data-slot="navigation-menu-portal"
    >
      <NavigationMenuPrimitive.Positioner
        className={navigationMenuPositioner({ class: className })}
        side={side}
        align={align}
        sideOffset={sideOffset}
        alignOffset={alignOffset}
        avoidCollisions={avoidCollisions}
        collisionPadding={collisionPadding}
        {...rest}
        data-size={size}
        data-slot="navigation-menu-positioner"
      >
        <NavigationMenuPrimitive.Popup
          className={navigationMenuPopup()}
          data-slot="navigation-menu-popup"
        >
          <NavigationMenuPrimitive.Viewport
            className={navigationMenuViewport()}
            data-slot="navigation-menu-viewport"
          />
        </NavigationMenuPrimitive.Popup>
      </NavigationMenuPrimitive.Positioner>
    </NavigationMenuPrimitive.Portal>
  );
}

export default NavigationMenuPositioner;

// apps/svelte-demo/src/lib/starwind-runtime/navigation-menu/NavigationMenuPositioner.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { NavigationMenuPositioner, NavigationMenuPortal } from "@starwind-ui/svelte/navigation-menu";
  import { cx } from "tailwind-variants";
  import { navigationMenu, navigationMenuList, navigationMenuItem, navigationMenuTrigger, navigationMenuIndicator, navigationMenuContent, navigationMenuLink, navigationMenuPositioner, navigationMenuPopup, navigationMenuViewport } from "./variants.js";
  import { NavigationMenuPopup } from "@starwind-ui/svelte/navigation-menu";
  import { NavigationMenuViewport } from "@starwind-ui/svelte/navigation-menu";

  export type NavigationMenuPositionerProps = ComponentProps<typeof NavigationMenuPositioner> & { side?: "top" | "right" | "bottom" | "left"; align?: "start" | "center" | "end"; sideOffset?: number; alignOffset?: number; avoidCollisions?: boolean; collisionPadding?: number; size?: "sm" | "md"; disablePortal?: boolean; portalContainer?: ComponentProps<typeof NavigationMenuPortal>["container"]; };
</script>

<script lang="ts">
  let {
    "side": side = "bottom",
    "align": align = "start",
    "sideOffset": sideOffset = 8,
    "alignOffset": alignOffset = 0,
    "avoidCollisions": avoidCollisions = true,
    "collisionPadding": collisionPadding = 8,
    "size": size = "md",
    "class": className,
    "portalContainer": portalContainer,
    "disablePortal": disablePortal = false,
    "children": children,
    ...rest
  }: NavigationMenuPositionerProps = $props();
</script>

<NavigationMenuPortal
  container={portalContainer}
  disabled={disablePortal}
  data-slot={"navigation-menu-portal"}
>
  <NavigationMenuPositioner
    class={navigationMenuPositioner({ "class": cx(className) })}
    side={side}
    align={align}
    sideOffset={sideOffset}
    alignOffset={alignOffset}
    avoidCollisions={avoidCollisions}
    collisionPadding={collisionPadding}
    {...rest}
    data-size={size}
    data-slot={"navigation-menu-positioner"}
  >
    <NavigationMenuPopup
      class={navigationMenuPopup({  })}
      data-slot={"navigation-menu-popup"}
    >
      <NavigationMenuViewport
        class={navigationMenuViewport({  })}
        data-slot={"navigation-menu-viewport"}
      >

      </NavigationMenuViewport>
    </NavigationMenuPopup>
  </NavigationMenuPositioner>
</NavigationMenuPortal>
