// apps/react-demo/src/components/starwind-runtime/navigation-menu/NavigationMenu.tsx
"use client";

import NavigationMenuPrimitive from "@starwind-ui/react/navigation-menu";
import type * as React from "react";
import NavigationMenuPositioner from "./NavigationMenuPositioner";
import { navigationMenu } from "./variants";

export type NavigationMenuProps = Omit<
  React.ComponentPropsWithoutRef<"nav">,
  "defaultValue" | "onChange" | "value"
> & {
  defaultValue?: string | null;
  value?: string | null;
  openDelay?: number;
  closeDelay?: number;
  closeOnEscape?: boolean;
  closeOnOutsideInteract?: boolean;
  orientation?: "horizontal" | "vertical";
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  sideOffset?: number;
  alignOffset?: number;
  avoidCollisions?: boolean;
  collisionPadding?: number;
  size?: "sm" | "md";
  portalContainer?: string;
  disablePortal?: boolean;
  contentSize?: "sm" | "md";
  onValueChange?: (
    value: string | null,
    details: import("@starwind-ui/react/navigation-menu").NavigationMenuValueChangeDetails,
  ) => void;
};

function NavigationMenu(props: NavigationMenuProps) {
  const {
    defaultValue = null,
    value,
    openDelay = 50,
    closeDelay = 50,
    closeOnEscape = true,
    closeOnOutsideInteract = true,
    orientation = "horizontal",
    side = "bottom",
    align = "start",
    sideOffset = 8,
    alignOffset = 0,
    avoidCollisions = true,
    collisionPadding = 8,
    size = "md",
    contentSize = size,
    onValueChange,
    className,
    portalContainer,
    disablePortal = false,
    children,
    ...rest
  } = props;

  return (
    <NavigationMenuPrimitive.Root
      className={navigationMenu({ class: className })}
      defaultValue={defaultValue}
      value={value}
      openDelay={openDelay}
      closeDelay={closeDelay}
      closeOnEscape={closeOnEscape}
      closeOnOutsideInteract={closeOnOutsideInteract}
      orientation={orientation}
      onValueChange={onValueChange}
      {...rest}
      data-size={size}
      data-slot="navigation-menu"
    >
      {children}

      <NavigationMenuPositioner
        side={side}
        align={align}
        sideOffset={sideOffset}
        alignOffset={alignOffset}
        avoidCollisions={avoidCollisions}
        collisionPadding={collisionPadding}
        size={contentSize}
        portalContainer={portalContainer}
        disablePortal={disablePortal}
      />
    </NavigationMenuPrimitive.Root>
  );
}

export default NavigationMenu;

// apps/svelte-demo/src/lib/starwind-runtime/navigation-menu/NavigationMenu.svelte
<script module lang="ts">
  import type { ComponentProps, Snippet } from "svelte";
  import { NavigationMenuRoot, NavigationMenuPortal } from "@starwind-ui/svelte/navigation-menu";
  import { cx } from "tailwind-variants";
  import { navigationMenu, navigationMenuList, navigationMenuItem, navigationMenuTrigger, navigationMenuIndicator, navigationMenuContent, navigationMenuLink, navigationMenuPositioner, navigationMenuPopup, navigationMenuViewport } from "./variants.js";
  import { default as NavigationMenuPositioner } from "./NavigationMenuPositioner.svelte";

  export type NavigationMenuProps = ComponentProps<typeof NavigationMenuRoot> & { defaultValue?: string | null; openDelay?: number; closeDelay?: number; closeOnEscape?: boolean; closeOnOutsideInteract?: boolean; orientation?: "horizontal" | "vertical"; side?: "top" | "right" | "bottom" | "left"; align?: "start" | "center" | "end"; sideOffset?: number; alignOffset?: number; avoidCollisions?: boolean; collisionPadding?: number; size?: "sm" | "md"; disablePortal?: boolean; contentSize?: "sm" | "md"; portalContainer?: ComponentProps<typeof NavigationMenuPortal>["container"]; };
</script>

<script lang="ts">
  let {
    "defaultValue": defaultValue = null,
    "openDelay": openDelay = 50,
    "closeDelay": closeDelay = 50,
    "closeOnEscape": closeOnEscape = true,
    "closeOnOutsideInteract": closeOnOutsideInteract = true,
    "orientation": orientation = "horizontal",
    "side": side = "bottom",
    "align": align = "start",
    "sideOffset": sideOffset = 8,
    "alignOffset": alignOffset = 0,
    "avoidCollisions": avoidCollisions = true,
    "collisionPadding": collisionPadding = 8,
    "size": size = "md",
    "contentSize": contentSize = size,
    "class": className,
    "portalContainer": portalContainer,
    "disablePortal": disablePortal = false,
    value = $bindable(),
    "onValueChange": onValueChange,
    "children": consumerChildren,
    ...rest
  }: NavigationMenuProps = $props();
</script>

<NavigationMenuRoot
  class={navigationMenu({ "class": cx(className) })}
  defaultValue={defaultValue}
  openDelay={openDelay}
  closeDelay={closeDelay}
  closeOnEscape={closeOnEscape}
  closeOnOutsideInteract={closeOnOutsideInteract}
  orientation={orientation}
  {...rest}
  data-size={size}
  data-slot={"navigation-menu"}
  onValueChange={onValueChange}
  bind:value={value}
>
  {#snippet children(acceptedValue)}
    {@render consumerChildren?.(acceptedValue)}
    <NavigationMenuPositioner
      side={side}
      align={align}
      sideOffset={sideOffset}
      alignOffset={alignOffset}
      avoidCollisions={avoidCollisions}
      collisionPadding={collisionPadding}
      size={contentSize}
      portalContainer={portalContainer}
      disablePortal={disablePortal}
    >

    </NavigationMenuPositioner>
  {/snippet}
</NavigationMenuRoot>
