// apps/react-demo/src/components/starwind-runtime/skeleton/Skeleton.tsx
import type * as React from "react";
import { skeleton } from "./variants";

export type SkeletonProps = Omit<React.ComponentPropsWithoutRef<"div">, "children"> & {
  ref?: React.Ref<HTMLDivElement>;
};

function Skeleton(props: SkeletonProps) {
  const { ref, className, ...rest } = props;

  return (
    <div
      data-sw-skeleton
      className={skeleton({ class: className })}
      {...rest}
      ref={ref}
      data-slot="skeleton"
    />
  );
}

export default Skeleton;

// apps/vue-demo/src/components/starwind-runtime/skeleton/Skeleton.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes, ref } from "vue";
import { skeleton } from "./variants";

defineOptions({ inheritAttrs: false });

export type SkeletonProps = Omit<HTMLAttributes, "children" | "class"> & {
  class?: ClassValue;
};
type SkeletonDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ SkeletonProps;
const { class: className } = defineProps<SkeletonDeclaredProps>();
defineSlots<{}>();
const element = ref<HTMLDivElement | null>(null);
defineExpose({ element });
</script>

<template>
  <div
    ref="element"
    data-sw-skeleton
    :class="skeleton({ class: className })"
    v-bind="$attrs"
    data-slot="skeleton"
  />
</template>
