// apps/vue-demo/src/components/starwind-runtime/dialog/DialogHeader.vue
<script setup lang="ts">
import type { ClassValue } from "tailwind-variants";
import { type HTMLAttributes } from "vue";
import { dialogHeader } from "./variants";

defineOptions({ inheritAttrs: false });

export type DialogHeaderProps = Omit<HTMLAttributes, "class"> & {
  class?: ClassValue;
};
type DialogHeaderDeclaredProps = {
  class?: ClassValue;
} & /* @vue-ignore */ DialogHeaderProps;
const { class: className } = defineProps<DialogHeaderDeclaredProps>();
defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <div :class="dialogHeader({ class: className })" v-bind="$attrs" data-slot="dialog-header">
    <slot />
  </div>
</template>

// apps/react-demo/src/components/starwind-runtime/dialog/DialogHeader.tsx
import type * as React from "react";
import { dialogHeader } from "./variants";

export type DialogHeaderProps = React.ComponentPropsWithoutRef<"div">;

function DialogHeader(props: DialogHeaderProps) {
  const { className, children, ...rest } = props;

  return (
    <div className={dialogHeader({ class: className })} {...rest} data-slot="dialog-header">
      {children}
    </div>
  );
}

export default DialogHeader;
